### ISSUE TITLE
Using CockroachDB as meta-data database

### ISSUE THREAD

**Issue by roboptics** [hasura/graphql-engine#10010]
### Version Information

Server Version: 2.35.1

### Environment

Docker / linux

### What is the current behaviour?

Cannot connect to a secure cockroachdb database (using ssl). The error below is shown:
"pgcrypto extension is required, but could not find the extension in the PostgreSQL server. Please make sure this extension is available."

### What is the expected behaviour?

Would be great if we could use CockroachDB instead of Postgres.

### How to reproduce the issue?

1. Simply try to point the meta-data database to a cockroachdb instance in secure mode (using SSL).

### Keywords

cockroachdb graphql-engine database meta-data

**Comment by manasag** [comment]
This is not planned to be supported due to some postgres extension features Hasura relies on. 
We would recommend to review Hasura [V3](https://hasura.io/docs/3.0/getting-started/overview/), which is built to be stateless, and doesn't require a database as a dependency. The metadata is provided as a mounted file. Currently V3 is cloud only, but soon would be released in Open Source if you want to try locally.
