### ISSUE TITLE
GRPC/ Protobuffer support for Hasura Actions

### ISSUE THREAD

**Issue by spoilerdo** [hasura/graphql-engine#10104]
### Is your proposal related to a problem?
It is not really a problem but it would make connecting my back-end to Hasura more secure and communication go faster, and all the other advantages GRPC has in comparison with REST.

### Describe the solution you'd like
It would be nice to instead of making Actions using REST, to be able to define an action using protobuffers and make the communication between Hasura and back-end go trough GRPC. It is still an upcoming technology but I think it also would be a great opportunity for improving the integration of Hasura to future systems.

**Comment by manasag** [comment]
Hi @spoilerdo, In Hasura V3 architecture, Actions are now powered by Connectors. Connectors based on a standardised SDK provided by Hasura can help integrate any external APIs, business logic into Hasura. To start with, we are building Typescript based connectors (e.g. [NodeJS connector](https://github.com/hasura/ndc-nodejs-lambda)). In V3 world, it's would be much easy to write a gRPC connector as you described. 

We would like to understand your gRPC requirements (shape of protobufs etc), that helps us work on early designs and may be provide guidance on connector development.
ccing @rahulagarwal13 @soorajshankar @daniel-chambers @TristenHarr

**Comment by spoilerdo** [comment]
Thx for the quick response. I am looking forward to Hasura V3 then :))

**Comment by almereyda** [comment]
I think there was a misunderstanding. Hasura v3 was [released 2023-12-19](https://hasura.io/blog/announcing-open-source-hasura-graphql-engine-v3/) and has been available at the time of writing already.

The chance here is to scope a gRPC Connector built with the Hasura SDK to implement custon gRPC Actions.

@spoilerdo Would you like to share your use case, in so other interested parties can learn from it? Sharing your general or specific requirements will allow developers taking on the task to know what is being expected.

Since this conversation didn't happen such a long time ago, this may still be an ongoing concern of yours?

**Comment by almereyda** [comment]
I think there was a misunderstanding. Hasura v3 was [released 2023-12-19](https://hasura.io/blog/announcing-open-source-hasura-graphql-engine-v3/) and has been available at the time of writing already.

The chance here is to scope a gRPC Connector built with the Hasura SDK to implement custon gRPC Actions.

@spoilerdo Would you like to share your use case, in so other interested parties can learn from it? Sharing your general or specific requirements will allow developers taking on the task to know what is being expected.

Since this conversation didn't happen such a long time ago, this may still be an ongoing concern of yours?

*Edit:* The v3 work has been *announced*, not *released. It happens around the corner in:

https://github.com/hasura/graphql-engine/tree/master/v3
