### ISSUE TITLE
Console: Command Relationships do not show

### ISSUE THREAD

**Issue by rahulagarwal13** [hasura/graphql-engine#10452]
### What is the current behaviour?
Relationships for commands should show just like for a model but currently they do not come up on the console

<img width="1411" alt="image" src="https://github.com/user-attachments/assets/202fd6f6-dd4e-417b-b290-1682a32b351a">
See below, relationships exist for the same command
<img width="1130" alt="image" src="https://github.com/user-attachments/assets/145b791b-adc1-459c-ae9c-1fb37e7079b6">

**Comment by soorajshankar** [comment]
Related https://github.com/hasura/graphql-engine/issues/10452

**Comment by soorajshankar** [comment]
To summarize, the current view displays all relationships originating from the selected entity but does not include those pointing to the selected entity. 

By including a table view that shows both incoming and outgoing relationships, domain owners will be able to explore an entity much more quickly and efficiently. (which otherwise would be a bit more time taking to identify from large supergraph explorer views -IMO)
