### ISSUE TITLE
Create TABLE with NOT NULL is ignored and used as nullable

### ISSUE THREAD

**Issue by git-no** [hasura/graphql-engine#1050]
Creating TABLE with NOT NULL is ignored and used as nullable via SQL in Hasura GUI, e.g.

```sql
CREATE TABLE mytable (
   id INTEGER PRIMARY KEY, 
   name VARCHAR(80) NOT NULL
);
```

It is possible to create a record with empty name via INSERT ROW in the Hasura GUI.
The name column is listed as nullable in the section MODIFY in the Hasura GUI.

**Comment by praveenweb** [comment]
@git-no , Hey, you have mentioned two issues.
1) > It is possible to create a record with empty name via INSERT ROW in the Hasura GUI

If the column is NOT NULL, it means that the column value cannot be `NULL`, but it can have any other values including empty string. This is expected behavior.

2) > The name column is listed as nullable in the section MODIFY in the Hasura GUI

I could not replicate this. I used the SQL given above and when i navigate to Modify section -> `name` column edit, i see `NULLABLE` as `False` (which is expected behavior).

<img width="642" alt="screenshot 2018-11-18 at 9 13 31 am" src="https://user-images.githubusercontent.com/14110316/48668399-3f601400-eb12-11e8-9faa-7ba060bb81c5.png">

**Comment by praveenweb** [comment]
@git-no - Ah, got it. The first section that you have highlighted Nullable is for Adding a new column. The second nullable section that you have highlighted is for editing an existing column.

When you are adding a new column, we have enabled `Nullable` by default since thats normal behavior. (This is the list view that you are referring to, and it is not for existing columns). 

When you are editing a column, it is reflecting your original column's nullable property (in your case it is false as expected).

May be we can add a separator to distinguish the two views to avoid confusion :)

**Comment by git-no** [comment]
Oh, I'm so sorry. Sure it makes absolut sense how you describe it. Maybe we see it as user test. I was blind. 
Have tested it now, works perfect. i was misleaded. Sorry bothering you. By the way, your product is great. Very easy to start, to model a schema/db and get live with graphql.

**Comment by git-no** [comment]
Just a suggestion: maybe you put a little more space between the last existing column and the create new column bar.
