### ISSUE TITLE
open-api connector headers

### ISSUE THREAD

**Issue by durkino** [hasura/graphql-engine#10628]
### Component

c/v3-ndc-open-api-lambda

### What is the current behaviour?

I am opening this issue based on [this other issue](https://github.com/hasura/ndc-open-api-lambda/issues/65) (which I seemingly opened in the wrong place).

It is unclear how to use HTTP headers in the open api endpoint. For example, using the ddn console for the Auckland museum api, if I create a `postSparqlPostSparql` mutation and add the `headers` parameter, it adds it to the mutation as an empty string.
```graphql
mutation MyMutation {
  postSparqlPostSparql(data: {query: ""}, headers: "")
}
```
but correct use of the endpoint looks like this. Note that `headers` is not a string.
```graphql
mutation MyMutation {
  postSparqlPostSparql(
    data: {
      query: "PREFIX ecrm:<http://erlangen-crm.org/current/>     SELECT ?subject WHERE {       ?subject ecrm:P45_consists_of/ecrm:P2_has_type <http://api.aucklandmuseum.com/id/thesauri/material/AAT.11914>     }     LIMIT 10"
    }
    headers: {
      accept: "application/sparql-results+json"
    }
  )
}
```
Also, if an HTTP endpoint expects a header with a hyphen in its name then it seems impossible to use it since GraphQL prohibits hyphens (e.g. `Accept-Encoding` or `Accept-Language` or any custom header with a hyphen).

### What is the expected behaviour?

The format for passing HTTP headers in the GraphQL headers argument should be documented in the ndc-open-api-lambda repo.

Adding the "headers" parameter should not default to an empty string in the DDN console GraphiQL interface since this is misleading.

There should be a way to pass HTTP headers that include hyphens in their name.

### How to reproduce the issue?

See [here](https://github.com/hasura/ndc-open-api-lambda/issues/65)

### Keywords

ddn
open api data connector
http headers

**Comment by robertjdominguez** [comment]
Thanks for this @durkino — I'm tagging the connector's primary author to see if he can help you.

cc @m-Bilal

**Comment by m-Bilal** [comment]
Hi @durkino , that was an excellent report, thanks! 

First off, the place you had opened the last issue was not the wrong place. The reason it didn't get a reply was because you figured out a solution on your own (great work btw!)

Second, sorry we had missed out documenting this. I added the documentation and while that PR awaits a review, [here's the early documentation link](https://github.com/hasura/ndc-open-api-lambda/blob/fe335c0c0dafd4efd2cf8de7ec2bec416adfdb9e/docs/documentation.md#adding-custom-headers-to-apis) so that you can be unblocked. Again, apologies for the confusion this has been causing, and, thanks again for bringing this to our attention.
