### ISSUE TITLE
Include hostname in auth webhook?

### ISSUE THREAD

**Issue by bs1180** [hasura/graphql-engine#1103]
This is a great project, thanks!

I'm experimenting with using it in a multi-tenant setup, where the tenant is decided by the subdomain (eg. foo.example.com is tenant foo), and the authentication webhook includes a x-hasura-tenant-id in the response. Unfortunately the headers passed to the webhook don't include the original hostname, so this approach is impossible.

I think it would be useful for the webhooks (and perhaps also the forthcoming schema stitching) to forward more details about the original request, so my server can make use of the original IP address, useragent etc.

Thanks.

**Comment by 0x777** [comment]
Using `GET` for the webhook and passing client headers as HTTP headers was a bad choice that we made, because of which when graphql-engine is making a request to the webhook it cannot use send some of the client headers, `Host` being one of them. We'll add a new `POST` webhook call behavior so thatl all the client headers can be sent in the `POST` body.
