### ISSUE TITLE
document that migration version cannot be 0

### ISSUE THREAD

**Issue by polymeris** [hasura/graphql-engine#1108]
I am running `hasura/graphql-engine:v1.0.0-alpha30.cli-migrations` using docker-compose.

When I start it, it correctly applies migrations numbered 0 and 1 from `0_schema.up.sql`  
and `1_metadata.up.yaml`, respectively, resulting in:
```
postgres=# select * from hdb_catalog.schema_migrations;
 version | dirty 
---------+-------
       1 | f
(1 row)
```
However, when I restart the service, it tries to apply migration 0 again, which fails, because the tables already exist.

**Comment by shahidhk** [comment]
@polymeris If you have 2 migration files, namely

```
0_schema.up.sql
1_metadata.up.yaml
```

after applying migrations, the state of the database should be:
```
postgres=# select * from hdb_catalog.schema_migrations;
 version | dirty 
---------+-------
       0 | f
       1 | f
(2 row)
```

I am not sure why version 0 is not applied. Can you check this with `hasura migrate status`?

When you restart the container, the behaviour is to apply them again, since the apply command checks what is applied and what is not applied and only applies the ones that are new.
 

@coco98, the `cli-migrations` image can be used to run the server, withour any issues.

**Comment by shahidhk** [comment]
> it tries to apply migration 0 again, which fails, because the tables already exist.

@polymeris This happens because the info in db says 0 is not applied, despite it being applied already. Can you see what the status is? Also, if possible, share the migration files?

**Comment by polymeris** [comment]
@shahidhk 
`hasura migrate status` says:
```
VERSION  SOURCE STATUS  DATABASE STATUS
0        Present        Not Present
1        Present        Present
```

**Comment by polymeris** [comment]
I have changed the names of the files to be `1_schema.up.sql` and `2_metadata.up.yaml` and now `hasura migrate status` returns:

```
VERSION  SOURCE STATUS  DATABASE STATUS
1        Present        Present
2        Present        Present
```

I think it just doesn't like having a version 0, for some reason.

**Comment by shahidhk** [comment]
Makes sense. I'm guessing CLI doesn't accept zero since 0 for an int type
is treated as null value in Go.
