### ISSUE TITLE
How to send userId in events payloads?

### ISSUE THREAD

**Issue by jakobrosenberg** [hasura/graphql-engine#1323]
Is this possible?

For instance. I have three tables: USERS, ORGANIZATIONS and ROLES. After a user creates an organization, I want a new entry in ROLES: {userId: 123, organizationId:456, role: 'collaborator'}.

**Comment by tirumaraiselvan** [comment]
@jakobrosenberg Does you organization table not have the userId?

**Comment by coco98** [comment]
@jakobrosenberg Like @tirumaraiselvan  said, in this particular case, it might be better to solve this is by having a `creator_id` in the organisation table, because you might need that information anyway. Further more, you can create an insert permission on the organisation table to ensure that a user can only create an organisation id where they are the creator `creator_id: _eq: x-hasura-user-id`.

But to answer your question, in a more general sense this should be possible to add to our event payload quite easily because our triggers actually have the user session context. We can capture the session-variables of the user that caused a certain event to run. This way, the organisation create event will have the user_id in the payload.

**Comment by jakobrosenberg** [comment]
Thanks for your answers @tirumaraiselvan and @coco98 

@coco98 When you say this should be add, you mean on your end, right? Or is there something I can do include the user session context?

**Comment by tirumaraiselvan** [comment]
@jakobrosenberg Yes, we should be able to add it as a feature soon. 

Also for the time being, are you okay with having the userId/creatorId field in the organisation table?

**Comment by jakobrosenberg** [comment]
@tirumaraiselvan yes, that shouldn't be much of a problem. Most likely though, I'll add a server to handle business logic and use Hasura as an ORM instead.

**Comment by tirumaraiselvan** [comment]
Okay, we are tracking the feature here: https://github.com/hasura/graphql-engine/issues/1328
