### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mzgnr** [hasura/graphql-engine#139]
Do you have any roadmap for stable release ?

**Comment by 0x777** [comment]
We tag our current releases `alpha` only because we are in the final stages of adding features and it might break the API. The server itself is battle tested fairly well. So you shouldn't encounter any issues using the current release in any environment except for a couple of bugs.

That being said I'll draft out a roadmap soon. The rough plan is to promote the current alpha releases to beta by the end of this week.

**Comment by mzgnr** [comment]
I'm really excited about this project. I could also help on `Console` if you had roadmap, feature list :)

**Comment by shahidhk** [comment]
@0x777 Let's take a call on this? Or link to a project board instead?

**Comment by ecthiender** [comment]
We are already doing milestones, and associating issues with milestones. Does that work for a roadmap for upcoming releases ?

**Comment by shahidhk** [comment]
The roadmap for upcoming releases can be found here: https://github.com/hasura/graphql-engine/milestones
