### ISSUE TITLE
How to mark certain columns as required fields in the generated GraphQL schema

### ISSUE THREAD

**Issue by venelin-mihaylov** [hasura/graphql-engine#1433]
Not nullable fields in the database are not exposed through the graphql schema as required.
Is this by design? Shouldn't non nullable fields be required?

**Comment by 0x777** [comment]
The schema generation logic respects the nullability of columns in the database. Can you give us an example where this is not as expected?

**Comment by venelin-mihaylov** [comment]
I created a very simple table "test", with "id" and "test" nonNullable field, and the "test" field was not marked with "!" in "test_insert_input" . 
What info would you like to have to reproduce the issue?

**Comment by 0x777** [comment]
Unfortunately `NOT NULL` constraint does not imply that the column value **has** to be provided. A column can have a `NOT NULL` constraint with a `DEFAULT` value, or the value can be set inside a Postgres trigger. So it will be incorrect to generate a not-null type("`!`") for such column in the input (as the column value need not be provided at all). Postgres does not provide information on whether a column input needs to be provided for a table (it cannot). 

However, `NOT NULL` constraint implies that the data returned will never be `NULL` and so we generate not-null types for non nullable columns in the object type for a table response.

**Comment by venelin-mihaylov** [comment]
I understand. Is there another way for an input field to be marked as mandatory then?

**Comment by ajayar** [comment]
Any update? I too am looking for this feature. Our frontend team often struggle with figuring out the min required fields.

**Comment by ajayar** [comment]
perhaps you can add one more checkbox next to the col definition in the console.

**Comment by hmexx** [comment]
@ajayar That seems like a reasonable solution. Adding a "REQUIRED" checkbox that's unchecked by default would preserve backward compatibility. 

With a little tooltip that explains why REQUIRED and NOT NULL are not the same thing.

**Comment by smeevil** [comment]
That would be a nice solution indeed. I came here looking for the exact same thing.

**Comment by wu-s-john** [comment]
Omg, yes please add this

**Comment by CharlonTank** [comment]
Please, I use elm-graqhl, I need to be able to set fields as required.

**Comment by maxcan** [comment]
@0x777 / @coco98 its true that `NOT NULL` columns can have defaults but it would be nice for schemas to mark fields as required if they are but `NOT NULL` and don't have a default.  Since this would be a breaking change, it seems reasonable to flag it behind an environment setting.  

Another option would be to expose two different insertion mutation with different insertion types - one would have current behavior and then a strict version of each which requires all fields which are `NOT NULL` and don't have defaults.  field by field overrides could work too, but I see this as more complicated

**Comment by maxcan** [comment]
@venelin-mihaylov  @wu-s-john if you're using typescript, i have a workaround:

This will create versions of input types were scalar fields are required and fields that commonly have defaults are excluded.  This assumes you are using graphql-code-generator with defaults.


```typescript
type SubtractKeys<T, U> = {
  [K in keyof T]: T[K] extends U ? K : never;
}[keyof T];

type Subtract<T, U> = { [K in SubtractKeys<T, U>]: T[K] };

type ExcludeCommonCalcedFields<T> = Required<
  Omit<T, "deleted_at" | "id" | "updated_at" | "created_at">
>;
type MakeMaybesRequired<T> = { [k in keyof T]: Exclude<T[k], null> };

type ScalarFieldTypes = string | number | boolean | Date;
type NonScalarFieldsKeys<T, U = ScalarFieldTypes> = Subtract<T, U>;
type ExcludeNonScalars<T> = {
  [k in keyof NonScalarFieldsKeys<T>]: NonScalarFieldsKeys<T>[k];
};
export type ReqInsertArr<T, E extends string = ""> = Array<ReqInsert<T>>;
export type ReqInsert<T, E extends string = ""> = Omit<
  ExcludeNonScalars<MakeMaybesRequired<ExcludeCommonCalcedFields<T>>>,
  E
>;
```

**Comment by CharlonTank** [comment]
I'm using elm, I hope this gonna be a feature at some point, I might PR too

**Comment by maxcan** [comment]
ping..

**Comment by CharlonTank** [comment]
pleasssse <3

**Comment by beepsoft** [comment]
Wouldn't it be possible to generate directives in the schema to define constraints of fields? 

In case of input types we could have eg @required or similar to mark it as a required field.

There could also be directives for ranges, regexp validation strings, etc.

**Comment by ryanberckmans** [comment]
This would be really useful.

My generated types are full of

```
foo?: Maybe<Scalars['String']>;
```

When in fact I know that foo will never be null.

**Comment by VRspace4** [comment]
I was excited to introduce Hasura to the team until I found this limitation. This, at least to me, is a show stopper if front end developers can't easily tell which GraphQL fields are required and which are optional.

**Comment by ziahamza** [comment]
This makes our mutation code super fragile, and requires each pass to either go through manual or automated testing to ensure no compulsory field is missed

manually adding a check-box would be of huge help. We are currently wrapping all mutations with proper typed code, and have to manually maintain it as fields become non-nullable.

I think its even safe to be more aggressive and be on the safe side to mark it as compulsory if the field is non-nullable in the graphql API, and allow it to be override otherwise (there can also be a --strict-mutations flag)

**Comment by maxcan** [comment]
My current workaround is to avoid using the generated input types and just pass individual scalar fields as arguments to mutations.  This at least shifts the burden onto writing the GQL queries but at least my generated typescript code (thank you graphql code generator) will enforce the correct types.

**Comment by ghry5** [comment]
Having a required checkbox should be a fairly simple solution. Imo it would be great to move this into the create/update permissions since this would give more flexibility. 
That way a create from a user role could require different fields than a admin role. Also this would embed nicely in the existing metadata for permssions.

**Comment by carlosbaraza** [comment]
Looking forward to this being fixed. It is quite frustrating, because it defeats the whole point of having strong typing... Mutations could easily break at runtime because you missed a null value when calling the mutation, because the column doesn't allow null values and doesn't set defaults. I wish the compiler would break and remind me to action on that potentially null variable. Instead, this breaks at runtime...

An environment variable to enable this feature for any column without a default value would be my preferred solution. Otherwise, the checkbox for mandatory input would be an easy enough setup.

**Comment by maaft** [comment]
WHAT THE ???

This should have been implemented like 2 years ago. 

It really makes the mutation side very fragile.

**Comment by maaft** [comment]
@0x777 Hello?

**Comment by Estifanos-Neway** [comment]
I came here looking for the exact same thing, any update?

**Comment by roryacuity** [comment]
Bumping request for status on this flaw. If a field is:

1. Non-nullable at the database level
2. Does not have a default value at the database level
3. Does not have a **Column Preset** at the Hasura level

then I believe we can know for sure that this field is required on the insert input type.

Short the ability to detect this state without additional configuration, a "require this field to be explicitly set" checkbox in **Column Insert Permissions** would help a ton.

**Comment by maaft** [comment]
@roryacuity

Fields could also be set by e.g. insert triggers.

The "require" option on permission is imho the only way for now. Should also be straight forward to be implemented.

**Comment by roryacuity** [comment]
@maaft yes, that's correct, thank you. Explicit configuration is a more realistic option than trying to account for every possible way the column could be set on an insert mutation.

**Comment by maxcan** [comment]
Agree about explicit configuration. Should be a metadata option.

**Comment by joanrodriguez** [comment]
+1 This would be nice

**Comment by michael-land** [comment]
need this

**Comment by manasag** [comment]
Thanks everyone for your comments and patience on this issue. We have been closely listening into all the feedback and requests from the community, and have been working on a re-imagined, re-architectured Hasura, that tackles many of these from ground up. 
We are pleased to announce that we are launching V3-Alpha of Hasura ([Data Delivery Network](https://hasura.io/ddn)) on our next Community call on Nov 30. The new metadata structure in V3 is designed to be highly flexible and declarative, to support the perfect GraphQL schema you would like to achieve. While building this metadata in V3, you would have the control to decide which columns are to be marked as required.
We would request to join this [community call](https://hasura.io/events/community-call/latest) to learn more about Hasura V3. Post launch, we will update this ticket with relevant details.

**Comment by dameleney** [comment]
This is now possible using [Hasura DDN](https://hasura.io/ddn). 

> When specifying the types of a field or an argument, you can mark them as required ! or repeated []. 
[link to docs](https://hasura.io/docs/3.0/supergraph-modeling/types/#introduction:~:text=When%20specifying%20the%20types%20of%20a%20field%20or%20an%20argument%2C%20you%20can%20mark%20them%20as%20required%20!%20or%20repeated%20%5B%5D).

Follow our getting started docs [here](https://hasura.io/docs/3.0/local-dev/) to get started with Hasura DDN.

**Comment by Jokero** [comment]
@manasag Any plans to port it to v2?
