### ISSUE TITLE
Send previous invocation response in the request payload for even triggers in case of retry

### ISSUE THREAD

**Issue by arvi3411301** [hasura/graphql-engine#1478]
Currently, none of the previous invocation response is sent in the request payload in case of retry.

If this is added in the request payload, it would be easier for the flow of the execution.

For example,

Let's say if we charge the user in stripe and update the charge information in the database. If the mutation fails, an error will be sent to the event trigger with the following information 

```json
{
  "code": "mutation-failed",
  "charge_id": "xxxxx"
}
```

When the event is re-tried and previous invocation response is present, we will know the charge_id from the previous invocation and we can either mutate to update the charge_id in the table or refund the charge (in case of max_retry is reached)

**Comment by tirumaraiselvan** [comment]
After discussing with @0x777, seems like this is not a good idea:

1) It might be better to manage errors yourself in a table or column instead of iterating through previous logs.
2) It feels like having more than one type of error in an event handler is an anti-pattern because:
    i) An event handler should ideally do ONLY one thing.
    ii) The ONE thing should fail fully or finish fully (atomic).
    iii) In case, the ONE thing fails fully then retry makes sense.
    iv) In case, the ONE thing finishes fully but retries (due to final mutation failure or re-delivery) then do step 3) 
3) In case a mutation fails after finishing everything, then first step should be to retry the mutation in the handler itself. On failure, relevant details can be stored via a different mutation and this state can be checked in the beginning of the handler to skip the logic.
