### ISSUE TITLE
run master's console tests for the previous version before release

### ISSUE THREAD

**Issue by wawhal** [hasura/graphql-engine#1524]
Using the assets of the latest build, we should run the console tests of the previous release with previous server/CLI.

This is to make sure that the UI is in a happy state for the previous versions as well.

Thoughts?
@praveenweb @karthikvt26 @shahidhk @coco98

**Comment by karthikvt26** [comment]
Couple of problems I could see are
1) For how many previous versions we are going to run the tests
2) When will we assert the fact that this build is fine to go live.

I think @0x777 idea makes sense where you make a release with a specific version so that latest console build will not have any impact on the previous versions.
