### ISSUE TITLE
Update metadata when making changes to the schema

### ISSUE THREAD

**Issue by danielcompton** [hasura/graphql-engine#1597]
Currently, when you make a change to a table through graphql-engine, if it would result in an invalid state of the schema, the change is not allowed. For example, when dropping a column that a role is allowed to select from, you get this error:

> Deleting column failed
> cannot drop due to the following dependent objects : permission auth_user.user.select

It would be helpful if Hasura warned about this scenario and offered to remove the select permission on that column before dropping the column. You can run into similar situations trying to drop tables.

This is similar to #231, but with a slightly different focus on in-console editing. Also relates to #408.

**Comment by mike-thompson-day8** [comment]
To put this another way, the console is currently very "correct" (about avoiding inconsistent metadata), but equally not very helpful.  

In its strictness, the console forces the user to perform manual, potentially error-prone work, which is not the best tradeoff.  So this is a feature request ... 

Could the console be improved to make it "smarter" when the user wants to:
1.  Rename Tables
2.  Rename columns 
3.  Remove columns

By "smarter" we mean can it automatically adjust metadata (like security rules) for each of the actions above, rather than stopping the user cold, and getting them to perform all the manual steps in adjusting metaadata.

**Comment by coco98** [comment]
@danielcompton @mike-thompson-day8 This is something we're actively working on. We're working out the right UX to help users go through iterations of their schema safely but without console being a PITA. :)

The good news is that renaming will land very soon! 
https://github.com/hasura/graphql-engine/pull/1542

And this will solve the 2 rename use-cases you mentioned and also work for renaming relationships

@0x777 @rakeshkky What about automatically adjusting metadata for the column drops also? Atleast for select permissions.

**Comment by 0x777** [comment]
Currently we have `cascade`, which can be set to `true`/`false`. If you are dropping a column and set `cascade` to `true`, all the dependent objects are dropped too. We should allow this in the console.

However if we want to `adjust` existing permissions (which is only possible in few cases) we'll need to introduce something like a `safe` option for `cascade`. I can't think of operations other than dropping columns where adjustment to the existing metadata is needed as renames are already in.

**Comment by rikinsk** [comment]
related to #1593

**Comment by beerose** [comment]
Solved in https://github.com/hasura/graphql-engine/pull/4846
