### ISSUE TITLE
Allow unauthorized role to access x-hasura- headers

### ISSUE THREAD

**Issue by mitchazj** [hasura/graphql-engine#1686]
This would allow the case where an anonymous user needs to be able to query a table for more information on a specific row, without having access to every row that they do not know about.

For example, if an anonymous user needs to access the primary key attached to their email address (perhaps to fetch other non-sensitive information connected in another table via key_relation to the primary key), they would pass their email address in the `x-hasura-user-id` header so that they can query-select their specific row without being able to query-select every row (including other users' emails) in the entire table.

**Comment by tirumaraiselvan** [comment]
This issue was brought up by another user recently who got confused byt this. Why can't the header be passed as something else instead of `x-hasura-`?

The problem is that it might be confusing to have `x-hasura-` headers coming from the client directly when the user is unauthenticated (as it is dropped when the user is authenticated). It might be perceived that the value is infact resolved by hasura.

**Comment by pnappa** [comment]
Hi, I was the user that reported this as an issue in the email to you, @tirumaraiselvan.

I strongly believe that this is indeed a dangerous behaviour to have by default in Hasura, due to the perceived authority of the `X-Hasura-` headers. When a valid JWT is provided, the `x-hasura-user-id` is populated with the user-id contained within the JWT. It is likely that a unwitting web-developer only tests this positive case, and thus relies on this behaviour to be consistent. This problem arises in remote schemas, when mutations/resolvers are added with custom logic.

The scenario you describe @mitchazj, is likely indicative of a wider flaw in your application. User emails are not private information, and as such, enumeration of secondary information can be iteratively retrieved. Of course, you can pick a different header too - it doesn't need to be prefixed with `X-Hasura-` to be useful (in the case of remote-schemas, say), just tick the box to forward headers.

Cheers,
Patrick
