### ISSUE TITLE
Relations in the mutations returning are not supported since alpha40

### ISSUE THREAD

**Issue by roman-y-korolev** [hasura/graphql-engine#1763]
Since version v1.0.0-alpha40 it is impossible to use relations inside mutation returning.
Example:
```
mutation {
  insert_smth_v1(objects: [{name: "foo", relate_id: 1}]) {
    returning {
      relateByrelateId {
        id
      }
    }
  }
}

```
Will return `"message": "field \"relateByrelateId\" not found in type: 'smth_v1_columns'"`
But it is still posible to use it inside of the query:
```
{
  smth_v1{
    relateByrelateId {
        id
      }
  }
}
```

**Comment by 0x777** [comment]
@roman-y-korolev From alpha40, relationships can only be retrieved in mutations if the table has a primary key (or a unique constraint). What we were doing prior to `alpha40` would only work in some cases and could trigger inconsistent results such as #1576. 

Is there a primary key/unique constranit on `insert_smth_v1`? If not, is it possible to define one?

**Comment by roman-y-korolev** [comment]
@0x777 We use views instead of tables. Tables have pk, but it is impossible to add pk to the view. Are there any solutions for that case?

**Comment by 0x777** [comment]
@roman-y-korolev Are you using updatable views? Maybe we can try to infer the constraints on an updatable view from the underlying base table? We'll look into this asap. And apologies for not including this as part of the release notes. We are sending out an announcement soon.

> Are there any solutions for that case?

You can downgrade to `alpha39` (till we figure out if this is fixable) as follows:
1. Stop graphql-engine alpha40
2. Run this sql
 
   ```sql
   drop table hdb_catalog.hdb_schema_update_event;
   drop function hdb_catalog.hdb_schema_update_event_notifier();
   update hdb_catalog.hdb_version set version = '10';
   ```
3. Start graphql-engine alpha39

Another alternative is to have mutations on the underlying tables directly. This may or may not be desirable

**Comment by roman-y-korolev** [comment]
> Are you using updatable views? 

Yes, we do.
>  We'll look into this asap.

Thank you!

**Comment by joshainglis** [comment]
Hi @0x777, love what you guys are doing with Hasura!

Further to the discussion above, I've put together a minimal example of the kind of pattern we are attempting to support.
https://github.com/joshainglis/hasura-pg-views-example

Essentially we are using postgres views as a way of providing a versioned interface in Hasura.

I'd be keen to hear your thoughts on this and if you think this will be supportable with Hasura moving forward.

**Comment by 0x777** [comment]
@joshainglis Let me explain the problem that we are facing: 

To fetch relationships as part of a mutation response, we need to uniquely identify the row that was modified by the mutation. Prior to `alpha40`, we were using Postgres's `CTE`s to reference the modified rows and it turned out to be incorrect in some odd cases. So we switched to an implementation which relies on unique constraints on a table. We cannot go wrong with this approach but it is also restrictive. 

Now, to support relationships on updatable views, we somehow need to figure out how to uniquely identify a modified row on this view. While there is some information available in `information_schema.view_table_usage` and `information_schema.table_column_usage`, it looks like it may not be possible to fetch this information in a general case. 

What we can do though is allow you to specify the unique columns when tracking a view. The console can probably have an advanced mode where when tracking a view can open up a modal to pick the unique columns?

By the way we are also adding `query_root` as part of the mutation selection set in the upcoming release or so, i.e, you can run any query as part of the mutation response. Would that in any way help your use case? 

We are open to any ideas on how to fix this behaviour in cases such as yours.

**Comment by joshainglis** [comment]
@0x777 Thanks for the detailed description!

I think it's completely reasonable to add that info when tracking a view: eg

```
- args:
    name: companies_v1
    schema: public
    type: view
    unique_columns:
      - id
      - name
  type: add_existing_table_or_view
```
