### ISSUE TITLE
server side caching

### ISSUE THREAD

**Issue by SunChero** [hasura/graphql-engine#1964]
this is more of a question / RFC or maybe enhancement request since its not specific to hasura but rather touches on graphql in general.

since every graphql request is basically a POST request, we loose the caching mechanism on the server side. this mean every graphql request will go throught the database no matter what.
i understand, graphql use caching on the client side, but still i can see imporvment in using old and prouved  technology.

so is it possible to have  graphql cache queries (not mutation /subscriptions) to something like memcache/redis ...

**Comment by switz** [comment]
My data is read-heavy, write-light. Would love to set a ttl cache on some queries. Curious if there are any plans to go forward with this.

**Comment by eads** [comment]
Same boat as @switz over here, my uses are ludicrously unbalanced towards reads -- a couple writes an hour that could probably be once a day, up to hundred of thousands of reads an hour. I've played around a bit with https://fastql.io but haven't used it in production yet. It seems ok, but underdeveloped so far.

However, the approach of using a CDN/CDN integration seems nice in terms of flexibility and fitting into existing architecture. That might be an argument in favor of #574 because it would make it very easy to use the CDN of your choice without having to use edge functions to manipulate the response (which is coincidentally what I think I may try next).

**Comment by Conorrr** [comment]
@eads This feature is coming and is currently in beta. See this part of the latest community call for more information: https://www.youtube.com/watch?v=nNhWUh4Woew&t=135s I think the feature wiill be a Pro only feature though

**Comment by rishi-div** [comment]
Query Response caching is available. See details here: 
https://hasura.io/docs/latest/queries/response-caching/
