### ISSUE TITLE
Guide on recommended hosting options for Hasura

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#2083]
Let's create a recommendation guide for where to host Hasura, also mentioning that switching between different providers is not hard, and link to the updated guides on migrations with perhaps a video showing 1 migration across cloud vendors.

For example:
1. Easiest & serverless: [Hasura Cloud](https://hasura.io/cloud/)
2. Price-sensitive: DigitalOcean
3. HA: AWS/GCP/Azure configurations (Gordon's post about the AWS setup)
4. Auto-scale: Heroku, Fargate, AppEngine
5. Best with zeit/netlify: AWS (and which right region)

Any other dimensions that might be relevant?

**Comment by cortopy** [comment]
I can't find a helm chart for hasura. I can see there's some small work on this area

https://github.com/hasura/gitkube/blob/master/docs/helm.md
https://blog.hasura.io/draft-vs-gitkube-vs-helm-vs-ksonnet-vs-metaparticle-vs-skaffold-f5aa9561f948/

It would be great to have a hasura chart in the [official repo](https://github.com/helm/charts) so that deploying kubernetes is easy

**Comment by praveenweb** [comment]
Closing this since we have [Hasura Cloud](https://hasura.io/docs/cloud/1.0/manual/getting-started/index.html) as the recommended hosting solution along with [Deployment Guides](https://hasura.io/docs/1.0/graphql/manual/guides/deployment/index.html) for other cloud providers on Docs.
