### ISSUE TITLE
can we support postgres 9.4

### ISSUE THREAD

**Issue by ecthiender** [hasura/graphql-engine#210]
Or document the limitations on Postgres 9.4

Right now following don't work with Postgres 9.4.

1. Upsert queries
2. Operator `_append`
3. Operator `_prepend`
4. Operator `_delete_key`
5. Operator `_delete_at_path`
6. Operator `_delete_at_path`

**Comment by coco98** [comment]
@ecthiender Can this be closed? Or is this open because we still don't have docs on this yet?

**Comment by 0x777** [comment]
This is open as we can be smart about the schema that we generate based on the Postgres version.

**Comment by erikhSSI** [comment]
I am trying to connect to a pre-exisiting remote postgres 9.4 database.  (I have had no trouble with this perviously on a 10.6 database)

Q1: Do I need to upgrade from postgres 9.4?  What version is recommended -- I didn't see reference to this in the docs?

Q2: Are my problems due to postgres 9.4 or something missing from the postgres-permissions steps for "hasurauser" in the docs here: https://hasura.io/docs/1.0/graphql/manual/deployment/postgres-permissions.html

Steps I took:
1. install/run HGE v1.1.1 using the docker-compose with https template (minus the local postgres) 
2. set up a hasurauser in postgres using the commands here: https://hasura.io/docs/1.0/graphql/manual/deployment/postgres-permissions.html#postgres-permissions
3. test the remote postgres connection string first with psql using hasurauser.  everything fine.
4. sudo docker-compose -d up  (worked fine but...)
5. sudo docker ps (shows HGE constantly restarting)
6. sudo docker logs [container] -- shows lots of SQL errors.  I will include the last one here:
[hasura-docker-log.txt](https://github.com/hasura/graphql-engine/files/4483722/hasura-docker-log.txt)

Thanks for the help!

**Comment by erikhSSI** [comment]
OK, so I think I have answered PART of my question -- no. postgres 9.4 is clearly not supported because the error log msg was complaining about `jsonb_build_object()` -- which doesn't seem to exist until 9.5:
`function jsonb_build_object(unknown, name, unknown, smallint, unknown, name, unknown, boolean, unknown, text) does not exist`

https://www.postgresql.org/docs/9.4/functions-json.html
https://www.postgresql.org/docs/9.5/functions-json.html

**Comment by praveenweb** [comment]
Closing this since we are not planning to support 9.4.

Hasura GraphQL Engine supports Postgres 9.5 and above.
Hasura Actions works on Postgres 10 and above.

[Docs on Supported Postgres Versions](https://hasura.io/docs/1.0/graphql/manual/deployment/postgres-requirements.html#supported-postgres-versions)
