### ISSUE TITLE
Recommended approaches to schema stitching with Hasura?

### ISSUE THREAD

**Issue by hrgui** [hasura/graphql-engine#2102]
## What I understand
- Hasura has the ability to do schema stitching from Hasura => another GraphQL server.
- Other graphql servers can do schema stitching, as described in the hasura blog (https://blog.hasura.io/the-ultimate-guide-to-schema-stitching-in-graphql-f30178ac0072/).

## Question
I have a scenario that calls for the following:
- Authenticate using firebase authentication
- Get additional user metadata from hasura graphql engine based on result of authentication, using the UID as a lookup.

Let's call this a mutation `login`.

With the schema stitching from hasura, it is unclear how this could be done - are there guidelines on how this mutation should be written? 

With (https://blog.hasura.io/the-ultimate-guide-to-schema-stitching-in-graphql-f30178ac0072/), it is unclear how JWT authentication should work, as none of the examples describe how to work with JWT authentication. Are there guidelines on how to make this approach work with hasura graphql engines that require JWT authentication?

**Comment by leoalves** [comment]
Hello @hrgui,

Do you want to add your own Graphql Server to the Hasura schema?
When you say "get addional metadata from Hasura". Do you mean get the Hasura ID for the authenticated user?

If you are using Firebase Authentication. You should add custom claims to your token.  You can do that after you create the user in the Firebase Authentication.  With Custom Claims, when Hasura decodes the JWT token it will be able to identify the user in Hasura.

You can use the information from the custom claim to add Access Control inside Hasura.
https://docs.hasura.io/1.0/graphql/manual/auth/index.html

And here is an explanation about JWT tokens custom claims with Hasura.
https://docs.hasura.io/1.0/graphql/manual/auth/jwt.html

For the Graphql stitiching, usually what I do is I create a Graphql server in a Google Cloud Function and add  the endpoint from that function as a remote schema to Hasura.

For the login, since the JWT token generation is done by Firebase Authentication, it doesn't make sense to call it from the server.  You should call it from the client with the Firebase Javascript Client Library (I am assuming you are doing a web app). And add the authentication token to to the Headers when requesting data from Hasura.

To create the user, it does make sense to have an Graphql endpoint handle that for you.  You would need to create the user in Firebase Auth, create the user in Hasura, and set the custom claims to identify the user in Hasura after the login.

**Comment by hrgui** [comment]
> When you say "get addional metadata from Hasura". Do you mean get the Hasura ID for the authenticated user?

Yes, a record of the user and its intended role and other data that can't be stored in Firebase Authentication. For example, if the user is supposed to be a `read_only` user, I have a record in Hasura that indicates that. 

I then use that to create the custom claim, which can't be done client-side, and nor do I want to have to use Firebase Realtime Database for it. So I then use `createCustomToken` and have the client sign in with `signInWithCustomToken`.

This eliminates the need for a cloud function + Firebase Realtime Database.

**Comment by leoalves** [comment]
@hrgui 

What you need to do is create a custom claim when you create the user.  This custom claim should hold the Hasura unique user identifier.  With that information you can set up permissions and get all data you need in Hasura. You shouldn't be creating a custom token every login.

You should do something like this when you create the user. 

```javascript
/// create the firebase user
const firebaseUser = await app.auth().createUser({
    email,
    password
  })
// create the user in Hasura
const hasuraUser = await client.request(addUser, {
    firebase_id: firebaseUser.uid,
    email,
    name,   
    organization_id: 'fa30f31d-d9bc-48b5-8f55-8cb6a8fe4ec7',
    role_id: 'fc4fd197-4b76-4a41-8412-817afb185781'
  })

// set custom claims in the token
 const claims = {
    'https://hasura.io/jwt/claims': {
      'x-hasura-allowed-roles': ['user'],
      'x-hasura-default-role': 'user',
      'x-hasura-firebase-id': firebaseUser.uid,
      'x-hasura-organization-id': hasuraData.insert_users.returning[0].organization_id,
      'x-hasura-user-id': hasuraData.insert_users.returning[0].id     
    }
  }
await app.auth().setCustomUserClaims(user.uid, claims)

```
In the client you just log the user in, directly calling Firebase Auth

```javascript
 await firebase.auth().signInWithEmailAndPassword(email, password)
```

And in all requests to Hasura you send the token in the Authorization Header.  And in the Hasura console you can make the Access Control configurations, using the token values set in the Custom Claims, like: x-hasura-user-id, and whatever values you used.

https://docs.hasura.io/1.0/graphql/manual/auth/basics.html


In that case you should only call the external mutation when creating the user, or when updating the info set in the custom claim.

**Comment by hrgui** [comment]
@leoalves - thanks for the suggestion, didn't think of that, it'll make the login process a lot simpler.

I think now I have some sort of idea on how this could be implemented, also saw your https://github.com/leoalves/hasura-firebase-auth repo and it gave me some idea of how to continue, so I am closing this issue.
