### ISSUE TITLE
Can't add relationship to existing entity on insert

### ISSUE THREAD

**Issue by VividDigital** [hasura/graphql-engine#2114]
I've broken this down to the simplest use case and can't help but think I must be missing something. All I want to do is create a new parent object and link it to an existing child object. Here is a basic payload:

`{
  "objects":
  [
    {
      "title":"New Title",
      "authors":
      [
        {
          "data":{"id":1}
        }
      ]
    }
  ]
}`

Both the parent and the child have auto increment ids. I get the following response:

`{
  "errors": [
    {
      "extensions": {
        "path": "$.selectionSet.insert_posts.args.objects[0].authors.data[0]",
        "code": "validation-failed"
      },
      "message": "cannot insert \"id\" columns as their values are already being determined by parent insert"
    }
  `

This is basically verbatim of what is in the docs aside from not providing an id for the parent object. I've also tried it with on_conflict on the child primary_key and id column. Same result.

What am I missing?

Also, what I really want is something like described in #1573. I want to be able to pass child objects as:

`[ { id:1 }, {title: 'New Author'} ]`

and have the first item be linked to the parent, and the second be created then linked. This seems like desirable and normal behavior. For now if I can get this main issue resolved at least I can add the new author entities first and then link all the ids to the new parent object.

The only other thing I can think of is to add the parent first, then update it with the child relationships. I haven't tried that so I don't even know if that will work, but it seems convoluted.

**Comment by coco98** [comment]
@VividDigital 

Try this heroku app: https://test-nested-inserts.herokuapp.com/console/api-explorer

with this query that reads:

Insert an article called article3, that is written by author with id 1 and also a new "author4". In case, an author already exists, they might already have an article assigned so update the article_id column (with the new for this article) but ignore anything else.

```graphql
mutation {
  insert_articles(objects:[
    {
    	title: "article3"
      authors: {
        data: [
          {id:1, name:"doesn't matter because won't update"},
          {name:"author4"}
        ]
        on_conflict:{
          constraint: authors_pkey
          update_columns:article_id
        }
      }
    }]
  ) {
    affected_rows
    returning {
      id
      title
      authors {
        id
        article_id
        name
      }
    }
  }
}```


--------------------------------------------------------------
**Nested object relationship**

I know that you're talking about a nested relationship that is an array relationship. But just in case, if you had a nested object relationship, a connection to the child object would be via the column value anyway.

For example:
If you have a relationship (or a nested child) you must have columns that specify the nested relationship. This means that your insert would be inserting the exact value instead of the nested child.
`{ "objects": [ { "title":"New Title", "author_id": "id":1} ] }`

------------------------------

Feel free to play around with the heroku app I linked you to, to suggest queries/use-cases etc.

**Comment by VividDigital** [comment]
Appreciate the help. Although it's not what I was looking for, it caused me to double check something.

The issue seems to be that I did not manually create the relationship tables. I was under the impression making the relationship where needed would generate the backing tables for me. I didn't know I had to go and manually do it as well for the many to many.

Thanks
