### ISSUE TITLE
read JWT from cookie header

### ISSUE THREAD

**Issue by lishine** [hasura/graphql-engine#2183]
When Hasura decoding the JWT token (instead of passing it to webhook), Can Hasura read JWT token from secure-http-only-cookie ? If so then what should be the name of the cookie?

**Comment by 0x777** [comment]
@lishine Currently the JWT is expected as a bearer token in the `Authorization` header. Maybe this can be a setting, `--jwt-from-cookie <cookie_name>`?

**Comment by lishine** [comment]
It would be very nice! Otherwise hook a must with cookies.

**Comment by campie** [comment]
Hi,

It would be great to have **--jwt-from-cookie <cookie_name>**.

This would solve the problem of safely storing the jwt in the client by using a secure http-only same-site cookie (more on this below). IMHO, we should **NEVER STORE the JWT in LocalStorage** or anything else js has access to. For web apps, using http-only cookie is currently the only solution to this problem (that I'm aware of).

However, there should be some **protection against csrf attacks** for old browsers that do not support same-site flag on cookies.

Something like **--jwt-csrf-token <csrf_token_name_inside_jwt_payload_and_in_http_headers>** could do the job.

I really would like to help design this solution.


**Example Scenario**

![Hasura-Cookie](https://user-images.githubusercontent.com/49657981/57795603-c6d2bc80-771c-11e9-81e1-1dc84c4d70c7.jpg)


**Cookie containing the jwt**

The jwt is stored in a secure http-only same-site cookie. The max-age cookie flag can be used to keep the cookie in the client browser for a specific time. 

**1 - Secure cookie** 

This flag makes sure the cookie is only sent to the server through https.

**2 - Http-only cookie**

With the http-only flag is set to true, JS **never** has access to the token. 

In case of a xss attack, the jwt can't be stolen and the attacker has to do his evil job inside www.app.foo. It mitigates a lot the trouble a xss attack could cause.
 
**3 - Same-site cookie** 

The same-site flag has two options: strict or lax. 

If the flag is omitted (or set to none in the future), the cookies are sent with **every request**

Sending cookies with every request was the only option before the same-site flag was introduced.

This flag distinguishes same-site requests from cross-site requests, **NOT** cross-origin requests.

**Attention: a cross-site request is different from a cross-origin request**. (Please, correct if I'm wrong)

www.app.foo and api.app.foo are different origins but same sites (both have app.foo as their [public suffix](https://publicsuffix.org/)). So in the example above, the spa is loaded from a cdn at www.app.foo and then requests the hasura api at api.app.foo: these are all same-site requests and at the same time all cross-site requests.

If the same-site flag is set to strict, the cookies are **never** sent with any cross-site request, only same-site requests. This is the "strictest/safest" mode and it works in the example above.

In lax mode, cookies are sent for all same-site requests (just like in strict mode) plus cross-site requests if it's a GET request and the URL in the address bar changes because of the request. Cross-site requests from iframes, images or XMLHttpRequests never send same-site=lax cookies, but if a user clicks in a link from a different site and then goes to your site, lax mode will send cookies. 


**Cookie containing the payload**

This is a secure same-site domain set cookie and is optional.

The domain flag has to be set to app.foo by the api so that www.app.foo can read the cookie. If domain is not set, only api.app.foo can read the cookie (but the app is served at www.app.foo).

This cookie improves the UX because, at start-up, if the payload cookie is present, the user is logged-in (client js cannot read the http-only jwt cookie to check this). Besides, the payload contains user info to update the UI accordingly. If an evil force changes the payload content, all we get is a broken UI. 

An alternative to this cookie could be an api call at start-up to check login status, but this adds overhead to the process.


**Payload duplication**

My app is a little bit different from the example above. The http-only jwt cookie only contains the jwt header and signature. The payload cookie is exactly the same. Server side, my hasura auth webhook gets the csrf-token from the csrf-token header, reassemble the jwt from this two cookies, verifies the jwt and then check if the payload csrf-token is the same as the headers csrf-token.

**Set-Cookie Headers from remote schema**

I'm still struggling with this issue #1654

**Comment by verekia** [comment]
For the folks stuck on this, I wanted to share my (hopefully temporary) workaround: https://github.com/verekia/my-stack/blob/master/docs/src/pages/api/graphql-client-endpoint.tsx.md#readme

I have a serverless function that acts as a bridge between the browser and Hasura. It transforms browser requests that contain the JWT in a cookie into a server-to-server call that uses the `Authorization` header to pass the JWT to Hasura. It's obviously quite a heavy, slow, and potentially unsecured workaround, but it works.

Looks like we'll still have to wait at least several months for a fix (until they release 1.4.0, and prioritize this issue), so maybe it can help a few of you folks in the meantime.

**Comment by afefer** [comment]
@verekia - I was using a similar solution with a serverless function acting as a bridge, but then realized that GraphQL subscriptions won't work because Hasura relies on websockets which the bridge function can't pass through. 

A better workaround is to create a serverless function to act as a Hasura auth webhook. Hasura will pass along the request headers to the webhook (including the cookies), and inside that function you can validate the JWT, extract the x-hasura-* session variables from the JWT claims, and send that back to Hasura.

**Comment by khan297** [comment]
B

**Comment by verekia** [comment]
@afefer Good point, that can't work for subscriptions. Thanks for pointing that out. My goal of using JWT in the first place was to avoid the auth webhook because it has to be run for every single request, which slows down the entire backend compared to JWT. My app is built on Next.js so I have both server-side rendering and client-side calls to Hasura. SSR calls can use the JWT in the cookie, so the bridge was actually only for client-side calls, so it's only used for a portion of requests. Not too bad – but yeah, that only works if you don't need subscriptions indeed.

**Comment by xorander00** [comment]
@verekia I was literally just reading through this issue since I'm facing the same question in my use-case.  I also happen to be using Next.js too lol.  I used Hasura before until 1.3.3 and would like to resume using it, but for now I've fully implemented the GraphQL server & client in Next.js.  I very much miss being able to do it with Hasura.
  
Anyway, my $0.02 as follows:  
  
- Up until a month ago, I was using `Authorization: Bearer ...` but finally got around to switching to httpOnly cookies.  
- I'd really prefer not to have to revert to using the Authorization header again with Hasura, which would defeat the purpose.
- The point about subscriptions is well taken.  I actually changed my subscriptions approach, but it would be nice to be able to have Hasura as an option for that, in which case the cookie/context issue would need to be resolved.  
- Personally, I think a prioritized sequence of token sources would be nice, say something like HASURA_AUTHN_TOKEN_SRCS='cookie:accessToken,authorization,bodyJsonPath:session.token' which would mean "Try to read the cookie with key accessToken, and if that's missing, then try the authorization header, and if that's missing, then check the body to see if { session: { token: '' } } exists, and if not, then fail (or try a webhook or whatever)."  
  
It's a bit complicated & I'm sure has problems I'm not seeing, but that's my at-a-glance thought.

**Comment by verekia** [comment]
It seems like this is now supported?

https://hasura.io/docs/latest/graphql/core/auth/authentication/jwt.html#header

> header
> This is an optional field, which indicates which request header to read the JWT from. This field is an object.
> Following are the possible values:
> {"type": "Authorization"}
> {"type": "Cookie", "name": "cookie_name" }
> Default is {"type": "Authorization"}.
>
> In the default mode, Hasura expects an Authorization header with a Bearer token.
>
> In the cookie mode, Hasura will try to parse the cookie header with the given cookie name. The value of the cookie should be the exact JWT.
>
> Example:-
>
> If header is {"type": "Authorization"} then JWT header should look like:
>
> Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWI...
If header is {"type": "Cookie", "name": "cookie_name" } then JWT header should look like:
>
> Cookie: cookie_name=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWI...

I haven't tried myself, but if it works, this issue should be closed :)

And this PR too: https://github.com/hasura/graphql-engine/pull/2327

**Comment by xorander00** [comment]
@verekia Yup, saw that in the docs a couple of weeks ago.  It's on my calendar to try out next week. This issue can be closed and I'll comment on it again if I run into any problems this weekend.  Thanks! :)

**Comment by sfcgeorge** [comment]
It does work but you may run into an issue with default unauthorised role if you want to use that https://github.com/hasura/graphql-engine/issues/7272#issue-949510472

**Comment by manasag** [comment]
Closing this as resolved (feature is now supported). Please feel free to reopen if the issue is still relevant for you.
