### ISSUE TITLE
managing seed or data-only migrations

### ISSUE THREAD

**Issue by rikinsk-zz** [hasura/graphql-engine#2431]
Often one would like to add some data into tables as part of the db init process. We should document how to achieve that.

- head to run SQL
- add the insert sql statement
- hit ~track this~ This is a migration
- Run will insert data and create a migration file

**Edit**: 
The above task is done. There are further suggestions for managing seed data migrations in the comments. Leaving this issue open for that discussion

**Comment by jjangga0214** [comment]
@marionschleifer Initializing seed data is what I need right now. Could I ask
- when this task would be completed
- how to make it work before waiting docs to be published

**Comment by marionschleifer** [comment]
@jjangga0214 
1. This task will be completed within the next few weeks, until mid September.
2. Yes, you can do as described in the issue description: You can add the SQL (with insert statements) as a migration.
Let me know if you have any further questions 🙂

**Comment by jjangga0214** [comment]
@marionschleifer Thank you for the prompt response :)

>You can add the SQL (with insert statements) as a migration.

If I understand what you mentioned clear, then migrations would look like this, where `1565610380000_seed.up.sql` contains all `INSERT` statements. The version `1565610380000` of `1565610380000_seed.up.sql` is just arbirarily choson number as the file is not generated by hasura, but by me.
 
```
hasura
├── config.yaml
└── migrations
    ├── 1565510062048_init.up.sql
    ├── 1565510062048_init.up.yaml
    ├── 1565610349244_alter_table_public_author_add_column_test.down.yaml
    ├── 1565610349244_alter_table_public_author_add_column_test.up.yaml
    ├── 1565610379357_alter_table_public_author_alter_column_test.down.yaml
    ├── 1565610379357_alter_table_public_author_alter_column_test.up.yaml
    └── 1565610380000_seed.up.sql
```
The reason I want seed data is easily populate data on local development environment. So seed data must be prevented to be fed to production database in our case. But satisfying this with migration model introduces, at least to my project, an inconvenient workflow. 

Let's say I add a new migration named `new_migration_example` with vesion `1565610380001` like this.

```
hasura
├── config.yaml
... (previous versions are omiited)
    ├── 1565610380000_seed.up.sql
    ├── 1565610380001_new_migration_example.up.yaml
    └── 1565610380001_new_migration_example.down.yaml
```

While I want to just simply execute `hasura migrate apply` as like before adding seed, now I have to run `hasura migrate apply --version 1565610380001`. What if I have many versions to be applied? Then every version would need to be specified like `hasura migrate apply --version 1565610380001 --version 1565610380120 --version ...` (I haven't tested specifying multiple vesions on one command works. If not, then mulitple commands would be required.), rather than a simple command `hasura migrate apply`. This is cumbersome and error-prone as well.

In my opinion, "seed" should be an independent concept from migration. That's because migration can be applied to both dev and production environment, whereas seed, at lease my case, should only be applied to dev environment. For example, prisma provides [`prisma seed`](https://www.prisma.io/docs/prisma-cli-and-configuration/cli-command-reference/prisma-seed-xcv8/) command, independent from [`prisma deploy`](https://www.prisma.io/docs/prisma-cli-and-configuration/cli-command-reference/prisma-deploy-xcv9/), which is simmilar to hasura migration.

**Comment by coco98** [comment]
@rikinsk @shahidhk Based on @jjangga0214 comments, do you think we can solve this by allowing a user to run an arbitrary migration/SQL _without_ running it as a migration which updates the migration state on the database?

```
$ hasura migrate apply --one-off /path/to/folder

$ hasura migrate apply --one-off /path/to/file.sql
```

This will make it easy to run a seed data style migration, and we don't need to explicitly code in a seed directory into the CLI command flow?

**Comment by rikinsk** [comment]
Why isn't executing an insert SQL after the migrations are run good enough? Any reason for this to be a migration if its not to migrate from one system to another

**Comment by mnlbox** [comment]
Any news?

**Comment by shahidhk** [comment]
For the CLI migrations image, we can provide another environment variable `HASURA_GRAPHQL_MIGRATIONS_SEED_DIR` where the user can keep all the seed data as Migrations. 

Then use can keep one directory for schema/metadata migrations and another for see data.

**Comment by jjangga0214** [comment]
I'd like to suggest an additional proposal for seed data format.

I've seen folks have some different approaches for seeding. 
For instance, some prefer SQL, others, GraphQL Mutation.
What's more, some people have JSON as their raw seed data, so they want use it as-is.

**JSON**

![Screenshot from 2019-12-16 20-25-08](https://user-images.githubusercontent.com/28584151/70904652-3f984f00-2045-11ea-8b85-6bdc2389e1c6.png)
![Screenshot from 2019-12-16 20-27-32](https://user-images.githubusercontent.com/28584151/70904659-445d0300-2045-11ea-8a82-f0b69eb62689.png)
![Screenshot from 2019-12-16 20-30-25](https://user-images.githubusercontent.com/28584151/70904725-6ce4fd00-2045-11ea-8ed3-25b5bf59b37a.png)

**SQL**

![Screenshot from 2019-12-16 20-29-35](https://user-images.githubusercontent.com/28584151/70904679-4f179800-2045-11ea-8072-7adf862c26b9.png)
 
**GraphQL mutation**

![Screenshot from 2019-12-16 20-31-05](https://user-images.githubusercontent.com/28584151/70904813-b1709880-2045-11ea-88b0-d8984c5f5bbb.png)

(This guy actually thinks json would be good as well, though)
![Screenshot from 2019-12-16 20-30-56](https://user-images.githubusercontent.com/28584151/70904762-8be38f00-2045-11ea-9171-0f3845956c65.png)

I believe these comments are just a tip of real(or potential) needs for seed, with various approaches (at least under these 3 categories). 

Thus, I think all of these 3 forms, JSON, SQL, GraphQL Mutation, are good to be used as data format for automatic seed.

**Comment by jjangga0214** [comment]
I'd like to suggest an additional proposal for seed data management.

```bash
hasura seed apply
```
The `apply` command reads seed data, and insert it to Postgres. 
This would be convenient when editing seed data frequently, and don't want to reboot or directly handle Hasura and Postgres.
If Postgres already has some data, an user can choose (e.g. by flag) between
1. Delete existing data, and then insert the seed.
2. Just insert the seed regardless of the existing data. Override existing data by seed if unique key is overlapped. 



```bash
hasura seed pull # or `hasura seed create` for consistency with `hasura migrate`?  
```
This commands reads existing data from Postgres, and generate seed data format, possibly one of SQL, JSON, GraphQL. It should probably write the seed data on filesystem, or stdout for pipelint.

**Comment by marionschleifer** [comment]
@jjangga0214 thank you for your idea. Currently, this is not something that we are planning to do. However, any community contribution on this are welcome 🙂

**Comment by GavinRay97** [comment]
I also am in the process of trying to come up with a solution for this at the moment.
Manually writing SQL statement seeds is technically an answer, sure, but that is going to cost our team a lot of time. Ideally, Hasura should provide utilities to track and insert records along with schema definitions.

**I think the optimum solution here is to use the `pg_dump` API (which I had no clue existed in Hasura until I went digging for answers in the repo code).**

My initial thought was to implement calling the `pg_dump` binary externally as part of the migration process, but I can see now that this has already been implemented :sweat_smile: 

**Have a look at this:**

![image](https://user-images.githubusercontent.com/26604994/71376614-12d9bf80-2590-11ea-82f7-88bc97d44638.png)

I figure the way it would work is that either through CLI flags or the Console, users can select whether they want to track just the schema, or the data plus the schema in migrations. 

This may be a bit of an undertaking, because it is going to require (I assume):

- Integration into the Haskell engine core and test suite
- Integration into the Web console
- Integration into the Go CLI

**A short-term solution would be to modify the Go CLI to accept a flag for whether or not it should dump the data as well:**

Modify `migrate_create.go` and `schema_dump.go` to take a `--include-data` (or similarly-termed) flag. Modify `ExportSchemaDump` argument string to dynamically generate the array of flags based on whether or not `--include-data` was passed.

https://github.com/hasura/graphql-engine/blob/master/cli/commands/migrate_create.go
https://github.com/hasura/graphql-engine/blob/f8ffbda11897983adffd5a5d00f077da92f618ba/cli/commands/migrate_create.go#L29
https://github.com/hasura/graphql-engine/blob/f8ffbda11897983adffd5a5d00f077da92f618ba/cli/commands/migrate_create.go#L85-L98

https://github.com/hasura/graphql-engine/blob/f8ffbda11897983adffd5a5d00f077da92f618ba/cli/migrate/database/hasuradb/schema_dump.go#L8-L18


I am not sure who best to tag about this. @marionschleifer @coco98

**Comment by GavinRay97** [comment]
I do not have any experience writing Go, but here is what I imagine the function would roughly look like (barring the fact that if we are going to pass config here, it should be in an object (I suppose Go calls them interfaces)):

```go
 func (h *HasuraDB) ExportSchemaDump(schemaNames []string, includeData bool) ([]byte, error) { 
	 opts := []string{"-O", "-x"}

	 if includeData {
		 opts = append(opts, "--inserts")
	 } else {
		opts = append(opts, "--schema-only")
	 }

	 // Probably want to add in a []string for tableNames here as well
	 // Then the implementation would look like:
	 if tableNames {
		opts = append(opts, "-t")
		for _, table := range tableNames {
			opts = append(opts, table)
		}
	 }

 	for _, s := range schemaNames { 
 		opts = append(opts, "--schema", s) 
	 }
	 
 	query := SchemaDump{ 
 		Opts:        opts, 
 		CleanOutput: true, 
 	} 
	resp, body, err := h.sendSchemaDumpQuery(query) 
}```

**Comment by marionschleifer** [comment]
@shahidhk could you please help @GavinRay97 to get started on this? ✨

**Comment by GavinRay97** [comment]
@lexi-lambda This has cross-cutting concerns with https://github.com/hasura/graphql-engine/issues/2817 and would potentially take care of that too

**Comment by joshuarobs** [comment]
I wrote a bash script that helps with the process of migrating from a Docker Hasura instance to somewhere else (e.g. on Heroku for production). Originally posted here: https://github.com/hasura/graphql-engine/issues/2817#issuecomment-569417930 (Look there for more info)

````
docker exec docker_container_name pg_dump -U postgres -d postgres --column-inserts --data-only $(docker exec docker_container_name psql -q -A -t -U postgres -c "SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' ORDER BY table_schema, table_name" | sed -e 's/^/-t /' | sed 's/$/ /' | tail -n +2 | tr -d '\n') | sed -n -e '/^INSERT INTO public/p' >> dump.sql
````


> Usage: Replace docker_container_name with the name of the actual Postgres container in docker. (Run docker_ps and look for the one with the Image of postgres). Then run the command. After that, you'll get a dump file containing all the data in your public table. You can then do what @Inch4Tk suggested, copy and paste these INSERT statements at the end of the init.sql file.

I'm not 100% sure if this will help in this situation while we don't have anything official for seeding data.

**Comment by GavinRay97** [comment]
@joshuarobs 

I added functionality for seed scripts into the CLI, but have some minor details to work out. Have not heard back from the Hasura team on this so it may be the case they are either on holiday or not interested in supporting it.

![image](https://user-images.githubusercontent.com/26604994/71548086-28c3f780-2977-11ea-9f94-fddb84d82630.png)

![image](https://user-images.githubusercontent.com/26604994/71548089-337e8c80-2977-11ea-9cb7-398ec8fe02a9.png)

![image](https://user-images.githubusercontent.com/26604994/71548090-38434080-2977-11ea-8d38-2fdd2b1b83c2.png)

**Comment by Manubi** [comment]
I would actually love an option where I can update the seed data in the hasura console tab. Adjust the row and have the opportunity after I've updated a couple of rows to save them as a migration. So instead of writing for every small change a new SQL statement I would prefer to take a database snapshot from time to time. 

Any ideas?

**Comment by Jokero** [comment]
What do you guys use now to auto-apply seeds for local development? It would be nice to just run `docker compose up` and this is it
