### ISSUE TITLE
docker hasura/graphql-engine behind ELB - some endpoints not working

### ISSUE THREAD

**Issue by mmccormack-scwx** [hasura/graphql-engine#2443]
Seeing the message "Hasura console is not able to reach your Hasura GraphQL engine instance"

Trialing an instance behind AWS ELB with auth0. Most endpoints are fine, but I notice
```
/v1/version
/v1/query
```
are not making it past the ELB because they don't have the auth headers. Crucially, they are missing the `AWSELBAuthSessionCookie` header (among others), and so are getting a 302 back to auth0.

The endpoints:
```
/console
/v1/graphql
```
are fine.

Any thoughts on why `version` and `query` are not honoring the session?

**Comment by shahidhk** [comment]
@mmccormack-scwx Have you configured ELB to redirect to Auth0 is the session cookie is missing?

**Comment by mmccormack-scwx** [comment]
Right, ELB redirects to Auth0 for auth. After this hasura is served from behind nginx. 

Logging on nginx indicates that the endpoints `/v1/version` and `/v1/query` never make it past the ELB.

Most of the page loads fine, but requests to those two endpoints do not function. 

GET /console
POST /v1/graphql
are fine as they honor the session and contain the cookie.

/v1/version
/v1/query
Hit the ELB, and get a 302 to Auth0, but do not seem to be following it for eventual Auth.

![image](https://user-images.githubusercontent.com/39194956/60647468-2463c980-9e81-11e9-9bd9-89acb6315f59.png)


Redacted headers for successful `POST` to `/v1/graphql`:
```
Host: domain.com
User-Agent: Mozilla/5.0  Gecko/20100101 Firefox/67.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://domain.com/console
content-type: application/json
Origin: https://domain.com
Content-Length: 1728
Connection: keep-alive
Cookie: AWSELBAuthSessionCookie-0=XXXX
Pragma: no-cache
Cache-Control: no-cache```

Headers for unsuccessful (302) `POST` to `/v1/version` or `/v1/query`
```
Host: domain
User-Agent: Mozilla/5.0  Gecko/20100101 Firefox/67.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://domain.com/console
content-type: application/json
Origin: https://domain.com
Content-Length: 158
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
```

**Comment by shahidhk** [comment]
Okay, I think I understand what is happening. Are you checking the `Authorization` header and redirecting to Auth0 based on its presence?

Hasura implements a few different kinds of Access control on its APIs (see https://docs.hasura.io/1.0/graphql/manual/api-reference/index.html)

With the following configuration changes at ELB, everything should work fine:

- `v1/version` is an open, public endpoint; you should not enforce any authorization on this endpoint at the ELB layer
- `v1/query` is an admin endpoint; console send `x-hasura-admin-secret` as authz for this endpoint, not `Authorization`; so allow access to this endpoint if admin secret header is present; allow access otherwise also, Hasura will reject if it doesn't see the right admin secret.
- `console` is an open, public endpoint; allow access irrespective of what headers are set, like the version endpoint
- `/v1/graphql` is the GraphQL API for which auth is handled with the Auth0 token in `Authorization` header; redirect to Auth0 for this endpoint.

Let me know if you have any questions.

**Comment by marionschleifer** [comment]
@mmccormack-scwx Is your problem resolved or do you continue to experience issues?

**Comment by marionschleifer** [comment]
I'm closing this issue. @mmccormack-scwx if you would like to add anything, feel free to re-open 🙂
