### ISSUE TITLE
loading placeholder for graphiql on console

### ISSUE THREAD

**Issue by wawhal** [hasura/graphql-engine#2485]
For large schemas like onegraph, when it takes a long time to introspect, graphiql says "No schema available".

We should have a placeholder skeleton or a loading spinner that indicates that introspection is in progress.

**Comment by tafelito** [comment]
My console is showing No schema available after I added a function. It doesn't seem to be loading anything. And the schema is not that big. How can I tell if is there anything loading or there was any error loading it?

**Comment by rikinsk** [comment]
@tafelito That is unusual. Could you share some more info about the function you added. Ideally exact steps to reproduce the issue might be of great help.

Also considering your issue is kind of unrelated to this particular issue, could you raise a new one where we can discuss & investigate this further?

**Comment by tafelito** [comment]
@rikinsk the issue is the same as #3232

**Comment by NitiKothari** [comment]
I have same issue

I am able to run query, but schema is not showing. Previously it was working fine

![image](https://user-images.githubusercontent.com/55777183/116712742-cb6c0a80-a9f1-11eb-85f7-890e5eb87096.png)
