### ISSUE TITLE
Release schedule or docs on how to build?

### ISSUE THREAD

**Issue by waynebloss** [hasura/graphql-engine#2502]
Just wondering if you have a regular release schedule? If so, what is it?

I don't want to create another issue for my next question, so here it is: Are there any docs on how to build the projects so that I can run unreleased commits? (I'm anxiously waiting for my issue fixes.)

Thanks for a great product!

**Comment by waynebloss** [comment]
I guess just read and use the various `Makefile`s eh?

**Comment by lexi-lambda** [comment]
We try to release at regular intervals (ideally a few times a month or more), but we don’t have any particular schedule we adhere to. There’s been more of a delay between releases than usual lately, but here’s some good news from @shahidhk yesterday on Discord:

> [The delay is] because of changes in the release process and some big features being worked upon. Good news - we're on track to make a release this week.

Still, if that isn’t quick enough, you can also try development versions of Hasura: Docker images get automatically built and pushed for each opened pull request, so if there’s a particular PR with a feature or bugfix you’re interested in, you can find the comment from @hasura-bot and use the Docker image tag mentioned there. For example, if you wanted to try the bugfix from #2492, you could use the `hasura/graphql-engine:pull2492-279facb9` image mentioned in [the last comment in the thread](https://github.com/hasura/graphql-engine/pull/2492#issuecomment-509752756).

However, be careful: I’m not sure I’d recommend using those images in production. Not because I expect them to be buggy, but because the PR images are built without optimizations enabled (so they build faster), so performance might be significantly worse. They’re fine if you just want to test something out or have a pre-release version to develop against, though.

**Comment by mnlbox** [comment]
+1 for release schedule.

**Comment by waynebloss** [comment]
Thanks!
