### ISSUE TITLE
cannot import metadata

### ISSUE THREAD

**Issue by kkshyu** [hasura/graphql-engine#2503]
i'm going to migrate my hasura metadata to another hasura server
and i got the error message: 
```
table exists in cache : "hdb_catalog.hdb_allowlist"
```
i've migrated my postgres schema and tried the `reset metadata` already.
i don't know what the cache is.

Here is the metadata i would like to import: 
[my-metadata.json.zip](https://github.com/hasura/graphql-engine/files/3379521/my-metadata.json.zip)

**Comment by ecthiender** [comment]
Hello @kkshyu 

In the metadata.json file, search for `hdb_allowlist` and remove the entire corresponding to that table and then you should be able to import it.

Or update the older hasura server to `alpha45` and then take the metadata dump again.

This is because of a bug in version < `alpha45` where the `hdb_allowlist` table was dumped as part of the metadata (its an internal table). I'm guessing the hasura server you dumped the metadata from is < `alpha45` and the new server where you're importing is > `alpha45`?

**Comment by kkshyu** [comment]
hi @ecthiender 
thanks for your quick reply, it works for the issue!
both of the import and the export are in v1.0.0-beta1
do i have to upgrade to v1.0.0-beta2?

**Comment by ecthiender** [comment]
@kkshyu metadata exported from `v1.0.0-beta.1` should not have the `hdb_allowlist` table in the dump. Can you confirm this?

You can upgrade to the latest version.

**Comment by kkshyu** [comment]
i think that is because i used `alpha45` before and upgraded the same instance to `v1-beta`
i have created a new instance with `v1-beta` directly and there was no `hdb_allowlist`
thanks for your help! @ecthiender
