### ISSUE TITLE
SQL functions in row select permission

### ISSUE THREAD

**Issue by lukaspili** [hasura/graphql-engine#2575]
Is it possible to define SQL functions in row select permissions?
Something like this does not seem to work currently:

```
{"_and":[{"date":{"_gte":"current_date - 1"}},{"date":{"_lte":"current_date + 1"}}]}
```

Date is a column of type `Date`.
I would like to restrict the SELECT permission, to only allow rows having date between yesterday and tomorrow. Thanks.

**Comment by marionschleifer** [comment]
@lukaspili You are right, currently this is not possible to do. We'll leave the issue here for discussion and we'll see how many reaction it generates 🙂

**Comment by lukaspili** [comment]
Sure, thanks. In the meantime I was able to solve my requirement using views.

**Comment by gabriel-sevecek** [comment]
I have use case when I need to the some checking on other tables based on user supplied data in a given mutation. I guess a SQL function would solve that so +1.

**Comment by aaronhayes** [comment]
This would be a fantastic feature, and have had similar requirements myself. Created and closed #2944 as a duplicate.

**Comment by mike360** [comment]
+1 for this feature. Use case for me is limiting the number of possible rows inserted for a user based on a value in another table (e.g. limited number of records for given subscription tier).

**Comment by ItsWendell** [comment]
I stumbled upon requiring something similar, quickly jumped to table views like @lukaspili recommended, they are often a good option!

**Comment by s-kris** [comment]
@mike360 Exactly.

**Comment by mvilrokx** [comment]
The view solution does not work for permissions on Inserts/Updates/Deletes. For example, I want to prevent Inserts/Updates/Deletes when the parent of the record that the uses is trying to mutate has a `start_date` in the past.

**Comment by mikejcooper** [comment]
+1 for this feature!

**Comment by raphaeltm** [comment]
Just wondering if this has gained any more traction internally? We would find it very useful.

**Comment by rossng** [comment]
I'd be interested in having this functionality for implementing a Zanzibar-style authorization model. Hasura's permission syntax is currently limited by its inability (as far as I can tell) to traverse relations recursively.

References:

* [Implementation of Zanzibar ACL language in PL/pgSQL](https://github.com/josephglanville/zanzibar-pg/blob/master/zanzibar.sql)
* [What is Zanzibar?](https://authzed.com/blog/what-is-zanzibar/)
* [Google Zanzibar paper](https://research.google/pubs/pub48190/)

**Comment by Kaelten** [comment]
I'd like to use this to allow for filtering out unpublished content but content that is scheduled to be published.

**Comment by m-revetria** [comment]
I have a similar use case: only rows with a date greater than `current_time` should be returned. Is possible to define a default filter? I think in my case being able to define a default filter applied to every query could be a solution. Is that possible?

**Comment by osdiab** [comment]
@rossng Aside, I would also be curious about the Zanzibar stuff you're looking into (and that Authzed product looks pretty cool too, though I have no insight into how it could possibly hook into Hasura's permissions model).

**Comment by osdiab** [comment]
Makes sense - yeah we’ve also spent an inordinate amount of time making our permissions system work with Hasura’s model. On the plus side the comprehensive filtering of data is really nice (like row level security), but if your permissions system isn’t RBAC with fixed roles across the entire application, it doesn’t work very elegantly—in our case, a multi tenant app where individual tenants and teams can define their own set of roles. 

On my next project I’m also exploring alternatives to Hasura largely because of this that might be better for enterprise/complex use cases - maybe just using postgres RLS with something like Graphile and a hand rolled Zanzibar-inspired schema/functions directly in Postgres would do the trick (don’t need the scalability of the actual distributed system), and let us have our cake and eat it too.

**Comment by rlee1990** [comment]
has there been any update from anyone at Hasura this is a major drawback

**Comment by inazurov-aiops** [comment]
+1

**Comment by nikhilshinday** [comment]
this would be really nice!

**Comment by SamirTalwar** [comment]
Hey folks. As a little sneak preview: [Native Queries][] will be out of beta and available in Hasura CE for PostgreSQL with the release of v2.28, which is imminent. Native Queries allow you to express your query as arbitrary SQL, so you can write more custom `WHERE` clauses and still benefit from Hasura's ability to slice and dice your data.

This means you'd be able to write something like query in the Native Query editor:

```sql
SELECT *
FROM my_table
WHERE "date" BETWEEN current_date - interval '1 day' AND current_date + interval '1 day'
```

You'd give it a name, then you can query it just like you would a table, a view, or a function. The query lives inside Hasura so you don't need to modify your database at all.

[native queries]: https://hasura.io/docs/latest/schema/postgres/logical-models/native-queries/

**Comment by osdiab** [comment]
This is awesome, thanks and looking forward to use it!

Omar

**Comment by osdiab** [comment]
Was there a change that addressed this issue or is the answer just native queries? I ask since Native Queries seem to be a bit half baked since I last tried them and not really a replacement for SQL functions. Thanks!

**Comment by manasag** [comment]
Hi @osdiab, this issue is closed since Native Queries feature aims to solve this pattern. We don't plan to add more direct support of SQL functions in the permissions flow in the V2 of Hasura. Please share more details on how this feature didn't work for your use-case.

**Comment by osdiab** [comment]
Well for one, I [still don't know how to declare a relation between a Native Query and a table](https://github.com/hasura/graphql-engine/discussions/9869) because it seems the only way to set it up is with the metadata API which I've never used before, and so even if I figured it out, using it would basically condemn the native query to be unmaintainable by my team. Hasura team doesn't seem to really care about the commenters there being confused about how we're supposed to use this product as well.
