### ISSUE TITLE
document behaviour when id _eq: undefined or null

### ISSUE THREAD

**Issue by pronevich** [hasura/graphql-engine#2648]
Everything worked well, but then on the client-side happened issue when selected for deletion item `id` has become `undefined` and as result, all items in the table was deleted:

```
{
  variables: { where: { id: { _eq: undefined } } },
}
```

**Comment by 0x777** [comment]
The reason why this happens is because:
```graphql
where: { id: { _eq: null } }
````
reduces to 
```
where: { id: {} }
```
which further reduces to 
```graphql
where: {}
```
and `{}` translates to `true`. `{}` translating to `true` is something that we cannot change now as it breaks a lot of already existing queries. @shahidhk opened [this](https://github.com/hasura/graphql-engine/issues/704) a while ago. I've added my thoughts there. 

For now I suggest you to write the delete mutation as follows: 
```graphql
mutation m delete_article($article_id: Int!) {
  delete_article(where: {id: {_eq: $article_id}}) {
    affected_rows
  }
}
```
and the variables will then be:
```json
{
  "article_id": 1
}
```
Since `$article_id` is defined to be of type `Int!`, a `null` value will never be accepted.

**Comment by m0ngr31** [comment]
Happened to me twice recently. Wasn't a good situation. Would be good to have this explicitly documented.

**Comment by leimantas** [comment]
I don`t use:
`where: { id: { _eq: null } }`

Safer:
`where: {id: {_in: [ ]}}`

**Comment by pronevich** [comment]
@leimantas but this is just a temporary escape hatch, in any time new team member that doesn't know all hasura quirks could catch this issue.

**Comment by pnappa** [comment]
> The reason why this happens is because:
> 
> ```graphql
> where: { id: { _eq: null } }
> ```
> 
> reduces to
> 
> ```
> where: { id: {} }
> ```

I think this could be fixed by preventing nullable types from being compared with some operators (e.g. `{_eq: X }` requires `X` to be some type `Y!`). The reduction from `{ _eq: null }` to `{}` is unintuitive to those unfamiliar with ternary-valued logic in SQL, especially when the column being compared is non-nullable. My 2 cents is that exposing this as a type error is a far more elegant solution to now.

**Comment by marionschleifer** [comment]
This has been documented here: https://hasura.io/docs/1.0/graphql/manual/queries/query-filters.html#evaluation-of-null-values-in-comparision-expressions.

**Comment by pronevich** [comment]
@marionschleifer but the issue still here - one day some broken code could return null / undefined to graphql expression and we will be in troubles

**Comment by marionschleifer** [comment]
@pronevich we are tracking this issue [here ](https://github.com/hasura/graphql-engine/issues/704).
