### ISSUE TITLE
tracking all suggested relationships in console has to be documented

### ISSUE THREAD

**Issue by jjangga0214** [hasura/graphql-engine#2726]
Hasura recommends relationships, based on foreign keys. So users just can "click" the button to create the relationships like this image.

![Screenshot from 2019-08-13 22-50-06](https://user-images.githubusercontent.com/28584151/62947382-61769080-be1d-11e9-9ac7-c73c13987ae3.png)

However, for existing databases with 'many' tables, manually clicking all the buttons is so tedious. Therefore I request a feature to accept EVERY recommended relationships with one click.

**Comment by ecthiender** [comment]
If you go to the main "Data" page, it will list all relationships that can be tracked, under "Untracked foreign-key relations". You can just click on the "Track All" button to track them all.

![Screenshot_2019-08-14 Schema - Data Hasura](https://user-images.githubusercontent.com/616387/62998027-da123700-be87-11e9-8b82-e63efa09ab7a.png)

**Comment by jjangga0214** [comment]
@ecthiender Great! Thank you for letting me know that!

**Comment by jjangga0214** [comment]
@ecthiender Then what if docs explicitly mentions this feature? If so, users would not have to waste their time by just not knowing this feature. Currently, as far as I know, docs doesn't say this feature.

**Comment by oscar6echo** [comment]
I agree the button  "Track All"  under "Untracked foreign-key relations" in the the"Data" page is EXTREMELY USEFUL. Otherwise, it would be practically impossible to use Hasura on an existing database with a large number of relationships.

But what is still missing is an API endpoint to do that: "Track all relationships inferred from db structure" (more precisely, the subset of tracked tables).   
Is there any plan to add this feature soon ?

Because it really is the ONLY step that cannot be automated (i.e. performed through the API).  
You already can:
+ track tables
+ make tables enums (where relevant)
+ manage event triggers and permissions
+ manage remote schemas
+ then download resulting metadata for future use

True, you can create individual relationships though `[create_array_relationship](https://docs.hasura.io/1.0/graphql/manual/api-reference/schema-metadata-api/relationship.html#create-array-relationship)` and `[create_object_relationship](https://docs.hasura.io/1.0/graphql/manual/api-reference/schema-metadata-api/relationship.html#create-object-relationship)` but it is a lot of work to build the many queries to do the same as the "Track All" button on the GUI.

In my company we are starting to use Hasura to expose postgres dBs. Unfortunately this manual step breaks the workflow. I'm surprised this endpoint is not already in the API. I would seem very natural since the work is already done, right ? Is there a reason beyond 'nobody asked for it' ?

Apart from that, I would like to congratulate the Hasura team for the superb work. It is a very useful and promising piece of software !!!

**Comment by jjangga0214** [comment]
@oscar6echo +1

P.S. Currently using an e2e tool would enable a workaround by "clicking" the button in an automatic way.

**Comment by shahidhk** [comment]
@oscar6echo It is not encouraged to "click the button" to track all tables or relationships in a production environment. You should do that once in your dev env and then export the metadata and use import this metadata later in other instances. 
Otherwise, your configuration is never declarative.

See https://docs.hasura.io/1.0/graphql/manual/migrations/manage-metadata.html on how you can use the API to export/import metadata.

**Comment by oscar6echo** [comment]
Ok, understood.  
Thx for the quick answer.

**Comment by rikinsk** [comment]
Closed via #4948
