### ISSUE TITLE
Console support for enums

### ISSUE THREAD

**Issue by dsandip** [hasura/graphql-engine#2767]
In reference to the on-going work for [Enums](https://github.com/hasura/graphql-engine/pull/2672), the following UI and other updates are need:

Edit: Let's just use the `reload_metadata` endpoint for now
## ~API enhancements~
~Given that the current `reload_metadata` call can sometimes be very expensive and the console encourages reloading on atomic operations (*like adding new rows to the Enum table, etc.*), we should have a more granular reload option for Enums too.~

~From @lexi-lambda :~
> We could also add a fit-for-purpose `reload_enum_metadata` API to just reload the enum table

## Console changes

The idea is to let developers mark a new/existing table as an Enum table, provided it meets the criterion for it (*documented in the PR referenced above*). Additionally, you should also be able to refresh Enums' metadata when adding rows to such a table or, if you've added said rows outside the console, in the `Browse rows` section.

1. **Create Table**
   a) Compatible table:  https://app.moqups.com/0eepEW20UV/view/page/aeaf81dcc?ui=0&fit_width=1
   b) Incompatible table: https://app.moqups.com/0eepEW20UV/view/page/ab6cc8017?ui=0&fit_width=1

1. **Modify Table**
   a) Compatible table: https://app.moqups.com/0eepEW20UV/view/page/a0888ce28?ui=0&fit_width=1
   b) Incompatible table: https://app.moqups.com/0eepEW20UV/view/page/abdb3fb84?ui=0&fit_width=1

1. **Insert rows** (*for only those tables marked as Enum*): https://app.moqups.com/0eepEW20UV/view/page/a4aad660e?ui=0&fit_width=1

1. **Browse rows**(*for only those tables marked as Enum*): https://app.moqups.com/0eepEW20UV/view/page/a769f8e37?ui=0&fit_width=1

**Comment by dsandip** [comment]
The console can use the existing `reload_metadata` call so as to not make the API enhancement a blocker for the console work. 
cc: @rikinsk

**Comment by wawhal** [comment]
While marking a table as enum during its creation, enum values have to be taken from the user because GraphQL spec does not allow empty enums. This will require new UI to be built.

For the upcoming release, we are going to support marking only existing enum compatible tables as enums. So if you wish to create an enum table, you would:

1. Create a table with exactly one text type column or exactly two text type columns
2. Insert some values
3. Mark it as enum

For existing tables, if the table has exactly one text type column, exactly two text type columns and at least one row inserted, you can mark it as enum.

cc: @rikinsk @lexi-lambda

**Comment by mnlbox** [comment]
@wawhal My enum table now has 4 column:
1. id | uuid
2. title | text
3. description | some description for this enum value | optional
4. created_at | datetime | I'm using this for sort values in UI

So I can't use this Enum feature? :thinking:
