### ISSUE TITLE
Option for Simple Logs

### ISSUE THREAD

**Issue by hspak** [hasura/graphql-engine#2770]
Hello!

We're using a customized version of the`hasura/graphql-engine:v1.0.0-beta.3.cli-migrations` docker container to automate hasura migrations in AWS.

Can we add support for an option for simpler logging? The current logs are hard to read in AWS
```
Checking for update... ◐  Checking for update... ◓  Checking for update... ◑  Checking for update... ◒  Checking for update... ◐  Checking for update... ◓  Checking for update... ◑  Checking for update... ◒  Checking for update... ◐  Checking for update... ◓  Checking for update... ◑  Applying migrations...◐  Applying migrations...◓  
```

**Comment by shahidhk** [comment]
We can switch to JSON logging for CLI if a non-tty environment is detected.

**Comment by mwarger** [comment]
@shahidhk I think I'm seeing the same issue in Google Cloud with log output in stackdriver.  It appears that migrations have happened for long enough that I'm suspicious that there's an error in the migration that's actually being hidden below what seems like truncated output because of the amount of "Applying migrations..." messages being sent to the logger.  Is there any ETA on this fix or a way to try it out ahead of release?  Thank you.
