### ISSUE TITLE
schema update error after upgrading to beta.6 on heroku (hobby plan)

### ISSUE THREAD

**Issue by brightloudnoise** [hasura/graphql-engine#2864]
I followed the instructions to upgrade to the latest hasura deployment on my heroku hobby plan, but now heroku reports the app crashes on restart and looking at the logs I see what looks like schema update errors when hasura starts. {"internal":{"statement":"\n    INSERT INTO "hdb_catalog"."hdb_table" (table_schema, table_name, is_enum)\n    VALUES ($1, $2, $3)\n  ","prepared":false,"error":{"exec_status":"FatalError","hint":null,"message":"column "is_enum" of relation "hdb_table" does not exist","status_code":"42703","description":null},"arguments":["(Oid 25,Just ("hdb_catalog",Binary))","(Oid 25,Just ("hdb_query_collection",Binary))","(Oid 16,Just ("\NUL",Binary))"]},"path":"$.args[0].args","error":"postgres query error","code":"unexpected"}

how do I fix this?

**Comment by lexi-lambda** [comment]
What version of Hasura are you upgrading from? If it was a version older than beta.5, it’s probably a duplicate of #2826, which is a known issue (but unfortunately not fixed yet).

The workaround for the moment is to upgrade to beta.5 first, start Hasura to run the migrations, then upgrade to beta.6. We’re intending to fix the issue soon to make doing that unnecessary (since it shouldn’t be necessary), but we haven’t gotten to it yet.

**Comment by brightloudnoise** [comment]
Thanks. I got it working after following the [instructions to upgrade to a specific version](https://docs.hasura.io/1.0/graphql/manual/deployment/heroku/updating.html#deploy-a-specific-version-of-the-hasura-graphql-engine)
