### ISSUE TITLE
multiple values on enum field

### ISSUE THREAD

**Issue by amine-benselim** [hasura/graphql-engine#2903]
I have an ENUM table 'language`, and I have a field on my user that is supposed to be able to get more than one language. 

doing a mutation of this way:
```
mutation {
 insert_user(
    objects: {
      name: "amin"   
      language: [GERMAN, ENGLISH]
    }
  ) {
    affected_rows
  }
}
``` 

shows me an error  `expected type language_enum, found [GERMAN, ENGLISH]` 

what I did is set an Array relationship on the user table to the Enum table (`language . language  → user . language`) but that did not work for me. 

is there a solution to set the schema this way?

**Comment by lexi-lambda** [comment]
What is the type of the `language` column in the Postgres schema, i.e. what is the output of `psql -c '\d+ language'`?

**Comment by amine-benselim** [comment]
the output of the command is: 
```shell
Column  | Type | Collation | Nullable | Default | Storage  | Stats target | Description
----------+------+-----------+----------+---------+----------+--------------+-------------
 language | text |           | not null |         | extended |              |
Indexes:
    "Languages_pkey" PRIMARY KEY, btree (language)
    "Languages_Language_key" UNIQUE CONSTRAINT, btree (language)
Referenced by:
    TABLE "resource" CONSTRAINT "resource_language_fkey" FOREIGN KEY (language) REFERENCES language(language) ON UPDATE RESTRICT ON DELETE RESTRICT
```

**Comment by lexi-lambda** [comment]
Err, sorry, I meant `psql -c '\d+ user'`. I’m interested in knowing what the type of the `language` column on `user` is.

That said, I imagine it’s of type `text`, which a foreign key constraint referencing the `language` table, right? That would mean each `language` column only holds one `text` value, so even ignoring Hasura’s special treatment of enum tables, that schema only supports associating one language with each user.

Since enum tables are just a way to express enums using ordinary relational modeling techniques, I think the right thing to do would be to model a many-to-many relationship the ordinary relational way: create a join table between `user` and `languages` that contains references to both.

**Comment by amine-benselim** [comment]
thank you for this approach. I did model it that way now and it worked. maybe worth explaining this in the documentation 🤔
