### ISSUE TITLE
Using postgres functions in custom permissions check

### ISSUE THREAD

**Issue by aaronhayes** [hasura/graphql-engine#2944]
I would like to use postgres function when within custom permissions checks. My use case is checking if the `expires_at` column is greater than the current timestamp `now()`. 

Something like this: 
![image](https://user-images.githubusercontent.com/4180720/65661317-b2acad80-e074-11e9-86e2-9ba73dc1ceb8.png)

Is this supported? If so, we should add documentation to [Permission Rules](https://docs.hasura.io/1.0/graphql/manual/auth/authorization/permission-rules.html#row-level-permissions) happy to help if needed.

**Comment by ecthiender** [comment]
Postgres functions generally are not supported, but as `now()` is a postgres literal, it works. But the issue is Hasura uses prepared statements. So when a query with this permission is executed for the first time, the `now()` is evaluated and is stored as a prepared statement. So, subsequent calls with the same query will have wrong `now()` value.

PS: you can disable the prepared statements behaviour, but you might lose some performance.

**Comment by aaronhayes** [comment]
Thanks @ecthiender  for the reply, I was not aware about that prepared statement behaviour. 👍 

If anyone else is running into a similar issue to mine. It is pretty trivial to create a view and manage permissions that way. I still think it would be ideal to do this within the hasura permission rules.

**Comment by ecthiender** [comment]
@aaronhayes as you mentioned, the view workaround works for now. But I agree it would be ideal to have this in the permissions. There is #2575 open for this. It would be great if you can upvote/comment on that. 

Can I close this issue then?

**Comment by aaronhayes** [comment]
@ecthiender absolutely - didn't see that issue, closing this a duplicate.
