### ISSUE TITLE
docs: page on how subscriptions work

### ISSUE THREAD

**Issue by marionschleifer** [hasura/graphql-engine#3050]
Feedback from @elgordino:

'How do subscriptions work'. I usually link to this https://github.com/hasura/graphql-engine/blob/master/architecture/live-queries.md which is super great but very technical and it discusses a number of approaches that were not adopted. I think a simpler explanation in the regular docs would be useful if it doesn't already exist.

**Edit**: After a review of @lexi-lambda, we decided that this section should be added as a page in the [`How it works` section](https://docs.hasura.io/1.0/graphql/manual/how-it-works/index.html) of the docs.

**Comment by pydevsg** [comment]
Hi @marionschleifer , I would like to work on this, can you tell what actually I need to implement for a good documentation.

**Comment by hnarasaki** [comment]
I'd like to work on this! Draft PR created: https://github.com/hasura/graphql-engine/pull/3094

**Comment by agarwalrounak** [comment]
I am working on this issue.

**Comment by hnarasaki** [comment]
@marionschleifer My draft PR was auto closed I think: https://github.com/hasura/graphql-engine/pull/3094. Do you know why this happened, or if my process was wrong? I'm actively working on this.

**Comment by marionschleifer** [comment]
@hnarasaki This was a misunderstanding, sorry about this. I re-opened the PR. Feel free to push to the PR regularly, so that we can see your progress 🙂

**Comment by hnarasaki** [comment]
@marionschleifer No problem, thanks! :) I was just unsure if I created the Draft PR wrong since I've never seen the draft feature before.

**Comment by hnarasaki** [comment]
@marionschleifer I finished adding my changes. Updated my Draft PR to a regular PR. Requested review on the PR: https://github.com/hasura/graphql-engine/pull/3094 Thanks! :)

**Comment by elgordino** [comment]
Hi. I'm the original requestor via @marionschleifer. This #3094 is a good start but what I had in mind is something that has more technical detail but is less comprehensive than the architecture page.

There is a frequent request in Discord for details on how subscriptions work, folks need to know it's database polling because once you know that it becomes clear how it works with views and other derived data, until you know that it's polling it appears to be 'magic', which may result in poor architectural decisions. 

I usually route folks to the architecture page, but it covers approaches that were not adopted and it a lot to filter through to get to the raw 'how it works' detail. 'idea #3' and part of 'when do we refetch' describe how it works, the surrounding text is about approaches that were not adopted.

**Comment by agarwalrounak** [comment]
Hi @elgordino, please have a look at PR #3103. I have broken down the architecture page and extracted out the components into different sections. At each level, the docs provides a simpler explanation and if the user is further curious, he/she can view additional information as given.

**Comment by robertjdominguez** [comment]
Close as we now have these docs 👍
