### ISSUE TITLE
Add computed columns to permissions

### ISSUE THREAD

**Issue by leoalves** [hasura/graphql-engine#3223]
Is it possible to add computed columns to the permissions?  

I think this can simplify some of my complex permissions.  Instead of creating views and relationships.

Thanks

**Comment by leoalves** [comment]
I guess adding the computed column to the `*_bool_exp` type will be the same as adding it to the permissions.  That's why I am adding this here  

I just had a use case where I want to filter some columns by a specific interval.  I created the function. It's working as intended but I am not able to filter it.

Here is what I was trying to do.

```SQL
CREATE OR REPLACE FUNCTION custom_interval (custom_interval text, table_row table)
RETURNS timestamptz 
AS $$
SELECT (now() - $1::interval)
$$
LANGUAGE SQL STABLE
```
```javascript
query {
   table (where:{ created_at:{_cgte: interval({args: {custom_interval: "10 days"}})} }) {
      name
    }
}
```

**Comment by rakeshkky** [comment]
@leoalves The query you mentioned in the above comment is not a valid graphql query.
We didn't include computed fields to `*_bool_exp` because of lack of support for parameters for input fields in GraphQL syntax. For Example:

```graphql
table (where: {computed_field(args: {arg_1: "arg value"}): {_eq: "some value"}}){
  name
}
```
It is not a valid GraphQL query.

**Comment by leoalves** [comment]
Hi @rakeshkky,
Maybe an alternate type, that extends the *_bol_exp, *_compute_bol_exp?  
I think this would be very useful to have
```javascript
table (where: {computed_field: {
    _args: { 
     arg_1: "arg value",
     arg_2: "arg_value"
   },
  _eq: "some value"
}){
  name
}
```

**Comment by karibertils** [comment]
A standard solution to apply arguments to the input fields would also solve other issues i ran into when using hasura and was forced into using the escape hatches.

For a JSONB i needed to do something like {where: my_json(path: "dynamicKey1.k2.k3") { _ilike: "string%" } on a multiple occasions.

Being able to order by the computed field while also taking arguments should also be considered. In #1357 the same problem appears.

**Comment by rakeshkky** [comment]
@karibertils As per [GraphQL spec](https://graphql.github.io/graphql-spec/June2018/), unfortunately, input fields do not support arguments.

**Comment by rakeshkky** [comment]
@leoalves 
As far as I can see, we can support computed fields whose underlying functions accept only one input argument (table row type) and return scalars in `where` and even in `order_by`. Since the table row argument is auto-determined and no need for `args` if arguments other than table row argument are not found.

**Comment by MatthiasGrandl** [comment]
@rakeshkky what's the state on supporting computed columns in `where` and `order_by` ? This would make my life a lot easier.

**Comment by barmaley443-sfdev** [comment]
> @rakeshkky what's the state on supporting computed columns in `where` and `order_by` ? This would make my life a lot easier.

+1
now receiving "field \"computed\" not found in type: 'table_order_by'"

**Comment by tirumaraiselvan** [comment]
I think the first point of this issue was about permissions. Permissions for computed columns are derived based on the underlying permissions: https://hasura.io/docs/1.0/graphql/manual/schema/computed-fields.html#computed-fields-permissions

Scoping this issue to permissions and for filter i.e. where expressions over computed fields, it is being tracked here: https://github.com/hasura/graphql-engine/issues/3772
