### ISSUE TITLE
Update token

### ISSUE THREAD

**Issue by robertfernanV** [hasura/graphql-engine#3309]
Hello, I have a question the token is automatically updated in a custom jwt provider, in the container configuration I have the key parameter

**Comment by ecthiender** [comment]
@robertfernanV  I am not very sure what token are you talking about.

Are you talking about JWT issued by your custom provider? Or are you talking about JWKs (the public key in JWT configuration)? My guess is you are talking about JWKs.

If you are mentioning that the JWKs gets updated/rotated, then you should use the JWK URL configuration, so that Hasura automatically updates your JWKs. See https://docs.hasura.io/1.0/graphql/manual/auth/authentication/jwt.html#jwk-url

**Comment by robertfernanV** [comment]
hello, I @ecthiender  had not understood until you stressed the difference of jwk and jwt, for a moment I thought that automatically renews the jwt and it is not so! Thank you
