### ISSUE TITLE
Inheritance in Postgres

### ISSUE THREAD

**Issue by rsingh-27** [hasura/graphql-engine#3453]
Hi,
I am very new to Hasura and did not find any solution to implement inheritance of tables, something on the lines below

```
CREATE TABLE cities (
    name            text,
    population      float,
    altitude        int     -- in feet
);

CREATE TABLE capitals (
    state           char(2)
) INHERITS (cities);
```
Can anyone point me, how to achieve this

**Comment by marionschleifer** [comment]
@rsingh-27 you can achieve this via `Run SQL`. On the Hasura console, click on the `Data` tab, then on `SQL` on the left side. In the SQL window, you can write the create statements:

![image](https://user-images.githubusercontent.com/5722022/69917681-e3400780-1468-11ea-8fbe-f32e91df5f2e.png)

Don't forget to leave the box `Track this` checked, so that the tables are exposed over the GraphQL API.

Let us know if you have any more questions 🙂

**Comment by tirumaraiselvan** [comment]
Should we think about interface types for inheritance?

**Comment by rsingh-27** [comment]
@marionschleifer Let me try this

**Comment by marionschleifer** [comment]
@rsingh-27 I'm closing this issue. Feel free to re-open if you have more questions on this 🙂
