### ISSUE TITLE
support column operators (_ceq, etc) in permission rules to reference other tables

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/graphql-engine#3459]
In permissions, column operators like _ceq, _cgt can only refer to the "currently selected" table i.e. we can do `{table1.c1 : { _ceq : table1.c2}}` . 

We should look at supporting spanning across other tables like: `{table1.c1 : { _ceq : table2.c3}}` .

**Comment by dijam** [comment]
Any update over this feature? It has been a while and it can be super useful for us to see this feature inside hasura rather using an external system to take care of it for us.

**Comment by tirumaraiselvan** [comment]
@dijam We will take this up very soon. As a workaround, I can suggest using postgres triggers for the time being. You can access role information via the method described in this issue: https://github.com/hasura/graphql-engine/issues/1582

**Comment by tirumaraiselvan** [comment]
Proposed API:

The `filter` key in permissions can take a new [BoolExp](https://hasura.io/docs/1.0/graphql/manual/api-reference/schema-metadata-api/syntax-defs.html#boolexp) or it can be another value in [ColumnExp](https://hasura.io/docs/1.0/graphql/manual/api-reference/schema-metadata-api/syntax-defs.html#columnexp) with the following syntax:

```
{
    PGColumn : { Operator : TableValue }
}
```

where `TableValue` has the following schema:


```
{
    "_table": TableName,
    "_column": PGColumn
}

```

**Comment by pronevich** [comment]
Very often I'm hitting the wall with this issue)) Thanks for future solution, will be waiting.

**Comment by fvieira** [comment]
I also need this, I'll leave my use case here:

I have a table A that has a 0..1 relationship to B (i.e. all rows of A point to a row of B, but some B rows can exist without an A row pointing to them), and I need to set the permissions of a role R so as to only let R select the rows of B that are pointed to by A.
To do this I want to have a Custom Check that only allows R to select B rows where EXISTS A.bId = B.id, hence why this issue is important to me.

**Comment by duskmoon314** [comment]
This is still in progress, right? How soon can we expect to see this feature released?

**Comment by Jrodseth** [comment]
+1 this would be _incredibly_ useful

**Comment by Konard** [comment]
Relationships should be supported too.

**Comment by kedarguy** [comment]
+1

**Comment by Andrew-Bekhiet** [comment]
This feature is the only one blocking me from using hasura

**Comment by Andrew-Bekhiet** [comment]
I need this feature as it's the only thing blocking me from using hasura

**Comment by tirumaraiselvan** [comment]
The support for this was released in v2.0.0 . Sorry for not closing this issue earlier!

From the release notes: https://github.com/hasura/graphql-engine/releases/tag/v2.0.0 

> ### Support comparing columns across related tables in permission's boolean expressions
> 
> We now support comparing columns across related tables (fixing #3459) . For example:
> 
> Consider two tables, `items(id, name, stock)` and `shopping_cart(id, item_id, quantity)`
> and these two tables are related via the `item_id` column. Now, while defining insert permission
> on the `shopping_cart` table, there can be a check to insert an item into the shopping cart
> only when there is enough `stock` present in the `items` table.
> 
> <img src="https://user-images.githubusercontent.com/8663570/115574796-9409a980-a2df-11eb-9844-00f0af9dd3b8.png" width="800">
> 

The docs for column comparison operators are available here: https://hasura.io/docs/latest/graphql/core/api-reference/syntax-defs/ (Please search for "Column Comparison Operators")

**Comment by poita66** [comment]
> The support for this was released in v2.0.0 . Sorry for not closing this issue earlier!

This doesn't seem to work in v2.6.1 with an SQL Server table. Does this only apply to Postgres?

**Comment by pscanlon1** [comment]
This should be in your examples. I have been using Hasura for years and just found this today :)

**Comment by asegal-singlepane** [comment]
@tirumaraiselvan is there any way to use column comparison operators where you traverse relationships above/below the root ($) of the table that we are setting permissions on?  

Consider a relationship like  (A) -> (B) ->  (C) ->(D).  We want to set permissions on D if there exists a record in A where the field FK of B.ID is present and matches the FK of B.ID on C.  Because the FK of B.ID doesn't exist on D, there is no way for us to say exists A where B.ID _ceq D ($) -> C ->B.ID

Are there any workarounds here or something in the docs I'm missing?

**Comment by asegal-singlepane** [comment]
@tirumaraiselvan in attempting to do this manually in the permission editor I got the error: "relationship references are not supported in column comparison rhs" so I take this to answer my own question.  However I would still ask if there are undocumented workarounds and/or whether this is on the roadmap.
