### ISSUE TITLE
hasura-dev cli manual migration error

### ISSUE THREAD

**Issue by erler** [hasura/graphql-engine#3506]
when trying to run a migration manually with `hasura-dev migrate apply --admin-secret <my-admin-secret>` I get the following error:
`FATA[0012] apply failed: json: cannot unmarshal string into Go struct field HasuraError.internal of type hasuradb.SQLInternalError` 

folllowing the steps outlined [here](https://github.com/paritytech/polkassembly/tree/master/hasura)

**Comment by tirumaraiselvan** [comment]
@shahidhk Any clues? 

From the link, they are using remote-joins build.

**Comment by tirumaraiselvan** [comment]
@erler This is perhaps happening because server returned some unknown error which `hasura-dev` does not handle very well right now as it works off master branch. We are working on printing the raw response of the error per this PR: https://github.com/hasura/graphql-engine/pull/3104

But for the time being can you just check if there are any inconsistent schema objects in your server by starting the console?

**Comment by erler** [comment]
@tirumaraiselvan thanks, I spotted something in the console. All working fine :)
