### ISSUE TITLE
[RFC] run hasura without hdb_catalog tables

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/graphql-engine#3533]
This is a big architectural refactor which will obviate the need for hdb_* schemas and tables. Instead, hasura can start from just the metadata.yaml file which can be given as a server-flag.

Why do we need hdb_* schemas in the first place?

~1. Insert permissions are based on postgres triggers on hdb_views : How can we move the logic to the app layer?~ Solved via https://github.com/hasura/graphql-engine/pull/3598 
2. We store lot of user generated events for event-triggers and actions in hdb_catalog : This can probably be solved by asking for user-defined tables. This also makes sense as these are user-events and not hasura configuration.
3. Easier dev workflow: Currently, having hdb_* is easier because you don't need to continuously reload the metadata file or even generate one (e.g. how will people try-out on heroku?).

If we do this, we can solve the following use-cases quite trivially:

1. Hasura(s) on multi-tenant postgres
2. Handle lot of existing postgres users, who don't have admin access on postgres.
3. Co-existing versions / Blue Green deployments of Hasura
4. https://github.com/hasura/graphql-engine/issues/3496

But this would create new problems like:

1. What if users modify metadata on prod? How will they persist new metadata? How will they sync across instances?
2. Event logs are in public namespaces now. What if we need to do migrations on event log tables, etc?

**Comment by shahidhk** [comment]
- CLI makes use of `hdb_catalog.schema_migrations` to store the migrations state
- Console uses `hdb_catalog.hdb_version.console_state` to store some state
- CLI/Console/Server all uses `hdb_catalog.hdb_version.hasura_uuid` for telemetry

**Comment by davidecavestro** [comment]
IMHO the ability to alter metadata on prod without redeploy is a feature... indeed a great one!

As of now a custom UI can define a new table simply demanding some calls to _run_sql_, _track_table_ and _create_xyz_permission_.
It can be easily achieved through a companion service with admin access.

When data structure is quite dynamic, automated redeploys wouldn't provide the same QoS as live changes: i.e. clients should probably open new websockets for live subscriptions and so on.

**Comment by soneymathew** [comment]
@tirumaraiselvan Do we even need metadata in prod if persisted query can be specified as a constraint?

Inspired by the spirit of disappearing frameworks that does all the work at compile time, The key lessons that I can take away from a few are
- Not everything needs to be done at runtime for every request. (Eg: sveltejs)
- A lot of pre-work can be done at build/dev/design time that avoids the overhead from every single client (Eg: relay-compiler)

What if My server want to permit only persisted GraphQL queries. By the time my CI pipeline is finished I am aware of exactly what GraphQL queries are needed by my application clients ( web/mobile).

Given a GraphQL query I know that Hasura can generate the SQL that backs it. I want to be able to persist the generated SQL someplace (disk/DB/redis) to avoid the runtime overhead to generate it per request.
The runtime component should be able to avoid all the repeated translation overheads that every request need to otherwise suffer without having the prior knowledge of a persisted query.

thoughts?

**Comment by Akira-Taniguchi** [comment]
I thought it would be good to add an option in hasura to disable mutation queries.

What do you guys think?

**Comment by tirumaraiselvan** [comment]
With v2.0, you can separate Hasura's metadata into a separate postgres db: https://hasura.io/docs/latest/graphql/core/deployment/graphql-engine-flags/config-examples.html#add-metadata-database
