### ISSUE TITLE
Configurable websocket keep-alive interval

### ISSUE THREAD

**Issue by walfie** [hasura/graphql-engine#3539]
For websocket subscriptions, keep-alive messages are sent every 5 seconds. Is it possible to have this value be configurable? For example if I wanted to set it to 30 seconds instead, or disable it entirely.

It looks like it's hard-coded at the moment (assuming I'm looking at the right place):
https://github.com/hasura/graphql-engine/blob/b81d22f5831240d2566824d74b1d7e4d107fdb61/server/src-lib/Hasura/GraphQL/Transport/WebSocket.hs#L189

**Comment by arpitjacob** [comment]
Hey guys any way to change this?

**Comment by abooij** [comment]
To clarify on this, the goal would be to add a configuration flag similar to `--stringify-numeric-types` that has to be threaded through the codebase to the relevant place (namely `server/src-lib/Hasura/GraphQL/Transport/WebSocket.hs`). So the steps are:

1. Add a new `KeepAliveDelay` newtype wrapper around the `Seconds` data type (the latter is defined in `server/src-lib/Data/Time/Clock/Units.hs`).
2. Expand the `ServeOptions` data type in `server/src-lib/Hasura/Server/Init/Config.hs` to additionally store a `KeepAliveDelay`.
3. Expand `server/src-lib/Hasura/Server/Init.hs` to support parsing a `--websocket-keepalive` flag, that takes a number of seconds, and stores this value in the `ServeOptions` object.
4. Somehow pass this value to `onConn` in `server/src-lib/Hasura/GraphQL/Transport/WebSocket.hs`. It may be desirable to pass it using `MonadReader`, using the same style that is used for `--stringify-numeric-types` which is passed in a `QueryContext` object. That way, one could simply add a reader constraint to `onConn`, and ask the compiler where this constraint needs to be satisfied, rather than having to change the number of arguments of many functions.

**Comment by KarolKalbarczyk** [comment]
I am going to give this issue a try.

**Comment by gahag** [comment]
@KarolKalbarczyk are you still working on this? If not, I could take it.

**Comment by v0d1ch** [comment]
@KarolKalbarczyk I noticed some time passed since your last message and decided to try to tackle this for fun. Please close my PR if you did some work already locally, I didn't mean to steal your thunder just to explore the codebase a bit.

@abooij I think the argument passing through some of the related functions could use some love but I didn't want to go out of scope of the task. If you want this handled just create the issue and I'd be happy to help out.
