### ISSUE TITLE
An operation already exists with this id

### ISSUE THREAD

**Issue by cah-rob-snider** [hasura/graphql-engine#3564]
I am getting this error:
https://github.com/hasura/graphql-engine/blob/756d8abd54c096bfe7afcb6491650149e53cc35f/server/src-lib/Hasura/GraphQL/Transport/WebSocket.hs#L267

I am not familiar with this programming language. What would cause this error to be thrown? I assume the websocket is trying to reconnect, but the uuid it is generating for the session already exists. I just don't know what would trigger that.

**Comment by 0x777** [comment]
We implement the Apollo's websocket protocol for GraphQL queries as described [here](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md). Which client library are you using? This happens when a client sends two operations with the same operation id (it shouldn't be doing this) on the same websocket connection.

**Comment by cah-rob-snider** [comment]
I am using GraphQL in Flutter: https://github.com/zino-app/graphql-flutter

Based on your response, I think it may have to do with the way that the library is re-establishing the connection when it drops. I can look more into it, but this was helpful!!

**Comment by 0x777** [comment]
@cah-rob-snider I'm closing this issue, please feel free to re-open this if you have more context to add.
