### ISSUE TITLE
Delays due to busybox

### ISSUE THREAD

**Issue by uniyalaa** [hasura/graphql-engine#3577]
Hello team,

We have been trying to get Hasura into our organisation's official container registry so that we can use it.
It needs to go through and pass certain vulnerability scans. Unfortunately, we are struggling on our side because busybox requires additional functionality of binary scanning to scan the image for vulnerabilities.
This will cause substantial delays for us.
Is it at all possible for you to build a new image based on a OS which we can scan like alpine, debian or centos?

Many thanks,
Aastha

**Comment by 0x777** [comment]
Hi, this is something we might add in future but we can help you build a graphql-engine image which is as per your organization's requirements. 

The official docker image [is built as follows](https://github.com/hasura/graphql-engine/blob/master/server/packaging/Dockerfile):
1. The source code is mounted into an appropriate `fpco/stack-build` image (the image with the compiler and build tools) and then compiled to produce the `graphql-engine` binary.
2. The binary is then copied into an image which has all the necessary dependencies and then a minimal root file system is created with the binary and all its dependencies. 
3. The root file system is then added to the scratch image (an empty image) to produce the final image. 

This is done so that the image size is as small as possible (ideally we would like to statically link everything and publish a binary but it is non trivial and we haven't looked into this).

In your case, you can stop after step 1, the image size would be huge (~5GB) because of the compiler and build tooling but the image would be based on debian/ubuntu.

**Comment by tirumaraiselvan** [comment]
@uniyalaa We can also supply a custom docker/binary for you. Please ping me in Discord (https://discordapp.com/invite/hasura) , my handle is `@Tiru` and we can set it up in a couple of hours.

**Comment by uniyalaa** [comment]
@0x777 and @tirumaraiselvan - I'll check internally if these solutions will work for us or not and get back to you. Thanks.

**Comment by tirumaraiselvan** [comment]
@uniyalaa Also, pls let us know what methodology would actually work inside your org.

**Comment by uniyalaa** [comment]
@tirumaraiselvan - Sure. I am trying to find out.  We are using Sysdig for vulnerability scanning and the problem is that, they have informed us, busybox requires additional functionality of binary scanning to scan the image for vulnerabilities (it has no package manager, no 3rd party feeds). 

If you create a custom docker image for us, will you maintain/publish and manage it same as your standard images?

Thanks,
Aastha

**Comment by tirumaraiselvan** [comment]
@uniyalaa Let's talk about what the maintenance might look like on Discord?

**Comment by uniyalaa** [comment]
@tirumaraiselvan - it blocked here at work.

**Comment by tirumaraiselvan** [comment]
@uniyalaa You can also reach me at `tiru@hasura.io`

**Comment by uniyalaa** [comment]
@tirumaraiselvan - sure. I'll do that. Just waiting for some more people to be back in the office in the new year to answer my queries. Thanks for quick responses. I'll email you next time.

**Comment by tirumaraiselvan** [comment]
Closing this as the request is handled by this issue: https://github.com/hasura/graphql-engine/issues/4837
