### ISSUE TITLE
Does Hasura natively support Arrays? If not, what's the best way to implement arrays (int & string) and when will hasura start supporting arrays natively?

### ISSUE THREAD

**Issue by Nau4man** [hasura/graphql-engine#3616]

**Comment by 0x777** [comment]
@Nau4man You can use Postgres's literal syntax for arrays as documented [here](https://docs.hasura.io/1.0/graphql/manual/mutations/insert.html#insert-an-object-with-an-array-field). We recommend you to use one to many relationships instead of arrays if that's a right fit for your data. 

Adding native support for arrays is something that we have been thinking for a while now but unfortunately this is currently in our backlog and we hope to pick it up soon. Closing this in favour of https://github.com/hasura/graphql-engine/issues/348

**Comment by Nau4man** [comment]
> @Nau4man You can use Postgres's literal syntax for arrays as documented [here](https://docs.hasura.io/1.0/graphql/manual/mutations/insert.html#insert-an-object-with-an-array-field). We recommend you to use one to many relationships instead of arrays if that's a right fit for your data.
> 
> Adding native support for arrays is something that we have been thinking for a while now but unfortunately this is currently in our backlog and we hope to pick it up soon. Closing this in favour of #348

Thanks for your answer. What datatype should I use in Hasura in order to pass arrays as Postgres literal? Should it be of Text type? If so, I have tried that but hasura is treating it as a string.

**Comment by Nau4man** [comment]
@0x777 Thanks for your answer. What datatype should I use in Hasura in order to pass arrays as Postgres literal? Should it be of Text type? If so, I have tried that but hasura is treating it as a string.
