### ISSUE TITLE
Characters in need of quoting can not be used in passwords

### ISSUE THREAD

**Issue by dsvensson** [hasura/graphql-engine#372]
When using --database-url or the corresponding environment variable, passwords containing "exotic" characters are incorrectly handled leading to authentication failures. A workaround is to use the `--password` etc flags that do not exhibit this issue.

**Comment by ecthiender** [comment]
@dsvensson hey now you should be able to use URL-encoded strings in your passwords if they have special characters.

**Comment by corinabioinformatic** [comment]
Hello! I know this issue is closed, but I get an error due to my HASURA_GRAPHQL_METADATA_DATABASE_URL variable when i pass it to docker-compose. 
I am using image: hasura/graphql-engine:v2.38.
My errror says 
hasura_graphql  | {"error":"connection error","path":"$","code":"postgres-error","internal":"could not translate host name \"passwordspecialCharacter@db\" to address: Name or service not known\n"}
