### ISSUE TITLE
Failed to build schema-cache because of inconsistent metadata: postgres query error

### ISSUE THREAD

**Issue by hunterbecton** [hasura/graphql-engine#3725]
I tried downgrading Hasura from 1.0.0 to `hasura/graphql-engine:pull2395-7ea7f82c` so I could create remote data relationships. However, I got an error that the catalogue was 28 and that it was expecting 26 or less.

That led me to try and downgrade my catalogue, but there wasn't a link from [on this page](https://docs.hasura.io/1.0/graphql/manual/deployment/downgrading.html) on how to downgrade from 28 to 27. However, I found someone point someone in the Discord to [this page](https://github.com/hasura/graphql-engine/blob/db5072dff3efdd3560c9755104550c698e5cd719/server/src-rsr/migrations/28_to_27.sql), which has a SQL statement for downgrading. However, I think the issue is that I didn't include:

```
UPDATE hdb_catalog.hdb_version
   SET version = '27'
 WHERE version = '28';
```

After I attempted to downgrade I still got the same error as before, so I tried to revert back to version 1.0.0, but I came across the `Failed to build schema-cache because of inconsistent metadata: postgres query error` in my Heroku logs.

How can I fix this issue? I'm assuming I need to write a new SQL statement, but I'm not sure how to even attempt that when my app is crashing in Heroku.

**Comment by tirumaraiselvan** [comment]
Hi @hunterbecton 

Pls follow the instructions here to reset your metadata essentially: https://github.com/hasura/graphql-engine/issues/3209#issuecomment-545833354

> 1. Get an export of the metadata using the console on the Remote Joins instance: https://docs.hasura.io/1.0/graphql/manual/migrations/manage-metadata.html#exporting-hasura-metadata
> 2. Stop Hasura and `drop schema hdb_views` and `drop schema hdb_catalog` ( this essentially drops all hasura metadata) using psql or some client.
> 3. Run Hasura beta8 and then import metadata again: https://docs.hasura.io/1.0/graphql/manual/migrations/manage-metadata.html#importing-hasura-metadata

Note that in step 1, you should use a working version of hasura (in the original post, it was pr2395). Since, you have also manually downgraded migrations, you are probably in a trickier situation (and hence, always backup your metadata before doing anything dangerous). You might have to apply the up migrations again so that version 1.0.0 works and then export the metadata.

**Comment by marionschleifer** [comment]
@hunterbecton just checking in if your issue is solved? If yes, we can close the issue 🙂

**Comment by hunterbecton** [comment]
Yes, thank you @marionschleifer
