### ISSUE TITLE
[RFC] Single row mutation

### ISSUE THREAD

**Issue by rakeshkky** [hasura/graphql-engine#3731]
Currently, all mutations we have are bulk. We need to have single mutations for inserting one object for insert and update/delete by primary key column. This solves the simpler use cases for mutating a single row in a table. I'm proposing the following GraphQL schema for the same.

**1.Insert**
```graphql
insert_author_one(object: author_insert_input!, on_conflict: author_on_conflict): author
```

**2.Delete**
```graphql
delete_author_by_pk(col1: col-ty1!, col2: col-ty2!): author
```
**3.Update**
```graphql
update_author_by_pk(pk_columns: table_pk_columns_input!, _set: author_set_input, _inc: author_inc_input): author
```

```graphql
input table_pk_columns_input {
  col1: col-ty1!
  col2: col-ty2!
}
```

The output of all the above mutations is null-able `<table-name>` type. If the mutation modifies the database, then it returns the *after* mutation table data object for insert/update else it is a `null` value. For delete, it returns data if row exists (and deleted), else `null` if row does not exist for given primary key column value.

**Comment by tirumaraiselvan** [comment]
Hey why do we need `pk_columns: table_pk_columns_input!` ?

Why can't it be: `delete_author_by_pk( col1: col-ty1!,  col2: col-ty2!): author`

**Comment by tirumaraiselvan** [comment]
And 

`update_author_by_pk(pk_columns: table_pk_columns_input!, _set: author_set_input, _inc: author_inc_input): author`

could be

`update_author_by_pk(where: table_pk_columns_input!, _set: author_set_input, _inc: author_inc_input): author`

**Comment by tirumaraiselvan** [comment]
Also while we are at this, might be good to see how it relates to https://github.com/hasura/graphql-engine/issues/519

**Comment by rakeshkky** [comment]
@tirumaraiselvan 

I agree with having `pk` in field name and input argument name is redundant, so I'll rename `pk_columns` to just `columns`. I thought using `where` may be confusing since in normal mutations it is a `bool_exp` input. We can't have column inputs in the same level of update operators (_set, _inc etc.) since the column names may conflict and resolving the input arguments in the code will be much simpler (we don't need to filter out the operator names). Initially the `delete_by_pk` has the input arguments as you suggested (see comment edit history) but later in a quick offline discussion with @rikinsk we thought having a separate input argument makes it consistent with `update_by_pk`.

**Comment by tirumaraiselvan** [comment]
@rakeshkky I think, it won't be confusing because you are clearly using `_by_pk` field and that has a different `where` input arg :man_shrugging: 

This way even `delete_by_pk` becomes nicer. 

@rikinsk Thoughts?

**Comment by rikinsk** [comment]
Currently in `select_by_pk` we expect all the pk column values to be passed as inputs individually., so that format should ideally be the same for `update/delete _by_pk` requests as well. 

Considering the chance of conflicts having something like a `_key_columns` kind of input which accepts the columns involved in a key (primary or unique) makes sense to me. But that would be a breaking change so I am not sure how we should proceed. Maybe we leave the `select_by_pk` requests as it is for now and make all the new fields we introduce consistent with the new style and eventually deprecate the old `select_by_pk` style of taking column inputs.

 @0x777 can pitch in as well

**Comment by rikinsk** [comment]
Also wanted to add, that I am  a big fan of overriding `where` behaviour or overriding any existing field behaviour for that matter. Those kind of explananations and distcinctions I dont want to have to deal with in docs and support.

**Comment by tirumaraiselvan** [comment]
The chance of conflicts is only with `update` right? `select` and `delete` are fine?

Also, this kind of override is quite natural. The field and type are quite self-documenting IMHO in practice. Yes, in docs we will have to describe it but that's what you would have done for `pk_columns` also.

**Comment by rikinsk** [comment]
Summarizing the discussion from above with the suggested options:

Ways to represent key columns:
1.  - `_by_pk(col1: col-ty-1!, col2: col-ty-2!, ...)`, 
     - `_by_<uniq_key>(col1: col-ty1!, col2: colty-2!, ...)`
     - Pros
       - Looks neat for select / delete
     - Cons
       - Col names may conflict with `_set`, `_inc`, etc. in update
2. - `_by_pk(pk_columns: table_pk_columns_input! )`
    - `_by_<uniq_key>(<uniq_key>_columns: table_<uniq_key>_columns_input! )`
    - Pros
      - Col names will never conflict with `_set`, `_inc`, etc. in update
    - Cons
      - Little ugly for select / delete
      - Will be breaking change for current select queries (deprecation will need to be done sometime)
3. - Use `1. for select/delete` and `2. for update`
    - Pros
      - Looks neat for all select, update and delete
      - No breaking changes needed
     - Cons
       - Inconsistent API signature. Might be confusing.

@tirumaraiselvan @0x777 @rakeshkky Please add any other points to consider and have a quick vote on this and finalize?

**Comment by tirumaraiselvan** [comment]
I vote for 3. I think it is a minor inconsistency for which I don't want to ruin the natural API for `select` and `delete`

**Comment by 0x777** [comment]
I'm also in favour of 3. Though I'm not sure about `pk_columns` as the argument name. What happens if you the role doesn't have select permissions on the table? What will be the response type then?

**Comment by rakeshkky** [comment]
I second 3. 

@0x777 The requirement is these single row mutation should return a `<table>` object type. If there is no select permission defined, then the `<table>` object type is not generated, which also forces not to generate these mutations. 

Hence, no single row mutations are generated if select permission is not defined on the table.

**Comment by wawhal** [comment]
@tirumaraiselvan @rikinsk @rakeshkky  can we called the argument of the `update_by_pk` mutation from `columns` to `pk_columns` or just `pk`?

I understand that there's already a `pk` present in the name of the mutation; but `pk_columns` or `pk` makes instant sense just like `inc` and `set`. `columns` threw me off a bit.

**Comment by tirumaraiselvan** [comment]
@wawhal Yeah, that makes sense to me. Could call it `key` because then it works for unique fields that we might create later (https://github.com/hasura/graphql-engine/issues/519).

**Comment by rikinsk** [comment]
I would keep it as `pk_columns` & `<uniq_constaint_name>_columns`. This will ensure types wont conflict and no chance of confusion

**Comment by tirumaraiselvan** [comment]
@rikinsk `<uniq_constraint_name>` is usually long and ugly. Maybe we can just call it `uniq_columns` .

**Comment by rikinsk** [comment]
Sure. Fully qualified argument name seems excessive. I would go for `uniq_key_columns` though. `uniq_columns` sounds a little wrong to me for some reason. No strong feelings though. 

On a side note, there seems to be an alternate API signature also that we can also go for which seems to be neater in my opinion now.

With our current suggestion, a blow up of root fields can happen in case tables have lots of uniq constraints.
 e.g. `select_by_uniq_constraint1`, `select_by_uniq_constraint2`, etc. 

So instead of generating a root fields for every available uniq constraint, we can have a single  `select_by_uniq_key` mutation that takes any one of many `<uniq_constraint_name>_columns` arguments as input. ie. We generate a columns argument for each uniq constraint present and it is mandatory to pass one and only one of them (this can be enforced by server).
e.g. `select_by_uniq_key(uniq_constraint1_columns: $columns)`, `select_by_uniq_key(uniq_constriant2_columns: $columns)` , etc.

Thoughts?
