### ISSUE TITLE
Permissions rule for a many-to-many table?

### ISSUE THREAD

**Issue by spiffytech** [hasura/graphql-engine#3744]
I have users who can belong to teams, via tables `users`, `teams`, and `users_teams`. I want users to be able to enumerate other users on their teams, but not users from other teams. How can I express this with a permissions rule?

**Comment by tirumaraiselvan** [comment]
On `users` table, you can have a permission like this? 

![Screen Shot 2020-01-20 at 8 26 25 AM](https://user-images.githubusercontent.com/8663570/72699685-692a2600-3b6f-11ea-9a03-3a07cb7624c2.png)

This would have been quite trivial if you had a session-variable like `X-Hasura-Team-Id` but you may not want to have that in your auth system because you can derive it from `X-Hasura-User-Id` also.

The main idea of the rule above is to get the `team_id` of the corresponding `X-Hasura-User-Id`. This you can get by getting the `team` rows via the `users_teams` tables that satisfy the user.

**Comment by marionschleifer** [comment]
@spiffytech just checking in to see if your issue is resolved? If yes, we can close this issue 🙂

**Comment by marionschleifer** [comment]
I'm closing this issue. @spiffytech feel free to re-open if you'd like to add something 🙂

**Comment by zewa666** [comment]
Hey @tirumaraiselvan I've got a somewhat similar scenario, but this doesn't work for me as still only the user itself is listed but not others. Are you sure above example works?

**Comment by aponski** [comment]
@FroeMic I think I will not work correctly. I have similar case 

**Tables**
- users (user_id)
- workspaces (workspace_id)
- users_worskapces: pk -> ( workspace_id, user_id ) and role_id (1, 2, 3)

**Permissions for users table**
`{
    "_or": [
        {
            "id": {
                "_eq": "X-Hasura-User-Id"
            }
        },
        {
            "users_workspaces": {
                "workspace": {
                    "users_workspaces": {
                        "_and": [
                            {
                                "user_id": {
                                    "_eq": "X-Hasura-User-Id"
                                }
                            },
                            {
                                "workspace_role_id": {
                                    "_eq": 3
                                }
                            }
                        ]
                    }
                }
            }
        }
    ]
}`

**Problem**
Role id 3 means workspace admin who can see ale workspace users. When user has role id 3 assigned to one workspace in users_workspaces, unfortunately he can also see all users in other workspaces.
