### ISSUE TITLE
Postgresql If Not Exists

### ISSUE THREAD

**Issue by nrakochy** [hasura/graphql-engine#3766]
Hi there, 

Thanks for the great tool. It seems as though the `if not exists` syntax is not supported by the SQL runner. I went ahead and dropped the syntax and created the table correctly, but perhaps this is useful information. 

1) Go to Data > SQL
2) Attempt to create a table 
```
CREATE TABLE IF NOT EXISTS article_tag (
  article_id INT
  tag_id INT
  PRIMARY KEY (article_id, tag_id)
)
```
3) Error

<img width="1114" alt="Screen Shot 2020-01-23 at 11 43 16 AM" src="https://user-images.githubusercontent.com/3740177/73009719-b0feb680-3dd6-11ea-96be-f74c68d0c464.png">

**Comment by rikinsk** [comment]
The regex for parsing create statements to execute the `Track this` request which is present [here](https://github.com/hasura/graphql-engine/blob/27910004752e430dbe6c4607f4e3f50e6c198c02/console/src/components/Services/Data/RawSQL/utils.js#L1) needs to be fixed

**Comment by mrsupiri** [comment]
I am interested in solving this issue, Does Hasura server has an endpoint to check if the table already exists? or should I just escape "IF NOT EXISTS" from the query?

**Comment by rikinsk** [comment]
@mrsupiri You need to update the regex defined [here](https://github.com/hasura/graphql-engine/blob/27910004752e430dbe6c4607f4e3f50e6c198c02/console/src/components/Services/Data/RawSQL/utils.js#L1) to handle the case where "IF NOT EXISTS" is present in the query.

**Comment by mrsupiri** [comment]
yeah, I went through the code and I have a basic understanding of how it works, I just want to know how should I handle `"IF NOT EXISTS"` in the query. Should I just update that [createSQLRegex](https://github.com/hasura/graphql-engine/blob/8a9901d417c1cde1e74744188779ad179c190120/console/src/components/Services/Data/RawSQL/utils.js#L1) so that it will ignore `"IF NOT EXISTS"` from the query and let the existing code handle the rest? 
Because for my understanding [`Endpoints.rawSQL`](https://github.com/hasura/graphql-engine/blob/02d13ba1642ddb3555a8cea14c20397bf14c49d9/console/src/components/Services/Data/RawSQL/Actions.js#L46) don't accept RAW SQL and I can't find another way check if the table already existing in the given schema.

**Comment by rikinsk** [comment]
@mrsupiri You just need to update the regex. As you mentioned the rest of the code shall handle the edge cases.
