### ISSUE TITLE
optimise count query in browse rows page to account for really large tables

### ISSUE THREAD

**Issue by rikinsk** [hasura/graphql-engine#3793]
The row count query currently being made on browse rows page can be quite slow to run in case a table has miliions of rows. A more optimised query needs to be used.

**Comment by rikinsk** [comment]
As a step 1. The count query and the get page results query can be decoupled. ie. display the page results even though the count query takes a long time.

**Comment by wawhal** [comment]
Let's implement what @rikinsk suggests in the above comment. Should be good enough for now.
The counter itself can be a separate component that maintains its state and can show a spinner while the query is in progress.

**Comment by beerose** [comment]
What about using [count estimate](https://wiki.postgresql.org/wiki/Count_estimate)?
Table plus, for example, uses this instead of the exact count. 

Here go some comparison:

Number of rows | count(*) | SELECT reltuples | Notes
-- | -- | -- | --
1 000 000 | 47ms | 1ms |  
2 000 000 | 66ms | 1ms |  
5 000 000 | 136ms | 1ms |  
10 000 000 | 316ms | 1ms | Estimated ~7 000 000, still fast in console
20 000 000 | 461ms | 1ms | Estimated ~18 000 000, still pretty fast in console
30 000 000 | 850ms | 1ms | Estimated ~25 000 000
35 000 000 | 12005ms | 3ms | Estimated ~32 000 000
50 000 000 | 2379ms | 7ms | Estimated ~48 000 000

**Comment by rikinsk** [comment]
The ideal behaviour I would like is that for small tables the count is accurate but for larger tables we display an estimate. 

Can we confirm how accurate the count estimate is for small tables (say less than 1,000,000 rows) and if there is a smart way to switch between the two queries. e.g. check if count is > a million and if so use the estimate query instead of exact count.

Also we will have to think what to do about pagination when we use the estimate count.

**Comment by tirumaraiselvan** [comment]
Something that I felt was needed in our SQL APIs (and graphql APIs) was using `statement_timeout`: https://www.postgresql.org/docs/9.4/runtime-config-client.html

This way if an execution fail with timeout then you can retry it with cheaper query.
