### ISSUE TITLE
Tracking a large number of tables in a single metadata load query is slow / doesn't work

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#3802]
Replicate:

1. Running hasura/graphql-engine:v1.1.0-beta.2
2. Load this sample schema in postgres (sample.sql.txt).
3. Import the attached metadata json
 (big-metadata.json.txt)

[big-metadata.json.txt](https://github.com/hasura/graphql-engine/files/4133275/big-metadata.json.txt)
[sample.sql.txt](https://github.com/hasura/graphql-engine/files/4133276/sample.sql.txt)

Note: This doesn't affect GraphQL performance for a large number of tables, just the initial metadata load for tracking new tables.

**Comment by coco98** [comment]
For now, this script might serve as a good workaround: https://gist.github.com/coco98/2a65f9fe8c1c0f5e4bee92d8cb66bc4c

**Comment by tirumaraiselvan** [comment]
Using the `sample.sql.txt` attached in the first comment, I also tried to do a bulk track which also took a very long time.

This script generates a bulk query: [track.js.txt](https://github.com/hasura/graphql-engine/files/4318647/track.js.txt)

What I noticed was that Postgres was at max capacity for the entirety of the bulk query, it seemed odd because I would have expected about 100 queries (for 100 tables) to have been executed and that shouldn't have caused so much load on Postgres.

**Comment by lexi-lambda** [comment]
I took a (very) brief look at the `replace_metadata` code just now, and it turns out my understanding of the way the code works was incorrect. I thought that it worked like this:

  1. Drop all the existing metadata from Postgres.

  2. Store the new metadata information into Postgres, without touching graphql-engine’s schema cache.

  3. Rebuild the schema cache.

It turns out that’s only *partially* true. For some resources, like relationships and computed fields, it does work that way, but for others, like tables and functions, it does the equivalent of an ordinary `track_table`/`track_function` API call. That means the schema cache *is* rebuilt for each and every added table, and it’s not at all surprising that’s slow.

Having learned that, the fix should not be hard: just fix the `replace_metadata` API to be consistent about how it persists the new metadata objects. That should make it nice and zippy!

**Comment by coco98** [comment]
Do we have a theoretical understanding on which one of these 2 would be faster based on their codepaths:
1. Bulk query to track 20 relationships
2. Replace metadata that has the 20 relationships

---------------- 

There are a few roadmap things to consider here. 

1. The new Hasura CLI encourages replace_metadata
2. Do we want console to move towards a more replace_metadata style workflow too?

Larger question: How does a  "bulk metadata request with a few metadata changes" compare to a "replace metadata" call in different scenarios?

**Comment by lexi-lambda** [comment]
> Do we have a theoretical understanding on which one of these 2 would be faster based on their codepaths

`replace_metadata` is, in my mind, unequivocally better than `bulk` from an efficient implementation point of view.

`bulk` is hard to make fast without a lot of work because its semantics is overspecified. It guarantees that everything is executed in order, top to bottom. That means that if a single `bulk` query tracks a table, then untracks that same table, we can’t easily optimize away the operations because some other step might depend on the transient table being there.

`replace_metadata`, on the other hand, is much nicer: it just specifies an end state, and it defers to graphql-engine to figure out how to get there.

Of course, `replace_metadata` has its own problems:

  1. The user has to specify the entire desired end state. This is good for a migrations workflow, but less good for the console, which incrementally modifies the metadata.

  2. Even if the change is very small (like tracking a new relationship), our naïve implementation will still drop and replace everything. A better approach would be to implement some kind of diff-and-patch, but that might not be worth the effort in the short term.

A solution to both these problems is to implement a `patch_metadata` API, which specifies a patch to apply directly. And if we want to optimize `replace_metadata` further in the future to do the diff-and-patch approach, we can do that in a nice way by internally translating `replace_metadata` calls to `patch_metadata` calls after doing the diffing.

**Comment by coco98** [comment]
@lexi-lambda This is good news! Another quick question: if a bulk query was composed of a bunch of run_sqls and a final replace_metadata/patch_metadata at the end, that could still be optimised right?

@rikinsk and @wawhal  and @0x777 and i also had some thoughts that for the console to have the entire metadata available in local state which is modified by user actions and then sent to the server is not a bad idea. Because console state management is hard and reads and writes dealing with the entire metadata object is not a bad thing for the console anyway.  

The reads/writes underneath can be sent as patches to make the upload more efficient I’m guessing.

**Comment by lexi-lambda** [comment]
> This is good news! Another quick question: if a bulk query was composed of a bunch of run_sqls and a final replace_metadata/patch_metadata at the end, that could still be optimised right?

Yes. The slowness is in the repeated, non-batched metadata queries, so as long as those queries are batched together, performance will be improved.

It’s worth noting that, theoretically, we could try and get these performance advantages with the current API. We could do some fancy analysis of a `bulk` query to find strings of consecutive metadata queries that we can be confident won’t conflict, and we could batch them together automatically, behind the scenes. But I thought about how hard that would be a while back, and I determined it’s almost certainly not worth the effort, especially since I think the alternate API is nicer to use, anyway.

So as with all optimizations, this is really about trying to find an interface that naturally lends itself to a fast implementation for realistic use cases. In this case, that means avoiding too many metadata queries that need to be isolated from one another.

**Comment by jberryman** [comment]
I don't know this part of the codebase very well, but maybe I should look again at this: https://github.com/hasura/graphql-engine/issues/4039 . When I filed the ticket I thought I'd triaged and determined the issue was indeed with `replaceMetadataToOrdJSON`, but later it seemed the arbitrary instance was what was actually slow...
