### ISSUE TITLE
Use local assets instead of CDN

### ISSUE THREAD

**Issue by rgtk** [hasura/graphql-engine#3825]
Console web interface of `hasura/graphql-engine` Docker image sends requests to `graphql-engine-cdn.hasura.io` host for Javascript and CSS.

This is dangerous: it compromises both security and privacy. These files [are bundled with the Engine](https://github.com/hasura/graphql-engine/tree/6ef0b4dfdf560dc49694d7ae872ea82c0b4d9096/console) so there is no reason to fetch it from external sources.

**Comment by rikinsk** [comment]
This is intentional to allow rolling updates to the console to resolve minor bugs (as the console is not in the critical path of serving GraphQL requests), You can choose to use local assets if you wish by using the configuration mentioned [here](https://docs.hasura.io/1.0/graphql/manual/deployment/graphql-engine-flags/config-examples.html#run-console-offline-i-e-load-console-assets-from-server-instead-of-cdn)

**Comment by rgtk** [comment]
Thanks for pointing me to solution to resolve this issue. Easy enough.

I feel, however, using local assets should not be a default behavior. Although Console is not in critical path of serving GraphQL request, JavaScript running in Console can serve those request with necessary authentication. Ergo, malicious code in Console could manipulate and spy when user simply uses the Console with CDN assets.

I would like to propose using local assets by default, mitigating above security issue.

**Comment by praveenweb** [comment]
Since it's configurable to use local assets, the default behavior to fetch the resources from the CDN benefits for rolling updates (which includes security fixes too) and for the convenience of upgrading server versions.

Closing this one.
