### ISSUE TITLE
column names that don't conform to the GraphQL naming spec don't show up in the GraphQL schema

### ISSUE THREAD

**Issue by Johnb21** [hasura/graphql-engine#3827]
**Version: 1.1.0-beta.2**

If I have a legacy column name that doesn't conform to GraphQL naming conventions on an existing Postgres Database (Employee Name), when I try to Table->Modify and edit the column to use a graphql friendly name under the GraphQL field name - I get an error that my column is used in an existing Trigger. However, there is no way for me to NOT track the triggers to avoid this issue.

Are there any known work arounds for this? It is one of my biggest roadblocks for being able to move forward.

**Comment by tirumaraiselvan** [comment]
Similar issue for table names is here #3811

**Comment by Johnb21** [comment]
@tirumaraiselvan that is also by me. However, this issue is related to column names and not the table name. I cannot alias the column names when the column name doesn't conform to graphql standards AND the column name exists in a trigger. The way the introspection works appears to auto introspect the triggers and track them without an option to track/untrack which makes it impossible to alias them using the interface when they belong to triggers.

**Comment by tirumaraiselvan** [comment]
Hi @Johnb21 

Hasura does not track anything (tables or functions) automatically so I might need more details here. Is it possible for you to share the screenshot of the console Data page where it shows all tables and functions (both tracked and untracked)? Is it possible for you to tell what is the trigger that is causing the issue (maybe give a sample definition?) when you are changing the GraphQL field name for a column?

Having said that, if you do have a function that is tracked which is dependent on a table (because its return type is `SETOF <table>`) , then you will need to untrack the function first and then untrack the table to keep the metadata consistent. We can definitely improve the UX here by giving an option to `cascade` dependents.

**Comment by tirumaraiselvan** [comment]
Closing this as support for this exists via `set_table_customization` or `set_table_custom_fields` API (and console)
