### ISSUE TITLE
Add custom permission check to update operation on the changed data

### ISSUE THREAD

**Issue by techninja1008** [hasura/graphql-engine#384]
Currently, on the permissions check on an update operation, the check is only run on the row *before* it is modified. It would also make sense to add a check to make sure that the modification is valid.

*Example use case*:

1. You have a table of users and a table of (for example) cars.
2. Each car has a reference (with a foreign key constraint) to a car.
3. You want users to be able to update their car entries using criteria including the user_id, so you allow them access to it on the update permission.
4. Currently: You have a problem, as they can now change the user_id column to someone else, when the application was designed for other users to be completely invisible.
    
    With suggestion: You add a check so that the user_id field *after modification* must still equal X-HASURA-USER-ID, and everything works fine.

**Comment by coco98** [comment]
@techninja1008 If I understand correctly, I have a feeling this can be solved with the current permissions. The update check permission will only allow update operations only on columns where the user_id is x-hasura-user-id and then you'll also have to remove the user_id column from being updatable?
<img width="1038" alt="screen shot 2018-09-09 at 3 10 58 pm" src="https://user-images.githubusercontent.com/131160/45263209-b5753a00-b442-11e8-9308-cc8945e68e80.png">

I've setup a heroku app without any access-key that you can do something on and share with me to illustrate better if I haven't understood well:
https://permissions-test.herokuapp.com/console

On another note, @0x777 I think there's an overlap with this https://github.com/hasura/graphql-engine/issues/216.

**Comment by techninja1008** [comment]
@coco98 Yes, this particular example (Not that great) can be solved with that, but lets say you also have a mileage counter on the cars table and you want to make sure that it can only be positive. A slightly more advanced example would be that you can only increase it.

**Comment by coco98** [comment]
@techninja1008 Hm...gotcha. We can think about this!

A current workaround would be to use postgres check constraints https://www.postgresql.org/docs/current/static/ddl-constraints.html.

However, the problem is that those constraints are applied for all hasura permission roles.

**Comment by spiffytech** [comment]
The suggestion of making `user_id` non-updatable works, but makes my code more complicated since I have to strip the id out of my `variables` objects in all of my GraphQL mutations. I'd much rather be able to pass the original object through to the GraphQL Engine and have it just reject if the modified row violates the permissions.

**Comment by pnappa** [comment]
Another solution is to provide two degrees of permission checks for updates. 

One being a check on the current state of the row being updated (this is what the permission check currently does).

The other being a check on the updating data (i.e. checking constraints on the inserting row).

My use case is pretty similar to the one above - I want to restrict one role to only being able to set a column to a subset of an enum's values, whilst another role can set them to another subset of the enum values. In this case, an SQL constraint isn't possible for this value, and _set doesn't work, because they may update other columns within the table without touching the enum column.

**Comment by paf31** [comment]
[Here](https://github.com/paf31/graphql-engine/pull/1) is a small change which checks the conditions based on the _insert permissions_, based on the new data _after_ an update mutation.
