### ISSUE TITLE
hdb_views.role__insert__schema__table remain in db after upgrading to v1.1.0

### ISSUE THREAD

**Issue by Mike96Angelo** [hasura/graphql-engine#3940]
After upgrading to v1.1.0, I was trying to drop a column and came across this error:
```
PostgreSQL said: cannot drop table "MyTable" column "MyColumn" because other objects depend on it
Detail: view hdb_views."role__insert__public__ MyTable" depends on table "MyTable" column "MyColumn"
Hint: Use DROP ... CASCADE to drop the dependent objects too.
```

I saw that these views were removed here:  https://github.com/hasura/graphql-engine/pull/3598

Note: I am NOT using Hasura for db migrations.

**Comment by lexi-lambda** [comment]
I think the issue here is that #3598 removed the code that creates/manages those views, but it didn’t clean them up as part of the migration. We should add a migration in a future release to clean up any lingering views that people might have in their databases, but as a workaround, it should be totally safe to drop the view yourself (or use `DROP ... CASCADE`).
