### ISSUE TITLE
hidden popover

### ISSUE THREAD

**Issue by jjangga0214** [hasura/graphql-engine#3960]
A part of popover is hidden.

![Screenshot from 2020-02-26 23-02-22](https://user-images.githubusercontent.com/28584151/75351819-179e5500-58ec-11ea-8b9a-9e6e01f6c6d7.png)

Though I think people would guess what it means, anyway leaving an issue :)

**Comment by sahil9001** [comment]
@beerose I want to work on this issue!

**Comment by sahil9001** [comment]
@beerose I guess I asked a question in the comment?

> Also can you provide steps to reproduce this issue?

**Comment by beerose** [comment]
There are two ways to reproduce this:

1. Run `graphql-engine` server in a beta version. Then you'll see this banner in the console.
2. Make it temporarily visible in the UI for the purpose of the solving issue. Specifically, you want to do this in these two places:
    * https://github.com/hasura/graphql-engine/blob/master/console/src/components/Main/Main.js#L316
    * https://github.com/hasura/graphql-engine/blob/master/console/src/components/Main/Main.js#L349
  
    You'd need to get rid of conditional renders.

**Comment by sahil9001** [comment]
Okay @beerose thanks for your help!

**Comment by beerose** [comment]
Hi @sahil9001!

The component with this bug was removed in recently merged [PR](https://github.com/hasura/graphql-engine/pull/5070), and hence the issue was resolved.
I hope you can find some other interesting [Hacktoberfest issue](https://github.com/hasura/graphql-engine/issues?q=is%3Aopen+label%3Ahacktoberfest+label%3Ac%2Fconsole). I'd be happy to help if you have any questions.

I'm therefore closing this issue as it was solved by https://github.com/hasura/graphql-engine/pull/5070.
