### ISSUE TITLE
Reloading metadata for a schema seems broken on 1.1.0

### ISSUE THREAD

**Issue by michaelhayman** [hasura/graphql-engine#3983]
I have a docker-compose file with a node remote schema, postgres and hasura in it.

I start up all the services, but sometimes the api doesn't start in time for hasura; so I issue a separate command to reload metadata.  This works just fine on 1.0.0, but on 1.1.0 no matter how many times I reload metadata, it doesn't work.  I know for sure the hostname is correct, can ping it from the hasura docker container, and what's more, if I *delete* the metadata and re-add it, everything is peachy.

I think something is wonky with metadata reload, somehow it's not pinging the remote schema properly.

Is this a known issue with 1.1.0?  If not then I'll do more testing and post more info.

<img width="811" alt="Снимок экрана 2020-02-29 в 16 26 03" src="https://user-images.githubusercontent.com/1134239/75607678-113df200-5b13-11ea-9947-92287131f933.png">

^ after deleting this entry and readding it, everything works, without me changing the API whatsoever

**Comment by michaelhayman** [comment]
(I also had to downgrade to 1.0.0 because this bug breaks my workflow)

**Comment by michaelhayman** [comment]
Disregard, I think this was my fault,s omething changed with introspection.

**Comment by michaelhayman** [comment]
This actually seems like a regression.

I now need to start the remote schema before Hasura is up, otherwise no matter how many times I refresh, there's an error.

I have remote-schema, postgres and hasura in one docker-compose file.

If I fully start the remote schema (i.e. `docker-compose up remote-schema -d`) before I start Hasura (i.e. `docker-compose up` afterwards), everything works.

But 'reload' no longer works, it just says there's an HTTP error.  Introspection & playground are both enabled on remote schema.

I've tried this several times now and I'm confident that's there's a regression there in 1.1.0.

Let me know if you need any other guidance to reproduce.

**Comment by tirumaraiselvan** [comment]
@michaelhayman Can you try the `reload_remote_schema` api: https://hasura.io/docs/1.0/graphql/manual/api-reference/schema-metadata-api/remote-schemas.html#id3

I think this is the expected behaviour since `reload_metadata` does not refresh remote schemas. We have an issue for this here: https://github.com/hasura/graphql-engine/issues/3792

**Comment by michaelhayman** [comment]
Thanks, makes sense. Would definitely be cool to have an option to reload the schema there too; I guess it was just coincidence that it worked in prior versions.

Closing for now since it's tracked elsewhere.

**Comment by tirumaraiselvan** [comment]
@michaelhayman Turns out `reload_remote_schema` had a slightly more tricky behaviour and this indeed leads to a bug: https://github.com/hasura/graphql-engine/issues/4117

This bug wasn't present in v1.0.0 becaus `reload_metadata` would try to fix inconsistent metadata (but not refresh non-inconsistent remote schemas).
