### ISSUE TITLE
On Event Retries, is Order of Delivery guaranteed?

### ISSUE THREAD

**Issue by gunar-gessner-qatalog** [hasura/graphql-engine#4043]
If there are two events, which happened in this chronological order: A first, then B. If A fails, will B wait while we retry to deliver A?

**Comment by tirumaraiselvan** [comment]
Hi @gunar-gessner-qatalog 

Event Triggers do not guarantee in-order deliveries. This is because delivering events over HTTP and maintaining order does not scale e.g. if you wait for each event to be acknowledged then it puts high pressure on the backlog of events, what do you do about retries, etc?

PS: Event Triggers follows the [Event Streaming](https://pivotal.io/event-streaming) architecture pattern. You can implement many solutions based on this. For e.g. your event handlers can be made idempotent so that the order doesn't matter.

**Comment by tirumaraiselvan** [comment]
Hey @gunar-gessner-qatalog , I am closing this issue - feel free to re-open it if you have further questions.
