### ISSUE TITLE
cli: read env vars from .env file

### ISSUE THREAD

**Issue by Maxvien** [hasura/graphql-engine#4129]
The scope of this issue has changed. See the comments below.
---
Hi there!

I don't want to load `endpoint` and `admin-secret` from `config.yaml`. I want to load them from `.env` so I created a `npm script` like this:

`"console": "env-cmd hasura --project app console --endpoint $HASURA_GRAPHQL_ENDPOINT",`

However it doesn't work without an empty `config.yaml`.

Even this command doesn't work.

`hasura console --project app --endpoint https://my-graphql-engine.com --admin-secret adminsecretkey`

So think we should fix this bug for not using `config.yaml` cases.

Thank you!

**Comment by Maxvien** [comment]
I think we should let hasura-cli read env variables from `.env` like docker-compose like this.


```
# config.yaml
endpoint: ${HASURA_GRAPHQL_ENDPOINT}
admin-secret: ${HASURA_GRAPHQL_ADMIN_SECRET}
```

**Comment by shahidhk** [comment]
I am changing the scope of this issue to add support for `.env`. Making the cli work without `config.yaml` is tracked at #1558

**Comment by shahidhk** [comment]
I think we can just use https://github.com/joho/godotenv and automatically get everything in `.env` as env vars. We will just need to call the load function at the first entrypoint itself, before viper is initialised etc.

I'd prefer not to depend on `config.yaml` opening up the opportunity to get rid of that later.

**Comment by scriptonist** [comment]
Just to add my two cents, I think we can also get away with using [viper](https://github.com/spf13/viper) itself, since It supports reading from `dotenv` files as well.
- https://pkg.go.dev/github.com/spf13/viper?tab=doc#pkg-variables 
- https://github.com/spf13/viper/blob/e34fb51dd7c8546211df464b3f0b11bae80c8468/viper.go#L1490

**Comment by ShraddhaAg** [comment]
Ah, I think only one configuration file can be accessed by a single viper instance. It mentions [here](https://github.com/spf13/viper/tree/e34fb51dd7c8546211df464b3f0b11bae80c8468#reading-config-files)
`Viper can search multiple paths, but currently a single Viper instance only supports a single configuration file.`

**Comment by scriptonist** [comment]
Got it, then maybe we should proceed as @shahidhk suggested.

**Comment by adventurini** [comment]
> I am changing the scope of this issue to add support for `.env`. Making the cli work without `config.yaml` is tracked at #1558
> 
> There are two ways to do this.
> 
> 1. Read env vars as is from `.env` and export them for the run.
> 2. Use the values defined in `.env` as substitutes in config.yaml (as mentioned in [#4129 (comment)](https://github.com/hasura/graphql-engine/issues/4129#issuecomment-604810221))
> 
> I prefer (2) since it gives me more control in defining my config. I can just have `ADMIN_SECRT=xxxx` in `.env` and use it in `config.yaml` as `admin_secret: ${ADMIN_SECRET}`. Can we actually substitute any environment variable in config.yaml? Or does it have to be in `.env` file?
> 
> Docker-compose CLI tools does something like this. It might be worth exploring how they do it.
> 
> Another point to consider is how this will change if we implement #1558 where we actually get rid of the config.yaml file.

This issue seems to have closed, but it's unclear in the docs and in the issue resolution whether option #2 was implemented. Although I cannot get option #2 to work, it is still unclear whether it is supposed to work or not.

Having the ability to read from environment variables, but still requiring the config.yaml file is a not a very straightforward developer experience. I feel like your second option could clear this confusion up a bit.
