### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by rohanmuplara** [hasura/graphql-engine#4160]
I am building a sass application. For each potential customer, I want them to them to have an admin and each admin to allow different roles for their customer. It seems like something like auth0 can not easily be integrated with hasura to have this functionality.  Additionally, I was wondering what the best way to integrate with something like https://workos.com/.

**Comment by rohanmuplara** [comment]
Any help here

**Comment by tirumaraiselvan** [comment]
@rohanmuplara This can be achieved at the authorization layer ( in hasura) rather than the authentication layer (in auth0). This means that you can model permissions in Hasura to allow for such capability. 

For e.g. let's call the admin for each potential customer as "account manager". You can have a table called `account_managers` and create a relationship with `customers` table to get all potential customers for an account manager. Similarly, you can create a reverse relationship from `customers` to `account_managers`.

Now, since your customers need different roles, you can have a `customer_roles` table which has `customer_id` and their corresponding `role`.  You can have only ONE role called "user" and give insert/update permissions on this table with the rule that it can only affect rows for which `customer_roles.customer.account_manager_id = x-hasura-user-id` i.e. customers for which the `x-hasura-user-id` is an account manager.  I think the Auth course [here](https://hasura.io/learn/graphql/hasura-auth-slack/introduction/) has a similar model where a workspace admin can create different roles for regular users.

The job of authentication system then simply lies in giving the user role and x-hasura-user-id. You can see this [guide](https://hasura.io/docs/1.0/graphql/manual/guides/integrations/auth0-jwt.html#guides-auth0-jwt) for a reference of integrating with Auth0.

**Comment by praveenweb** [comment]
@rohanmuplara - Hope the above approach helps. Feel free to re-open the issue if you have any more questions.
