### ISSUE TITLE
track functions that return a single row

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/graphql-engine#4299]
Currently, Hasura can track functions whose return type is `SETOF table_name` : https://hasura.io/docs/1.0/graphql/manual/schema/custom-functions.html#supported-sql-functions

We can extend this to functions that return just a row type `table_name`.

**Comment by adamrneary** [comment]
This seems like a big win for the scenarios of querying for `me` or `myOrg`. It would be fairly foundational to multi-tenant applications. Strictly relying on Authorization for filtering feels like a weak solution because admin users might have access to rows not in their org, but still want to query just for rows associated with their org. Starting the query with myOrg would allow that:
```graphql
query { 
  myOrg {
    users {
      id
    }
  }
}
```

I hope this gets picked up! It would be really valuable! Thanks!

**Comment by zhammer** [comment]
ha @adamrneary makes a good point. i just found this issue looking for a better way to implement `me`.

i have the following function. ideally `me` would return a user object or null, not a list of users
```sql
CREATE
OR REPLACE FUNCTION public.me(hasura_session json) RETURNS SETOF users LANGUAGE sql STABLE AS $ function $
SELECT
  *
FROM
  users
WHERE
  id = (hasura_session ->> 'x-hasura-user-id') :: int $ function $
```

**Comment by lukeramsden** [comment]
Trying out Hasura for the first time, and this is the first thing I'm missing from Postgraphile:

```sql
/* Returns user from JWT Claim */
create function app_public.current_user() returns app_public.users as
$$
  select users.* from app_public.users where id = app_public.current_user_id ();
$$
language sql stable cost 100000;
comment on function app_public.current_user() is E'The currently logged in user (or null if not logged in).';
```

```gql
"""The root query type which gives access points into the data universe."""
type Query {
  """The currently logged in user (or null if not logged in)."""
  currentUser: User
}
```

**Comment by bitjson** [comment]
Hey @codingkarthik, is there a commit where this issue was solved? 

This would really help to clean up my application's API.

I ran into an unusual case where using the standard Hasura relationships is not possible – I'm tracking several views which derive data from a very expensive to generate view (a recursive query which runs against a >100GB table). I've been able to set up relationships between existing tables and these views with great API performance, but as soon as I want to query a property inside an object returned by, e.g. an array relationship of the expensive view, the SQL produced by Hasura would require scanning the full, expensive view (no matter how high I set the COSTs).

I'm able to work around this issue nearly-perfectly with computed fields, though. Instead of adding a relationship from a field of the expensive view to another table, I simply added a computed field which does the lookup manually:
```sql
CREATE FUNCTION authchain_migration_transaction(authchain_migration_row authchain_migrations_view) RETURNS transaction
  LANGUAGE sql IMMUTABLE
AS $$
  SELECT * FROM transaction WHERE internal_id = $1.migration_transaction_internal_id LIMIT 1;
$$;
COMMENT ON FUNCTION authchain_migration_transaction (authchain_migrations_view) IS 'This function powers the "transaction.authchains[n].migrations[n].transaction" computed field in migration objects. This is a workaround to improve performance over an equivalent "transaction" standard Hasura relationship. When implemented as a relationship, the Hasura-compiled SQL query requires a full scan of the authchain_migrations_view, which is extremely large and expensive to compute.';
```

This works almost perfectly, however the result returned by Hasura is an array (of length 1) rather than an object:
```gql
query GetAuthheads {
  transaction(
    where: {
      internal_id: {
        _eq: "167243311"
      }
    }
  ) {
    internal_id
    authchains {
      migrations {
        migration_index
        transaction {
          internal_id
        }
      }
    }
  }
}
```

Returns (note the `[]` around each `transaction` object):
```json
{
  "data": {
    "transaction": [
      {
        "internal_id": 167243311,
        "authchains": [
          {
            "migrations": [
              {
                "migration_index": 0,
                "transaction": [{ "internal_id": 167243311 }]
              },
              {
                "migration_index": 1,
                "transaction": [{ "internal_id": 172962140 }]
              }
            ]
          }
        ]
      }
    ]
  }
}
```

When it should return (without the array):

```json
{
  "data": {
    "transaction": [
      {
        "internal_id": 167243311,
        "authchains": [
          {
            "migrations": [
              {
                "migration_index": 0,
                "transaction": { "internal_id": 167243311 }
              },
              {
                "migration_index": 1,
                "transaction": { "internal_id": 172962140 }
              }
            ]
          }
        ]
      }
    ]
  }
}
```

Is there some why to configure this computed field to return an object rather than an array here?

**Comment by esseswann** [comment]
@tirumaraiselvan 
I wonder is it possible to have a nullable return from such a generic function?
```sql
CREATE OR REPLACE FUNCTION public.me(hasura_session json)
 RETURNS "user"
 LANGUAGE sql
 STABLE
AS $function$
select
  *
from
  "user"
where
  id = (hasura_session ->> 'x-hasura-user-id') :: uuid
$function$
``` 
so for example if user is unathorized we return
```json
{ "me": null }
```

**Comment by RubenVanEldik** [comment]
I would love to know why this issue was closed. Just like @bitjson this is one of the first issues that I ran into using Hasura.

Having a computed column that returns a single row in the form of an object instead of an array (e.g. for a `me` relationship) seems quite fundamental for many applications.

**Comment by tirumaraiselvan** [comment]
@RubenVanEldik This issue was for functions tracked as root fields. For computed fields, we have this issue: https://github.com/hasura/graphql-engine/issues/6562

**Comment by RubenVanEldik** [comment]
Hi @tirumaraiselvan, Thank you for your quick response! But as far as I can see this feature has not yet been implemented in Hasura, right? 

I would love to have a `me` root field for all users, but I can't seem to get it working.

**Comment by esseswann** [comment]
@RubenVanEldik It's supported since [v2.0.0-alpha.1](https://github.com/hasura/graphql-engine/releases/tag/v2.0.0-alpha.1)

**Comment by RubenVanEldik** [comment]
That's so cool, I totally missed that! Thanks @esseswann!

**Comment by RubenVanEldik** [comment]
How can I track a function that returns a single row?

This function returns an array of users

```sql
CREATE
OR REPLACE FUNCTION public.me(hasura_session json) RETURNS SETOF users LANGUAGE sql STABLE AS $ function $
SELECT
  *
FROM
  public.users
WHERE
  id = (hasura_session ->> 'x-hasura-user-id') :: uuid;
$ function $
```

And I can't track this function (I'm running `v2.0.8`):

```sql
CREATE
OR REPLACE FUNCTION public.meoo(hasura_session json) RETURNS users LANGUAGE sql STABLE AS $ function $
SELECT
  *
FROM
  public.users
WHERE
  id = (hasura_session ->> 'x-hasura-user-id') :: uuid;
$ function $
```

**Comment by esseswann** [comment]
@RubenVanEldik 
Correct, you shouldn't use SETOF
What error exactly does it return? Did you try a hack with tracking the function not through the console but through API?

**Comment by RubenVanEldik** [comment]
It doesn't throw an error. The second function just doesn't show up in the console. I just tried to add it via the API, and that works!! 🎉  So it's just not yet implemented in the console yet.

Many thanks for the help!

(for those interested in doing this via the API, below is the body you want to send to `/v1/query`)

```json
{
  "type": "track_function",
  "args": {
    "schema": "public",
    "name": "me"
  }
}
```

**Comment by matiasf9** [comment]
This has not been solved for Relay API, it still returns a **me_connection** with edges and nodes and a single result. Are there any plans to fix it?

**Comment by franciscolourenco** [comment]
Do you have an example use case for tracking a function which returns a single item, besides the example of returning the current user?

What are the advantages of using such a function compared to selecting the user from the users table?

Cheers!

**Comment by ntziolis** [comment]
For anyone finding this: This now also works through the console. When doing so its important to explicitly set the session argument value.
