### ISSUE TITLE
`created_at` magic fields to have UTC normalization

### ISSUE THREAD

**Issue by rrjanbiah** [hasura/graphql-engine#4616]
I'm not sure if it is possible to normalize the time to UTC. Currently it is saving in system timezone. So, showing time in client looks difficult or confusing.

**Comment by leoalves** [comment]
Hi @rrjanbiah,

`timestampz` fields in PostgreSQL are always saved in UTC.  You need to change the settings in your connection to show dates in UTC, instead of the server timezone.

To do that, in the Hasura console SQL tab run the following command:

```SQL
SET TIMEZONE TO 'UTC';
```

This will change only for the Hasura connection.  If you wish to change it for all databases and all sessions you will need to change the `postgresql.conf` file.  There should be a timezone option just uncomment it and change to:

`timezone = 'UTC'`

Thanks

**Comment by rrjanbiah** [comment]
@leoalves Thank you so much. Would be better if this is documented somewhere. Thanks again.
