### ISSUE TITLE
Cannot insert a row containing a point type

### ISSUE THREAD

**Issue by MohiuddinM** [hasura/graphql-engine#4635]
I am using the console to insert a row into a table containing geometric point type. I get the following error: 

`invalid input syntax for type point: "{ "type": "Point", "coordinates":[12.9743387, 77.6030891] }"`

**Comment by ShahAnuj2610** [comment]
@MohiuddinM I don't think it's a bug. As per `POSTGRES` docs, the points syntax should be either `(12.9743387, 77.6030891)` or `12.9743387, 77.6030891` and I tried with both of them and it works.

![](https://i.imgur.com/n7mihSj.png)

Docs: https://www.postgresql.org/docs/current/datatype-geometric.html#id-1.5.7.16.5

cc: @rikinsk

**Comment by rikinsk** [comment]
The issue here is that the console stringifies the point definition instead of passing it on as an object. Console needs to do a better job of figuring out when to stringify input and when to not.

**Comment by beerose** [comment]
As @ShahAnuj2610 noticed, the values that can be inserted for a _geometric_ point must be of syntax `(x, y)` or `x, y`. 
Whereas `{ "type": "Point", "coordinates":[12.9743387, 77.6030891] }` is a _geographic_ point (`geography` type in the console). 

The issue here seems to be confusion between _geometric_ and _geographic_ point. 

Closing the issue, please reopen if you notice any other bad behaviors with the point data type.
