### ISSUE TITLE
Built-in authentication

### ISSUE THREAD

**Issue by luke-j** [hasura/graphql-engine#4659]
Authentication seems to be a extremely common addition to hasura. There’s several userland approaches to both webhook and JWT authentication, each taking slightly different approaches to auth. 

Will hasura ever consider incorporating a built-in authentication layer?

**Comment by coco98** [comment]
@luke-j For now there aren't any plans to bundle authentication along with Hasura. With actions it is quite easy to put together a set of basic login/logout/forgot-password endpoints.

Our main reason for not adding authentication is because of the sheer amount of diversity that folks have in their authn setup. Especially for our enterprise users, packaging in authentication is not useful since they have existing authentication setups. 

We'll keep improving our docs to make sure that adding basic authentication is super easy, but we won't officially bundle authn any time soon.

Feel free to reach out here or on discord (https://discord.gg/hasura) or on stackoverflow if you need any help integrating authentication with Hasura!
