### ISSUE TITLE
Is there a way to reference a nested object value at the root level?

### ISSUE THREAD

**Issue by Aditya94A** [hasura/graphql-engine#4767]
I simply want

```
"numRows": 10
```

in my response, however, hasura's aggregate method is this:

```
    numRows: mytable_aggregate {
      aggregate {
        count
      }
    }
```

which leads to the response
```
        "numRows": {
          "aggregate": {
            "count": 10
          }
        }
```

which is rather ugly.

Is there a way to make the query return the count value at a root level field instead?

**Comment by AdityaAnand1** [comment]
Any ideas? @tirumaraiselvan @alioguzhan @beerose

**Comment by tirumaraiselvan** [comment]
You cannot "flatten" the response as the query indicates the shape of the data.

One workaround is to create a postgres view which has the count field and query that instead.

**Comment by AdityaAnand1** [comment]
Yikes. Any plans to introduce alternate syntax for this and similar use cases? This syntax is really awful.

Creating views will work, but it doesn't seem like the hasura way 😏

**Comment by AdityaAnand1** [comment]
Any updates on this? @rikinsk 

```
    numProducts: products_aggregate {
      num: aggregate {
        num: count
      }
    }
```

Not sure if I'm doing something wrong, but I'm getting really sick of this `numProducts.num.num` format 😣 Everywhere in my otherwise pristine codebase, there's random `.num.num` scattered because of this :/

Is there really no workaround?

**Comment by rikinsk** [comment]
I think the only workaround for this currently is along the lines of what @tirumaraiselvan has suggested. Etiher create a PG view which contains the data in the shape you want and query it instead, or else set up a custom [Hasura action](https://hasura.io/docs/1.0/graphql/manual/actions/index.html) that exposes the API signature in the format you wish and internally executes the aggregate query from handler. 

That being said we can use this issue for further discussions and suggestions around this so that it might be taken up as a feature sometime in the future.

**Comment by tirumaraiselvan** [comment]
Related: https://github.com/hasura/graphql-engine/issues/360

**Comment by manasag** [comment]
We have recently launched Native Queries feature which allows to build custom objects (models) backed by SQL query; but without the need to creating views at the database level. Some docs [here](https://hasura.io/docs/latest/schema/postgres/native-queries/). You can try to create a top level model with an aggregate query.

**Comment by manasag** [comment]
Closing this in favor of #360
