### ISSUE TITLE
Create all default relationship names with column names

### ISSUE THREAD

**Issue by Papanash** [hasura/graphql-engine#4771]
Problem: When there are multiple relationships in one table, the default name of the first 
relationship is the name of the table itself while the following relationships are suffixed with "byCoulmnName", the name of foreign key it is related to. 

Suggestion: Suffix the first relationship name also with "byCoulmnName".

**Comment by rikinsk** [comment]
@Papanash Thanks for the suggestion! This is how it used to be a long time back :). Typically in such situations the name Hasura comes up with is always never ideal to be exposed over the API. So we recommend that the user rename them anyway right after creation to a more logical value.

**Comment by rikinsk** [comment]
Sorry. had closed this by mistake. 

@Papanash wanted to check if there is a specific reason for the behaviour you expect?

**Comment by Papanash** [comment]
I agree that the automatic name might almost never ideal to be exposed over the API.

But may i ask for the reason it was changed from that convention?
Can you explain the purpose for using the table name as default name of the first relationship?

**Comment by rikinsk** [comment]
The current logic is pretty simple. 

Based on relationship type (object/array ), set relationship name as the singular/plural form of the remote table name. In case there already exists a field for the table with the same name (an existing column or relationship), append the table name with "byColumnName" to create a unique field name. 

The reason for not appending "byColumnName" by default is because it always makes the name less user friendly than just the table name which in most cases is the most logical name for a relationship.

 For example, for the relationships between "author" and  "article" tables using "author_id" fKey, the generated relationship names would be "author" and "articles" which is much neater than "authorByAuthorId" and "articlesByAuthorId"

**Comment by Papanash** [comment]
thank you
