### ISSUE TITLE
Hasura/Actions - Support for nested object types

### ISSUE THREAD

**Issue by endigo** [hasura/graphql-engine#4796]
I want to build action for ElasticSearch API, it returns an array of product ids but I am not able to create a custom type that is nested.

```

type Product {
  id: bigint!
  name: String
}

type ElasticOutput {
  products: [Product!]!
  aggregations: jsonb
}
```

**Comment by tomasherout** [comment]
+1 it should be very useful  👍

**Comment by coco98** [comment]
> Copying @0x777 's comment on an internal discussion here for reference:

Let's assume the above types and say you have a top level field called get_config: `CloudConfig!` . Now, a query such as this comes in:

```
query {
  get_config {
    enabled_console
    enabled_APIs
  }
}
```
graphql-engine calls the HTTP handler, what should it respond with (note that you are not requesting jwt_secret)? It can respond with all of the CloudConfig data including the JWT secret even though that field is not requested, graphql-engine will then only send the requested fields in the selection set from this response. Seems straight forward.
Now consider mutually recursive custom types:

```
type comment {
  parent_id Int
  children [comment]!
  author_id Int!
  content String!
}
```

and your action definition is as follows:
`get_comments(thread_id: Int!): [comment!]!`
You cannot write a handler for this as the response of the handler depends on how deep the selection is.
To avoid these complications in the first iteration, we just said 'no object types' in the fields of object types.
I think what we can do though (still not easy) is to enable nested object type support for non-recursive types.

**Comment by CloudPower97** [comment]
@coco98 So, is there a workaround or something we can do about that? :confused:

**Comment by coco98** [comment]
@CloudPower97 The workaround for now is to flatten what you'd want from a nested action type!

Returning lists is already supported, so you can define an action that returns a list of elements. That element can in turn have relationships with other entities in Hasura and so that should work automatically :)

Example:
```
type mutation  createPosts(): [PostResult]

type PostResult {
  id: Int!
}
```

Now, there can be a relationship from `PostResult.id` to the Post table so that the mutation response returns all the data.

**Comment by nolandg** [comment]
Does this mean there is currently no way to derive a mutation for something like `insert_user`? The only thing that returns in the top-level is non-scalers thus deriving fails.

**Comment by thislogancall** [comment]
I think nested objects really need to be an option for action responses. Not only do you currently have to flatten all of your objects, but you also have to flatten errors into those same objects. If you really need error messages then this results in nearly all the fields of an object being nullable just to accommodate the possibility of error properties This is far from optimal. Example:

Say you want to use Plaid to get all of a user's accounts from their Plaid Items. You expect to return an array of accounts. However, it's possible that one or more items will be in an error state and the user will need to know that about that item specifically because they will need to re-link that item. We would still want to return all accounts (array of objects) and then all items with errors (array of objects or itemIds). This is not currently possible due to the lack of nested objects in Hasura actions. As such, only an array of "accounts" are returned with the only non-nullable property being the itemId. When an Item has an error, an "empty" account with an error property has to be returned. Here's the type for the account (in ReasonML) if it helps:

```reason
  type account = {
    itemId: string,
    /** this will be a plaidError stringified, since Hasura doesnt allow nested objects */
    error: option(string),
    accountId: string,
    mask: string,
    name: string,
    officialName: option(string),
    subtype: string,
    [@bs.as "type"]
    type_: string,
    verificationStatus: string,
    balancesCurrent: float,
    balancesAvailable: option(float),
    balancesLimit: option(float),
    balancesIsoCurrencyCode: option(string),
    balancesUnofficialCurrencyCode: option(string),
  };
```

Note that an additional workaround is to provide a JSON string as a field value (like the `error` field in the above example).

I'm happy to answer any questions about this use case. Thanks to the Hasura team for all of their hard work, truly amazing and groundbreaking software.

**Comment by mmaderic** [comment]
I would like to vote up for this feature. It would enable us to have generic action response types, that would contain possible error messages and payload data, being either collections or objects.

**Comment by ItsWendell** [comment]
We needed nested custom types for quite an advanced input object. The object had possible array relationships that could be _upserted_ by the user. I would have loved to do this as an Action, but because of this limitation mentioned in this issue, we needed to look for alternatives.

As a workaround, we created a serverless graphql server using [apollo-server-vercel](https://github.com/Saeris/apollo-server-vercel) a fork of [apollo-server-lambda](https://github.com/apollographql/apollo-server/tree/main/packages/apollo-server-lambda) to create Mutation that supported our advanced inputs.

Nested custom types for inputs and responses would be super valuable and prevents us from implementing a custom graphql server to make this happen or flatten our inputs (which in some cases would be unreasonable).

**Comment by DhvanilPatel** [comment]
I'd second this request as well! :)

**Comment by austindd** [comment]
@coco98 I think a better solution would be to disallow **recursive** object trees, rather than disallowing all nested objects. I could be wrong, but that should solve the issue in the short term while giving users *much* greater flexibility.

**Comment by smblee** [comment]
I'm resorting to making and calling the REST API end points directly for now until this is supported via Action.

**Comment by Luifr** [comment]
@coco98 what about blocking only recursive objects, and allowing everything else?

**Comment by manuFL** [comment]
Eagerly waiting for this feature... this problem is preventing us from using this beautiful library in production :(

**Comment by ItsWendell** [comment]
@manuFL Have you looked into serverless-graphql and merging the schema's as an alternative? https://github.com/hasura/graphql-engine/issues/4796#issuecomment-706413234

**Comment by manuFL** [comment]
Yes thank you, but as you said it is quite a workaround...

**Comment by eheiberg** [comment]
OP mentioned this earlier, but I would like to reiterate in case someone missed it, like I did, but one potential workaround for not having a nested object type is to use the `json` type. 

Example: 

Let's say you had a User who had multiple Roles across multiple applications. Role is an object that isn't in your database, so you can't solve this with a Relationship. Let's say in this case, it's just something you want to return back and it's an array of objects.
 
You **cannot** do this:
```
type Role {
  name: String!
  application: String!
  permission: String!
}

type User {
  id : String!
  name : String
  roles : [Role]
}

```

But, again, a workaround, just to get past it, but definitely doesn't solve the problem of the OP. 

```
type User {
  id : String!
  name : String
  roles : json!
}
```
is legal and seems to return the data as a single json object (without nesting or escaping). I.e the front end does not have to parse the JSON data of `User` and then subsequently parse the `roles` data. So... bonus?

**Comment by thanhdongnguyen** [comment]
I think author of hasura should consider change action allow nest object to response. Because many application have business logic complex and want custom type response to FrontEnd Engineer easy develop. Please seriously consider this matter

**Comment by RTAndrew** [comment]
Because I can't construct the typings a la Typescript or refer back to the Hasura schema types, I will just fall back and use a REST API to process all custom logic.

**Comment by jamesdhope** [comment]
Please can i upvote nested types. Major issue for us. Returning flat jsons is not really a workaround since we have key names in common at different levels.

**Comment by jamesdhope** [comment]
@vaishnavigvs any news on this?

**Comment by vaishnavigvs** [comment]
@jamesdhope this is something we're currently working on and we'll be back with an update soon!

**Comment by jamesdhope** [comment]
Do you have a timeframe @vaishnavigvs?

**Comment by psrcek** [comment]
:rofl: "soon" aka more than 1 month later you still haven't started any work

**Comment by incorvia** [comment]
Ran into this today on our project. Was a bit surprised needless to say. Will likely use the json type as a workaround for now.

**Comment by TeoTN** [comment]
Just popped onto that issue and must say it's quite limiting

**Comment by zlanich** [comment]
I too am very interested in integrating something like ElasticSearch results in my API, and I think these types should ideally be in the GraphQL API types layer.

**Comment by zedevs** [comment]
Very interested in that feature too!

**Comment by vxm5091** [comment]
Thanks Hasura team for all the hard work and the great platform. Similar to @zlanich I'm looking to integrate ElasticSearch results, so this would be a super helpful feature to have.

**Comment by kade-dentel** [comment]
Voting for this feature as well. Solving this with relationships currently is not an option for us and neither is flattening the data.

Thanks for the awesome work!

**Comment by paritosh-08** [comment]
Closed via https://github.com/hasura/graphql-engine/commit/40678855d03c70204419b7b27fa9068897cc4c7c

**Comment by BenoitRanque** [comment]
This feature has been merged into main, but has not been released yet as of 2022/010/26
We expect this feature to be included in the next release (currently the latest release is 2.1.1)

**Comment by snipebin** [comment]
@BenoitRanque when will this be released? Will it also be release to Hasura Cloud on the same date? It's urgent for us

**Comment by TwinkleMehta** [comment]
@BenoitRanque just seconding the above question^ need to use this feature and would love for it to be available asap. Thanks!

**Comment by BenoitRanque** [comment]
@snipebin @TwinkleMehta we are expecting to release v2.2 tomorrow

**Comment by snipebin** [comment]
@BenoitRanque some testing shows that it's only possible to use nested object types in the output/response and not in the input/request? Is this correct? If so why is there such a limitation and are there any plans to address it?

**Comment by fishactual** [comment]
I am also interested r.e. why this limitation exists in the input/request.

I am using an action to schedule in multiple participants (sometimes 10-15) using an action and it appears that this is a no go without flattening everything out (not feasible in my case).

**Comment by fishactual** [comment]
@BenoitRanque I am using 2.12.0 here is an example:

```
input CreateCalenderEventInput {
  interview_id: uuid!
  calendar_id: String!
  location: String
  participants: [Participant]
}

type Participant {
  name: String!
  email: String!
}
```

I am planning to switch `Participant` with `json` as a workaround for the time being.

**Comment by fishactual** [comment]
@BenoitRanque I had previously set it as an input and not type but was unable to apply the metadata on 2.12.0.

```
FATA[0002] error applying metadata 
cannot build actions from project: error parsing metadata 
object: actions
file: actions.yaml
error: custom type Nylas_Participant is not present in actions.graphql 
```

When I switch it to a type not input I can apply the metadata however I am still facing the aforementioned issue.

Thank you for your suggestion!

**Comment by BenoitRanque** [comment]
@fishactual can you please share the entire GraphQL definition for this and any other actions? This would be the `actions.graphql` file from your metadata.
