### ISSUE TITLE
add event trigger update ui to console

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#489]

**Comment by tirumaraiselvan** [comment]
Let's also merge docs with this issue.

**Comment by dsandip** [comment]
@karthikvt26 documenting our chat with @praveenweb about the UI for this here: 

1. Add an option in the settings page to edit trigger, this should be the first/primary option on the page. Clicking on this will take you to a version of the create triggers page, with the non-editable fields greyed out, the `Create` in the button at the end changes to `Modify`. Once a trigger has been updated, redirect the user back to the Settings tab (this should also happen if the user chooses to "cancel" on the update page).

Need to find a suitable title for the Settings tab that conveys that you can both see and modify the settings from here. @rikinsk ideas and review please?

**Comment by rikinsk** [comment]
Just to maintain consistency between the Data and Events sections, should we just update the Settings tab title to Modify and add in place Edit buttons like we have in Data.

**Comment by shahidhk** [comment]
docs issue here: https://github.com/hasura/graphql-engine/issues/680

**Comment by tirumaraiselvan** [comment]
@dsandip Can we prioritize this? I need this for presentation of 3F app.

**Comment by dsandip** [comment]
@wawhal the UI for "modify event trigger" will be similar to that of "modify table". Made a minor deviation because some of the config settings are related and cannot be edited in isolation:

![updateetriggerv2](https://user-images.githubusercontent.com/24300818/49213814-23e6ea00-f3eb-11e8-868e-ceff69fd9d9c.png)

editing any of the individual configs, will open up the same UI as in the create event triggers page (except for trigger config; @tirumaraiselvan please to validate the labels in the UI):

![updateetriggerv22](https://user-images.githubusercontent.com/24300818/49213867-4e38a780-f3eb-11e8-9795-f977f4700816.png)
