### ISSUE TITLE
Anonimous role is not working

### ISSUE THREAD

**Issue by lucasdevargassouza** [hasura/graphql-engine#4892]
After an engine security update, the anonimous rule no longer worked. Before the update everything was working!

In this case the action "authenticate" should appear in the explorer
![Captura de tela de 2020-05-26 18-03-13](https://user-images.githubusercontent.com/39599869/82950591-edf0da80-9f7b-11ea-8cb0-a216cf2f1543.png)

![Captura de tela de 2020-05-26 18-10-46](https://user-images.githubusercontent.com/39599869/82950775-4922cd00-9f7c-11ea-824f-9e84370d45e1.png)

I am using heroku.
![Captura de tela de 2020-05-26 18-11-52](https://user-images.githubusercontent.com/39599869/82950841-6d7ea980-9f7c-11ea-8813-a8501ab2c541.png)

I am demonstrating with an action, but this also happens for tables that have an anonymous role.

In this example below I show how it should be appearing, however it only happens if the admin secret is active.
![Captura de tela de 2020-05-26 18-18-10](https://user-images.githubusercontent.com/39599869/82951311-496f9800-9f7d-11ea-9b00-1f7574d5ea10.png)

**Comment by leoalves** [comment]
The `HASURA_GRAPHQL_UNAUTHORIZED_ROLE` value should be the name of the role you want to give access.  In your case `anonymous` and not `true`.
https://hasura.io/docs/1.0/graphql/manual/deployment/graphql-engine-flags/reference.html#command-flags

It was working because of a bug that was fixed with the security fix your said.

**Comment by lucasdevargassouza** [comment]
Thanks for help, that was  👍
