### ISSUE TITLE
`update_x_by_pk` is missing from non admin role with only update permissions applied

### ISSUE THREAD

**Issue by FickleLife** [hasura/graphql-engine#5058]
**Description**
When applying **only** update permissions to a non admin role in Hasura, `update_x` is exposed and not `update_x_by_pk` in the mutation root. If you give select (as well as the existing update) permissions to the non admin role, the `update_x_by_pk` now appears alongside `update_x` in the mutation root. 

**Reproduction steps**
1. Create a table and give it an anon user permission of update
2. Look at the mutation root for anon role, only `update_x` is there
3. give the anon user permission of select
4. Look at the mutation root for anon role, now both `update_x` and `update_x_by_pk` is there

**Tested in**
1.2.1
1.2.2

Thanks to @stevenpwaters on Discord who helped me troubleshoot

**Comment by stevenpwaters** [comment]
As @tirumaraiselvan noted on discord: "it's because insert_xyz has a returning field which doesn't require any select permissions."

It seems the regular update/insert's `affected_rows` and `returning` fields don't require any select permissions (though the latter's subfields do) and that's why they appear in the mutation root for roles with insert permissions but without select permissions.

So in terms of mutation schema:
- Insert permissions determine what fields are exposed as part of the arguments (e.g. `_where`, `_set`).
- Select permissions determine what fields are exposed as part of the mutation response.

Regardless, the role will need both select and update/insert permissions for the fields you're updating/inserting or you'll get a validation error. Only exception is the `update_<table>_by_pk` doesn't require any permissions for the PK column(s), only the fields being updated (provided you don't update or request any of the PK fields be returned in the mutation).

**Comment by tirumaraiselvan** [comment]
This is probably subsumed by https://github.com/hasura/graphql-engine/issues/4500
