### ISSUE TITLE
docs: API reference for Relay endpoint

### ISSUE THREAD

**Issue by sezgi** [hasura/graphql-engine#5174]

**Comment by tirumaraiselvan** [comment]
Document the specification of node `id` so that developers can decode and use the information present (if they want to). 

The specification is documented in source code at https://github.com/hasura/graphql-engine/blob/4e229dc568fc125f01a738cd1b4937885042b1fd/server/src-lib/Hasura/GraphQL/Resolve/Types.hs#L264.
