### ISSUE TITLE
use environment variables in web hooks

### ISSUE THREAD

**Issue by karibertils** [hasura/graphql-engine#520]
I would expect when using Hasura in a big project there would be quite alot of web hooks set up to deal with the business logic.

It would be super useful to be able to change all the event handlers at once. For example in development and testing you would want the events handled by a different server than in production...

Being able to specify something like "${MY_WEB_HOOK_URL}/my_trigger_handler" would deal nicely with this.

Additionally.
Since the POST data has plenty of info in it, it is actually pretty easy to use the same URL to handle all events, for those doing a monolithic handler anyway. So it would also be useful if there was a way to set a default webhook handler. This default handler would be used when no webhook url has been specified for the trigger. And specifying it would override the default handler.

**Comment by tirumaraiselvan** [comment]
Closing this in favor of https://github.com/hasura/graphql-engine/issues/966

**Comment by reinoldus** [comment]
Is it possible to reopen this issue? I think the point is still valid. My env-vars are starting to blow up

**Comment by roblframpton** [comment]
I would also like to see this re-opened.  As @reinoldus said, I would like to specify my webhook URLs as: `{WEBHOOK_ENDPOINT}/insert-user`, `{WEBHOOK_ENDPOINT}/insert-organization`, etc., so that I only have one environment variable to change and it is not tied to the endpoints I happen to write.  As it stands I have to create many variables like `WEBHOOK_ENDPOINT_INSERT_USER`, `WEBHOOK_ENDPOINT_INSERT_ORGANZATION`, etc.

**Comment by reinoldus** [comment]
it looks like this was implemented: https://github.com/hasura/graphql-engine/issues/2483
