### ISSUE TITLE
[1.3.0] Unable to call Hasura's own API with cron triggers

### ISSUE THREAD

**Issue by jflambert** [hasura/graphql-engine#5438]
With `hasura/graphql-engine:v1.3.0-beta.3.cli-migrations-v2`, this following cron trigger used to work:

```
- name: purge-hasura-logs
  webhook: http://localhost:8080/v1/query
  schedule: '* * * * *'
  include_in_metadata: true
  payload:
    args:
      sql: TRUNCATE hdb_catalog.event_invocation_logs; DELETE FROM hdb_catalog.event_log
        WHERE delivered = TRUE OR error = TRUE;
    type: run_sql
```

I would get the following request + response

![image](https://user-images.githubusercontent.com/11539524/88123058-1d951b00-cb98-11ea-9f34-579736fbb3b7.png)
![image](https://user-images.githubusercontent.com/11539524/88123083-2a197380-cb98-11ea-88c4-0054c1973b06.png)

With the official 1.3.0 Hasura release, I get the following request + response

![image](https://user-images.githubusercontent.com/11539524/88123328-add36000-cb98-11ea-9d19-60365e7d3c47.png)
![image](https://user-images.githubusercontent.com/11539524/88123343-b9268b80-cb98-11ea-924e-85f82ddb3623.png)

I understand the beta features are not necessarily expected to work as-is in the stable release, but it seems a huge oversight not to be able to call your own API. Or am I doing something wrong?

**Comment by tirumaraiselvan** [comment]
Hi @jflambert 

This was an intentional change as reported in this issue: https://github.com/hasura/graphql-engine/issues/5253 . Sending metadata with the payload is quite important and may induce breaking change if we didn't do it.

We are aware that this breaks your workflow where you wanted to call hasura internally. We do want to enable this and I think this issue: https://github.com/hasura/graphql-engine/issues/5050 that you had raised earlier is best place to track this.

Meanwhile, the current way to use scheduled triggers to call hasura is via an external webhook. I am closing this issue as this was intentional and let's continue the discussion in #5050

**Comment by jflambert** [comment]
@tirumaraiselvan I understand. This metadata took me by surprise though. I'll rephrase my request a bit, because my original scope was only about a shortcut to the local API.
