### ISSUE TITLE
tabbing through input values should work in insert row page

### ISSUE THREAD

**Issue by praveenweb** [hasura/graphql-engine#545]
Let's say I have name (text), description (nullable, text)

I insert something in text, and then I tab and insert text in description. The radio button doesn't get selected on the tab. That means that the actual value that gets inserted is NULL for description and not the text I tried to type.

**Comment by zacbraddy** [comment]
I'll give this a try. Just to confirm, are you talking about the radio on the left of the text boxes that are on the Data tab when you are inserting data? If this is the case should the radio be selected when you tab or rather when you actually start entering text. It would feel bad if you were intending to tab past a field and because you did that it entered an empty string instead of null just because you tabbed past it.

The ways in which I could see this working could be:

- The left radio is selected when you tab into the field and this remains until you manually hit the NULL radio. This would allow you to enter an empty string if you wished.
- When you tab into the field if the text field is currently empty then the NULL radio is selected if the field is nullable. When you then type something in the text field the radio on the left is automatically selected. Automatically selecting the radio buttons would only happen onChange so that if you wanted to enter an empty string, for e.g., then you could still manually select the left radio but the default behaviour would be for the NULL radio to be selected when you first tab into the text field and then have it flip over once it gets a value.

Do these ideas appeal? Or have I gotten too fancy and it'd better if I just did what you asked 😄
