### ISSUE TITLE
console: should add option to disable ONLY on ALTER TABLE

### ISSUE THREAD

**Issue by hgiasac** [hasura/graphql-engine#5512]
TimescaleDB hypertable doesn't support `ALTER TABLE ONLY` SQL statement. We should have an ENV option to disable `ONLY`

```json
{
    "statement": "ALTER TABLE ONLY \"public\".\"table_name\" ALTER COLUMN \"foo\" SET DEFAULT 0;",
    "prepared": false,
    "error": {
        "exec_status": "FatalError",
        "hint": null,
        "message": "ONLY option not supported on hypertable operations",
        "status_code": "0A000",
        "description": null
    },
    "arguments": []
}
```

![Screenshot_20200803_121017](https://user-images.githubusercontent.com/1615675/89147901-59f64d00-d582-11ea-8def-4c82bdb37d09.png)

**Comment by tirumaraiselvan** [comment]
From the PG docs, seems like `ONLY` is useful only in reference to inherited tables. Not sure why `ONLY` is added by default for column alter operations. What happens if you alter a column of a parent table with ONLY, then is the child table still a descendant? (But the columns are different now !)

Apart from the confusion above, there could be a checkbox in console to add `ONLY`. But, I think it is worth changing the default to not add `ONLY`.
