### ISSUE TITLE
Migration "Not Present" after created

### ISSUE THREAD

**Issue by jjangga0214** [hasura/graphql-engine#5591]
After creating an initial migration from server's state, it's not automatically considered as already applied.  

```bash
$ hasura migrate create init --from-server
INFO Migrations files created                      name=init version=1597409087181

$ hasura migrate status
VERSION        NAME  SOURCE STATUS  DATABASE STATUS
1597409087181  init  Present        Not Present
```

Thus, users have to execute `hasura migrate apply --version "<version>" --skip-execution` every time they start new projects.

Is this workflow intentionally designed?

Otherwise, wouldn't it be more intuitive if it's auto-applied when `hasura migrate create`? 

Thanks.

**Comment by scriptonist** [comment]
Hi, @jjangga0214 this was was an intentional design. The workflow that you mentioned makes sense but think of another scenario. When you are initializing a migration from another Hasura server using the `--endpoint` flag then we might not want to automatically mark it as applied right? 
In addition to the workflow that you mentioned, there can also be an alternative workflow which may not require us to automatically apply the initialized migration.

**Comment by jjangga0214** [comment]
@scriptonist I see. Thanks for the clarification!
