### ISSUE TITLE
how to protect admin password when to query?

### ISSUE THREAD

**Issue by huashaoxu** [hasura/graphql-engine#5619]
when i add an admin secret, send request must be set admin password in request header. everyone wil see my password by network in web browser, how to protect admin password when to query?

**Comment by praveenweb** [comment]
@huashaoxu - Once you secure your endpoint with admin secret, in order to query from the frontend, you need to have some form of authentication/authorization.

You can [configure unauthenticated or public access](https://hasura.io/docs/1.0/graphql/manual/auth/authentication/unauthenticated-access.html#configuring-unauthenticated-public-access).

If you have an authentication system (like Auth0, Firebase Auth or your custom JWT server) [you can set it up](https://hasura.io/docs/1.0/graphql/manual/auth/authentication/jwt.html) and then query from frontend by passing in the `Authorization` header with the token.

**Comment by huashaoxu** [comment]
But it do not protect password,  by base64 decoded
