### ISSUE TITLE
on_conflict update_columns not working for column preset with session variable

### ISSUE THREAD

**Issue by happyfloat** [hasura/graphql-engine#5715]
I'm trying to update the "user_id" column if there is a conflict on a unique field. `graphql-codegen` throws this error: "GraphQLDocumentError: Value "user_id" does not exist in "push_token_update_column" enum.", if the value of "user_id" is coming from the session variable, otherwise it would work.

Any ideas on how to solve this issue?

```gql
insert_push_token_one(
      object: $content
      on_conflict: {
        constraint: push_token_fcm_token_key
        # TODO: Add "user_id", but it doesn't work because the value should come from the session variable
        update_columns: [apns_token, platform]
      }
    ) {
      id
    }
``` 

<img width="1020" alt="Screenshot 2020-09-02 at 16 53 49" src="https://user-images.githubusercontent.com/64045340/92000641-0708e480-ed3e-11ea-9d34-66dd0b7b31dc.png">

**Comment by tirumaraiselvan** [comment]
If the column is already preset, it should be updated automatically without you having to provide it in the `on_conflict.update_columns` list. Is that not happening for you?

**Comment by happyfloat** [comment]
You are right, it does update the user_id too. That's good for me!

The only thing I had to change was my custom check from "Pre-" to "Post-update check", otherwise nothing would be updated at all (also no error message).

**Comment by tirumaraiselvan** [comment]
Not exactly sure what you mean but you should be able to set presets even with just "pre-update" checks.

**Comment by happyfloat** [comment]
@tirumaraiselvan The "pre-update check" will validate the user_id. If the user_id did change for the unique constraint on the fcm_token column, the new user_id doesn't have rights to change it in the first place.

**Comment by piyushk** [comment]
I think @happyfloat mentioned a legitimate problem here -- I was making the exact same mistake (using a pre-update check instead of a post-update check in the exact same setting). I do not believe Hasura should have failed silently. I'm using Hasura v1.3.3

Here's the exact scenario.

I have a table called `users` with columns `id`, `username`, and `other_data`. I'd like to auto-populate them from the JWT claim (`x-hasura-user-id` and `x-hasura-user-name`) if a user logs in to the app. The app sends the following upsert query to the hasura:
```
mutation loginUser {
    insert_users(
        objects: {other_data: "ABC"}
        on_conflict: {constraint: users_pkey, update_columns: [username, other_data]}
    ) {
        affected_rows
    }
}
```

For insert my permissions were (works as intended):
- Insert check: `{"_and":[{"id":{"_eq":"X-Hasura-User-Id"}},{"username":{"_eq":"X-Hasura-User-Name"}}]}`
- Partial column insert was only allowed to `other_data`, and `id` and `username` was preset via session variables. The user gets inserted correctly on first login.
For update my permissions were (accidentally used a pre-update check instead of a post-update check):
- Pre-update check (incorrect): `{"_and":[{"id":{"_eq":"X-Hasura-User-Id"}},{"username":{"_eq":"X-Hasura-User-Name"}}]}`
- Partial column update was only allowed to `other_data`. and `username` was preset via session variables.

If the username for that user is different in the DB, then the update will fail silently and the upsert query returns a 200. It took a while to debug what was going on. Should it have thrown an error because the pre-update check failed?

The correct update check was:
- Pre-update check: `{"id":{"_eq":"X-Hasura-User-Id"}}`
- Post-update check: `{"_and":[{"id":{"_eq":"X-Hasura-User-Id"}},{"username":{"_eq":"X-Hasura-User-Name"}}]}` (Id check isn't likely required, but just to be safe)

**Comment by piyushk** [comment]
I can't tell if this is bug or not (silent failure on update if pre-update check fails on upsert queries) -- but I can file a new ticket if necessary.
