### ISSUE TITLE
`_not` and `_or` in where filter affects results

### ISSUE THREAD

**Issue by yaroot** [hasura/graphql-engine#5838]
When `_not` and/or `_or` is included and set to null the query always gives empty response, removing both gives correct response. I don't think these 2 should affect the results when set to null.

(the client I use (https://github.com/ghostdogpr/caliban) generates these for me, imho not possible to work around)

```
query {
  product(
    where: {
      _and: null
      _not: null
      _or: null
      id: {
        _eq: null
        _gt: null
        _gte: null
        _in: [1, 2, 3, 4, 5]
        _is_null: null
        _lt: null
        _lte: null
        _neq: null
        _nin: null
      }
    }
  ) {
    id
  }
}
```

**Comment by GavinRay97** [comment]
Hello =)

It's unfortunate that your library is auto-inserting those `null` values for every field, but this one is something I don't think can be worked around on our end.

If you check the `ANALYZE` output for this query:
```graphql
query {
  github_repo(where: {
    _or: null,
    id: { _eq: 1234 }
  }) {
    id
  }
}
```
The condition `Where "_or" (any of): "null" is true` is always a falsey statement, so it is generated as:
```sql
-- Using "_or: null"
SELECT
  *
FROM
  "public"."github_repo"
WHERE
  (
    ('false')
    AND (
      ("public"."github_repo"."id") = (('1234') :: integer)
    )
  )
```
And the condition `Where "_not": "null" is true` converts to `NOT true` because of this behavior:
https://hasura.io/docs/1.0/graphql/core/queries/query-filters.html#evaluation-of-null-values-in-comparision-expressions
```sql
-- Using "_not: null"
SELECT
  *
FROM
  "public"."github_repo"
WHERE
  (
    (NOT ('true'))
    AND (
      ("public"."github_repo"."id") = (('1234') :: integer)
    )
  )
```
