### ISSUE TITLE
notify user that down migrations are not generated when raw sql is executed

### ISSUE THREAD

**Issue by grgurev** [hasura/graphql-engine#616]
Maybe it would be helpful to notify users somewhere near that "This is a migration" checkbox that down migrations are not generated when executing raw sql?

**Comment by shahidhk** [comment]
To add to what @grgurev mentioned, for every action done on the console, if run with the CLI using `hasura consol` and migration mode is not turned off, the console generates up and down migration steps.

But, when using the SQL tab and executing custom SQL, even when the `This is a migration` checkbox is selected, down migrations are not generated since console does not know what he rollback action is.

So, in the run sql screen, if the above-mentioned checkbox is selected, notify the user that down migrations are not created.

@praveenweb @karthikvt26 , maybe show a tooltip? Any other suggestions?

**Comment by karthikvt26** [comment]
Will it be useful if we add a line under Notes section in `SQL` tab?

![screenshot 526](https://user-images.githubusercontent.com/25095884/46405704-affbce80-c726-11e8-8ed0-ff500711da43.jpg)

@shahidhk @grgurev

**Comment by shahidhk** [comment]
@karthikvt26 Not sure if everyone reads this. But yeah, let's add it there as a stop-gap solution.
