### ISSUE TITLE
event creation fails for tables beginning with capital letter

### ISSUE THREAD

**Issue by rikinsk** [hasura/graphql-engine#639]
![screenshot from 2018-10-04 13-06-48](https://user-images.githubusercontent.com/153602/46459651-23f5af80-c7d7-11e8-8feb-278342179634.png)

**Comment by kaleabmelkie** [comment]
@shahidhk This issue is back again. 

![image](https://user-images.githubusercontent.com/29814842/166428132-0558aec7-057e-4628-8d54-790c22306265.png)

I've tested it in 2 different projects, both running on Hasura Cloud v2.6.0-cloud.1

We can't create Events for tables beginning with a capital letter, but it works for all small (snake_case) table names.

More details on the error message:

![image](https://user-images.githubusercontent.com/29814842/166428628-50bee574-42ff-4d6f-a7e3-d682ff86fd25.png)

**Comment by tirumaraiselvan** [comment]
@kaleabmelkie This was reported here: https://github.com/hasura/graphql-engine/issues/8454 and will be out in 2.6.1 (today)

**Comment by kaleabmelkie** [comment]
Thanks!
