### ISSUE TITLE
Is there any way to copy table with different name?

### ISSUE THREAD

**Issue by Hwan-seok** [hasura/graphql-engine#6442]
What i am doing is using `computed field` on jsonb type to have flexible query 

The result that i wanna derive from it is the table that one text column is added.
but `computed fields` cannot return `setof composite type` but `setof table`

so i need to create new table what is similar from existing one
But i cannot find any way to excute `show create table ...`-like utils that can includes relations  

Is there any way to do this?

Thanks.

**Comment by ayuryshev** [comment]
Please clarify: by "computed columns" you mean [generated columns](https://www.postgresql.org/docs/12/ddl-generated-columns.html) in postgresql 12 and 13? 

Because for views you can define fields with SETOF types.

Experiment:

```sql
DROP TABLE x.xxx CASCADE;

CREATE TABLE x.xxx(cz varchar, nz int );

CREATE FUNCTION x.fxxx () RETURNS SETOF x.xxx
LANGUAGE SQL
AS $$ 
SELECT '42' AS cz, 42 AS nz;
$$;


SELECT * FROM x.fxxx();

CREATE VIEW x.yfxxx
AS
SELECT x.fxxx() AS x;

SELECT * FROM x.yfxxx;
````

Note that  column `x` is having type `SETOF x.xxx`.

Or maybe you're trying to achive something completely differrent?

**Comment by tirumaraiselvan** [comment]
A full code example of what you are trying to achieve would really help!

**Comment by Hwan-seok** [comment]
Sorry for making a trip for nothing
I was wrong because I'm new for Computed Fields at that time.
