### ISSUE TITLE
Something wrong with _or operator

### ISSUE THREAD

**Issue by bluevariant** [hasura/graphql-engine#6455]
My query:

```graphql
query MyQuery {
  users(where: {_or: {password: {_is_null: true}, salt: {_is_null: true}}}) {
    username
  }
}
```

I found issue in query builder

**Comment by rikinsk** [comment]
This is due to a bug in the query builder and a nuance in the way _or behaves. 

The following resources should help clear the confusion:
- Issue regarding the query builder bug: https://github.com/hasura/graphql-engine/issues/3322
- Docs regarding _or behaviour: https://hasura.io/docs/1.0/graphql/core/api-reference/graphql-api/query.html#orexp
