### ISSUE TITLE
Bug with evaluation of null values in comparision expressions in v1.3.4-beta.2 

### ISSUE THREAD

**Issue by onikienko** [hasura/graphql-engine#6467]
According to the [documentation](https://hasura.io/docs/1.0/graphql/core/queries/query-filters.html#evaluation-of-null-values-in-comparision-expressions):
> If in any comparision expression a `null` (or `undefined`) value is passed, the expression currently gets reduced to `{}`

I have such quiery:

```
query Items($itemId: Int) {
  item(where: {id: {_lt: $itemId}}) {
    id
    name
  }
}
```

Querry value `{itemId: null}` or `undefined`. 

I expect that `where` will be evaluated to the `where: {}` as described in the documentation. Instead, I have an error **expected a 32-bit integer for type \"Int\", but found null**.

This bug appears with v1.3.4-beta.2 for me. On stable, it worked as expected.

Possible related to #6459

**Comment by onikienko** [comment]
Looks like the answer may be found here https://github.com/hasura/graphql-engine/issues/704#issuecomment-635571407  

Strange to see such kind of changes in a minor version.

**Comment by tirumaraiselvan** [comment]
Sorry about this! But this was actually causing serious problems for mutations where `{}` to `true` was deleting all the rows in the table. Also, the overall behaviour seemed opposite of expectation since passing `null` into a variable would hardly mean "everything" but variables accidentally becoming `undefined` was quite common.

We will highlight this in the changelog and make proper notifications before hitting stable. Thanks for the feedback.

**Comment by onikienko** [comment]
I understand the reason for this update. And agree. 

[semver](https://semver.org/) is kind of standard currently. Especially in the js community. So having breaking changes in the `patch` update may be a surprise.
