### ISSUE TITLE
Event triggers use too many postgres connections

### ISSUE THREAD

**Issue by jflambert** [hasura/graphql-engine#6496]
Tested with hasura 1.3.3 and 1.3.4-beta.2

We were surprised to see Hasura using upwards of 50 postgres sockets/connections with around 5000 transactions per second.

1. create a simple table and attach a dummy event trigger
2. insert a batch of 5000 events (using generate_series for example)
3. monitor postgresql sockets with `select count(*) from pg_stat_activity;`
4. observe 50+ additional sockets being used by hasura
5. observe some warnings in hasura logs: "Events processor may not be keeping up with events generated in postgres, or we're working on a backlog of events. Consider increasing HASURA_GRAPHQL_EVENTS_HTTP_POOL_SIZE"

Is this expected behavior?

Are event triggers not a viable solution in a "high" throughput situation?

I can confirm the sockets do get released once idle (within 8-10 minutes)

**Comment by cpursley** [comment]
Maybe the better approach would be to listen to the Postgres WAL for changes instead of triggers. This is what I'm doing from Elixir and it only uses 1 connection.

**Comment by jflambert** [comment]
> Maybe the better approach would be to listen to the Postgres WAL for changes instead of triggers.

That sounds intense, but doable. I'd be curious to see your "listen to WAL changes" code. I can't imagine it to be simple.

**Comment by cpursley** [comment]
@jflambert ~ it depends ~ what backend stack are you using?

**Comment by tirumaraiselvan** [comment]
Event Trigger mechanism is fully configurable to achieve the throughput you need. But nothing comes free, so you may need to give resources.

As the logs indicate, there are possibly many events pending and hence increasing the number of max concurrent http workers via: `HASURA_GRAPHQL_EVENTS_HTTP_POOL_SIZE` will help here. Further, each http worker will mark the event as "delivered" so it acquires a PG connection, and hence it will also take resources from the Postgres connection pool whose size you can configure via `HASURA_GRAPHQL_PG_CONNECTIONS`. Since you are running a test bench, the delivery is perhaps happening _instantly_ and hence there is very high contention for the pool.

**Comment by tirumaraiselvan** [comment]
We now also support the env `HASURA_GRAPHQL_EVENTS_FETCH_BATCH_SIZE` for performance tuning since this commit: https://github.com/hasura/graphql-engine/commit/bc1e13171736df58e51313870d96793b188f2afd. This should be configured in tandem with `HASURA_GRAPHQL_EVENTS_HTTP_POOL_SIZE` (i.e. if you are increasing the former, then in almost all cases you should increase the latter).

Pls let us know if you have any issues achieving the throughput you need for event triggers.
