### ISSUE TITLE
Schema Cache Sync listen-notify connections break Aurora Serverless Postgresql Auto-Scaling

### ISSUE THREAD

**Issue by bluetoken-jacob** [hasura/graphql-engine#6527]
Currently working through a POC of Hasura + AWS Aurora Serverless Postgresql. Hasura's Schema Cache Sync process utilizes  listen-notify connections that seem to break Aurora Serverless's seamless auto-scaling feature.

From AWS's docs the listen-notify usage does break their auto-scaling.
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless.html#aurora-serverless.limitations
```Currently, certain SQL queries and commands aren't recommended. These include session-level advisory locks, temporary relations, asynchronous notifications (LISTEN), and cursors with hold (DECLARE name ... CURSOR WITH HOLD FOR query). Also, NOTIFY commands prevent scaling and aren't recommended.```

Does a workaround exist that doesn't break the auto-scaling functionality?

**Comment by tirumaraiselvan** [comment]
Hi there

3 options since v2.0 :

1. If you are latest version of cloud, then Hasura will manage metadata on it's own storage and hence will not need a LISTEN connection to user db.
2. If you are on self-hosted, then you can separate the metadata storage to a different pure PG database. Similar to point 1., this will avoid LISTEN connection on user db.
3. If you are on self-hosted but do not want to separate metadata storage, you can disable schema sync by setting the env `HASURA_GRAPHQL_SCHEMA_SYNC_POLL_INTERVAL: 0` to disable it. If you disable it and you have multiple hasura instances, then you will need to reload metadata manually on each of the instances (using `reload_metadata` API) or restart them (which will reload metadata).

**Comment by tirumaraiselvan** [comment]
Closing this, pls feel free to reopen if the above solutions do not work.
