### ISSUE TITLE
Connectivity from Hasura to PG working but not the other way

### ISSUE THREAD

**Issue by sushilbansal** [hasura/graphql-engine#6594]
Setup:

1) Using Digitial Ocean one click setup
2) Followed the steps to replace the HASURA_GRAPHQL_DATABASE_URL with my RDS postgres url which is on this pattern: postgres://<USER_NAME):@:5432
I followed the steps to include my Digital ocean IP address to inboud rules. Also RDS pg is public available. I can make queries/changes from my pgadmin.

Hasura is not able to fetch any existing tables or data. But if i create table and add data in Hasura it reflects back in pgadmin. What is the issue here?

**Comment by sushilbansal** [comment]
another weird thing:
if i create table in Hasura and then delete it from pgadmin Hasura detects it and ask me to verify if i want to delete it from Hasura to maintain the consistency.

**Comment by soorajshankar** [comment]
Hey @sushilbansal , Thanks for submitting the issue!

Just to confirm that I understand correctly, 
* You added a Postgres database with the connection string successfully
* You clicked on view database, and then you selected the schema where you have some tables
* Then the expected behaviour is to show the trackable tables, functions, views etc. as shown below
![image](https://user-images.githubusercontent.com/8408875/109474119-2b9a0b00-7a9a-11eb-97ac-e0bdae4d6192.png)
* and when you click on `Track`, that is when the tables get added to the sidebar.

https://user-images.githubusercontent.com/8408875/109475057-402ad300-7a9b-11eb-9c6c-666dd044e89d.mov



from what I understand, can I confirm that the tables are not even listing under `Untracked tables or views` as shown above?

also, could you share the exact Hasura GraphQL Engine version that you are using?

**Comment by sushilbansal** [comment]
it started showing up in untracked tables in the latest version
