### ISSUE TITLE
Cannot use serializable mode in a hot standby

### ISSUE THREAD

**Issue by rijnhardtkotze** [hasura/graphql-engine#660]
I am following the instructions from [the official documentation](https://docs.hasura.io/1.0/graphql/manual/deployment/heroku/using-existing-heroku-database.html).

I am trying to connect Hasura to a follower database, it serves the following error: "cannot use serializable mode in a hot standby" 

Here is the exception: 

    {  
      "internal":{  
          "statement":"BEGIN ISOLATION LEVEL SERIALIZABLE ",
          "prepared":true,
          "error":{  
             "exec_status":"FatalError",
             "hint":"You can use REPEATABLE READ instead.",
             "message":"cannot use serializable mode in a hot standby",
             "status_code":"0A000",
             "description":null
          },
          "arguments":[  

          ]
      },
      "path":"$",
      "error":"postgres tx error",
      "code":"postgres-error"
    }

Any ideas?

**Comment by 0x777** [comment]
@rijnhardtkotze We haven't tested graphql-engine with a Hot Standby Postgres instance. It might be possible to connect to a Hot Standby instance after initializing the state with the master instance. We'll get back to you on this.

**Comment by rijnhardtkotze** [comment]
Thanks, @0x777 

Please let me know if I can be of any assistance.

**Comment by paulmwatson** [comment]
Any progress on this please, having the same issue.

**Comment by vinay0410** [comment]
Hi @0x777 ,
Is there a workaround to connect if this exception pops up.

**Comment by Iris-Qian** [comment]
Any progress on this?

**Comment by guibernardino** [comment]
+1

**Comment by jocrau** [comment]
I tried setting `HASURA_GRAPHQL_TX_ISOLATION=repeatable-read` but that didn't help because the initialization always happens at `SERIALIZABLE` level.

This is currently a blocker for using Hasura at our company. We have a high ingest rate on a Postgres master and read only from replicas.

**Comment by ttelfer** [comment]
Just ran into this problem as well. We have actually been using Hasura in essentially a read-only for generating dashboard frontend with no user inputed data. The problem we have is similar to ours is have an extremely high ingest rate and due to this we need to separate our reads. Has anyone looked at modifying the isolation level to repeatable read?

**Comment by cheslip** [comment]
Seeing this issue in Azure when setting up Postgres read replicas for a backup hasura environment.

**Comment by ttelfer** [comment]
We have found a way to get around this by using a proxy that can do read/write splitting such as PGPool2. This does seem to have a bit of a performance impact in our tests, but it does accomplish splitting reads and writes.

**Comment by tirumaraiselvan** [comment]
Can be solved by #3533

**Comment by meotimdihia** [comment]
I need to connect hot standby for local development.

**Comment by rccoe** [comment]
I'm bumping into this as well, getting postgres tx error at that migrateCatalog call. Can we get that PR merged @tirumaraiselvan ?

**Comment by davidpanic** [comment]
Has there been any progress on this? We would like to take advantage of our postgres read replicas by running additional read only hasura instances and splitting reads on the apollo client. This is currently preventing us from doing that.

**Comment by tirumaraiselvan** [comment]
Hey folks, it should be possible to add a read replica as a datasource directly if you configure a separate (writeable) metadata db.

**Comment by davidpanic** [comment]
I cannot seem to get it to work, hasura stops with exit code 1 and logs the following error: `{"code":"postgres-error","error":"postgres tx error","internal":{"arguments":[],"error":{"description":null,"exec_status":"FatalError","hint":null,"message":"cannot set transaction read-write mode during recovery","status_code":"0A000"},"prepared":true,"statement":"BEGIN ISOLATION LEVEL READ COMMITTED READ WRITE"},"path":"$"}` which seems pretty obvious to me, since the database is read only. Setting `HASURA_GRAPHQL_TX_ISOLATION=repeatable-read` doesn't do anything.
