### ISSUE TITLE
[v2.0.0-alpha.2] Array output types of actions not in generated graphql schema

### ISSUE THREAD

**Issue by cederigo** [hasura/graphql-engine#6631]
Given:
![image](https://user-images.githubusercontent.com/415316/109932293-4bb01100-7cca-11eb-895b-6c82029b4786.png)

the resulting graphql schema in hasura v2.0.0-alpha.2 is incorrect:
![image](https://user-images.githubusercontent.com/415316/109932004-ee1bc480-7cc9-11eb-9df0-f0bade129966.png)

but in v1.3.3 it was correct:
![image](https://user-images.githubusercontent.com/415316/109932191-27eccb00-7cca-11eb-8530-d01c2a463848.png)

**Comment by khan297** [comment]
ظ

**Comment by istarkov** [comment]
Same in alpha 5

**Comment by picosam** [comment]
Same bug here.

**Comment by picosam** [comment]
I believe this was fixed in alpha 6 but I might be mistaken.

**Comment by mvaivre** [comment]
Still exists in alpha.7

**Comment by rakeshkky** [comment]
@mvaivre Please give us the output type for `getDamagePictures` action.

**Comment by happyfloat** [comment]
For me it was fixed in alpha 6

**Comment by TheMrZZ** [comment]
Still happening in alpha 9

**Comment by siassaj** [comment]
I have been experiencing the same thing with v1.3.4-beta.2 and 1.3.4-beta.3

The documentation [here](https://hasura.io/docs/latest/graphql/core/actions/types/index.html#custom-object-type-relationships) appears to indicate that the fields of types  must only be scalars or enums, so does this mean that 1.3.3 behaves differently than what's intended in 1.3.4 - 2.x.x ?

**Comment by nicuveo** [comment]
This was closed automatically because the fix was merged to main! It will be included in the next release. :)

There actually was *two different bugs* described in this issue! The first one was fixed prior to alpha 6, and the other is the one that was just fixed. Consider the following action and custom type:

```graphql
# action
type Query {
  MyAction(id: Int!): [MyActionType!]
}

# custom type
type MyActionType {
  result: [String!]
}
```

The [first bug](https://github.com/hasura/graphql-engine/issues/6631#issue-821883487) was about the return type of the action: the schema listed the action as returning `MyActionType` instead of `[MyActionType!]`. The [second bug](https://github.com/hasura/graphql-engine/issues/6631#issuecomment-814100883) was about *the types of the fields within the return type*: even if the return type of the action was correct, the field `result` was shown as `String` instead of `[String!]` in the schema.

(If you are interested in the technical details of this bug, let me know, I'd be happy to explain what the bug was and how it came to be!)

**Comment by caoer** [comment]
Thanks @nicodinh, can you explain a bit more, or point out either issue, PR, or commit of the fix?

**Comment by nicodinh** [comment]
> Thanks @nicodinh, can you explain a bit more, or point out either issue, PR, or commit of the fix?

It's not me :smile: @caoer

**Comment by caoer** [comment]
ah...🤦 I meant to ping   @nicuveo .... 
sorry for the bothering. @nicodinh

**Comment by nicuveo** [comment]
Yeah, sure @caoer ! The patch for the second bug (fields within action output types) is [here](https://github.com/hasura/graphql-engine/commit/ecb90c47a1152a0be87b036b0b223f56bf7f288b).

### Schema and parsers

The context is that, last year, on the road to 2.0, we did a major refactor of the internals of the engine, nicknamed the "PDV refactor", for "Parse, Don't Validate", inspired by Alexis' [blog entry](https://lexi-lambda.github.io/blog/2019/11/05/parse-don-t-validate/) (we talked about it during our [August community call](https://www.youtube.com/watch?v=tFtgy4mQ68o)). The [resulting PR](https://github.com/hasura/graphql-engine/pull/4111) is a monster: 241 files modified, +14,929 −12,781. Its goal was to fix a old issue in the code, related to the GraphQL schema generation.

Before that change, generating the GraphQL schema from our metadata and parsing an incoming GraphQL query were two separate parts of the codebase, that had to be manually kept in sync. For example, if our metadata contains information about a Postgres table "test" with columns "foo int, bar int", then:
- the schema code needs to generate the corresponding schema:
```graphql
type test {
  foo: Int
  bar: Int
}

type Query {
  test(where: testBoolExp): [test!]
}
```
- the parsers need to accept corresponding queries, such as:
```graphql
query {
  test(where: {foo: {_eq: 42}} {
    bar
  }
}
```

But if you introduce a subtle feature, and you don't make the proper change in both parts of the code... then the schema advertises something that the parsers reject, or vice versa! We used to run into bugs like this quite a lot. Hence this refactor, that coalesced both parts of the code in one.

### PDV

What we did was to rewrite the entirety of the parsing code, to use a _parser combinators_ approach (if you're unfamiliar with the term, I wrote a [quick primer](https://hasura.io/blog/parser-combinators-walkthrough/) on the subject last year). For instance, the code that parses the arguments to a table looks (roughly) like this, now:

```haskell
tableArguments tableName selectPermissions = do
  -- gather other parsers
  whereParser    <- tableWhereArg    tableName selectPermissions
  orderByParser  <- tableOrderByArg  tableName selectPermissions
  distinctParser <- tableDistinctArg tableName selectPermissions
  -- output a parser that uses them...
  pure $ do
    whereArg    <- whereParser
    orderByArg  <- orderByParser
    limitArg    <- tableLimitArg
    offsetArg   <- tableOffsetArg
    distinctArg <- distinctParser
    -- ...and outputs our internal representation of table arguments
    pure $ IR.SelectArgs
      { IR._saWhere    = whereArg
      , IR._saOrderBy  = orderByArg
      , IR._saLimit    = limitArg
      , IR._saOffset   = offsetArg
      , IR._saDistinct = distinctArg
      }
```

each parser, recursively, parses what it needs to: `tableWhereArg` will call the `boolExp` parser, `tableLimitArg` will call the `int` parser, etc...

But the unique property of [the type of our custom parsers](https://github.com/hasura/graphql-engine/blob/master/server/src-lib/Hasura/GraphQL/Parser/Internal/Types.hs) is that it's _introspectable_, meaning we can extract the schema out of the parsers! So, the parser that this function generates can be introspected, to get the information that the arguments to a table are `limit: Int!, where: BoolExp, offset: Int`, and so on, meaning the schema can no longer get out of sync with the parsers; if you change what the parsers expect, that'll change the schema accordingly: if for instance you change `limitArgParser` to call the `string` parser instead of the `int` parser, when introspecting the parser we will generate a schema in which the type of the `limit` argument is `String` instead. **The schema will be correct by construction**.

Except...

### Output types

This technique works wonder for _input types_, which is most of where the complexity lies in, but has a drawback when it comes to output types. We still use the same technique, of course: if the parser for a selection set of a table looks like this (this is extremely simplified):

```haskell
tableSelectionSet tableInfo = do
  for (tableFields tableInfo) \field ->
    tableField (fieldName field) (fieldType field)
```

Then for our table "test", the resulting parser can be introspected to yield the corresponding schema type; we still have all the correct fields by construction:
```graphql
type test {
  foo: Int
  bar: Int
}
```

But the big difference, here, is that the parsers only parse the name of the field (and its arguments, if any): there's no value to parse! So how does it know what the type of `foo` and `bar` are? Well... because we tell it so: in our simplified example, we're giving `fieldType field` as an argument to `tableField`. But if we get it wrong, this won't prevent queries from running, since that information is only used for the schema. And that's how we can end up generating erroneous output types in the schema, despite constructing the schema from the parsers: **the type of output fields is the only thing they can't really check**.

### The second bug

(The first one is more or less the same, so I'll focus on the second one, which is slightly more interesting.)

Internally, in our metadata, we don't store the exact GraphQL type that was given during the setup; we use a parsed and annotated version of it. And, more specifically, the haskell type we use to represent a field of a custom output type contains *two different pieces of information* about its type:
- its actual GraphQL type (say, `[[String!]]`)
- some annotated information about the base type, which we restrict to a scalar or an enum (in this case, `Scalar String`)

That second bit of information is used for action relationships, among others. The bug was that, when creating the parser for each field of the object, we were generating the correct field name... but using the wrong haskell piece of information for the parser type! To be more accurate: we were not applying the correct modifiers based on the type information available, and only using the base type as described by that second piece of information. The fix, as you can see, is fairly simple: "just" use the correct type information to craft the correct output parser. ^^

---

We're currently going over all those small mistakes, to try and get a stable version of v2 as soon as possible. In the meantime, if you have any question about this, happy to go into more details / point out the relevant parts of the code. :)

**Comment by caoer** [comment]
Thanks for you detailed explanation!! @nicuveo 

It took me a while to go over the blog, PR, and the video. I can't say I've totally understand all the details, actually I knew little about haskell(it's beautify and definitely on my bucket list) , but know why and how, with some guessing around. I'm much more comfortable making the switching.

Love the idea "Parse, don't validate". It can be extended to a lot of other type based languages. 

With some testing around it on *Action*, I'm guessing it is using the same mechanism. with following output type: 
```
type SampleOutput {
  shouldBeString : String!
  shouldBeHere: Int!
}
```
regarding `shouldBeString`: 
If our action handler return `shouldBeString` to be an integer, or a string array, or an object, the request works fine. It will throw an error if `shouldBeString` is null. 

regarding `shouldBeHere`
if our action handler, does not return `shouldBeHere`, it will report error of not having this attribute. 

if our action handler, return more attributes than above defines, it will throw error. 

It's interesting to see such differences. the mantra “parse, don’t validate.” is hard to achieve in a real world case, especially when dealing with external systems. kudos to hasura team! I think in the perfect world, the external system, aka, action handler should be consuming `metadata/actions.graphql`, or generating it. The action handler is strong typed as well, so that the `metadata/actions.graphql` be the one describing the interface, and any changes made to the interface will trigger a compile error, either in action handler, or the graphql schema consumer.  

last, do you know if hasura will be in any position of validating outputs? I guess the term validate is better than parse because the output is not intent to be used by hasura. I think there might be performance concerns, likewise, our teams are using huge output from hasura in a single request, it's probably not cheap to validate all those outputs. Or it might never be the concern of hasura core, but might be part of a plugin like system. Or, I'm not sure, once knowing the detail, not sure this ought to be an issue worth solving? Would love to know what's your insight about it.
