### ISSUE TITLE
FATA[0007] apply failed: cannot create migrate instance: [not-exists] source with name "default" does not exist ($.args)

### ISSUE THREAD

**Issue by jagyas** [hasura/graphql-engine#6644]
Hello,
I was following documentation steps from https://hasura.io/learn/graphql/nextjs-fullstack-serverless/hasura-backend/ and downloaded migration scripts. While executing **hasura migration apply**, I am getting below error:
FATA[0007] apply failed: cannot create migrate instance: [not-exists] source with name "default" does not exist ($.args)
With this error it is not clear that what problem could be and where I should look.
Could you please help me to point in right direction?
Thanks

**Comment by rikinsk** [comment]
Hey @jagyas. Thanks for pointing this out. Seems like the tutorial has not been updated with the new workflow that comes with Hasura v2.0. The error suggests that you currently do not have a database connected to your Hasura instance (or it doesnt have the name `default`).You can follow the steps mentioned [here](https://hasura.io/docs/latest/graphql/cloud/getting-started/index.html#step-3-connect-new-existing-database) to connect a database to your Hasura instance. Note that for the migrations to work you will need the database to be named as `default`. So in case you are using the free Heroku DB you might have to "rename" it to `default` by simply removing the database and readding it with the name `default` using the same env var containing the connection string (should be `HEROKU_DATABASE_URL`). 

Do let us know if this works for you or if things aren't clear.

**Comment by jagyas** [comment]
hello @rikinsk it seems that Heroku do not allow to change database name in any plan as it is a database as a service and managed by Heroku. Is there any other workaround present as of now? Why this restriction of db name is there at first place? Generally databases do not have names as "default".
Thanks

**Comment by rikinsk** [comment]
Hey. I actually meant the name with which the database is added to Hasura. 
![Screenshot from 2021-03-11 13-08-52](https://user-images.githubusercontent.com/54616969/110752509-60ad1700-826b-11eb-9e65-197ff1aec593.png)
As you can see we have a heroku database added here  with the name `herokuapp-afternoon-crag-76643`. You can just remove the database and readd it with the name `default`
![Screenshot from 2021-03-11 13-12-35](https://user-images.githubusercontent.com/54616969/110752709-a669df80-826b-11eb-9f52-bdd93da31a2f.png)

The requiement for the name `default` is just because the migration files were created for a pre-2.0 project which to maintain backwards compatibility are applied to a db called `default` in v2.0 projects

**Comment by jagyas** [comment]
@rikinsk sorry for confusion. Thank you it is working fine now.

**Comment by mrcampbell** [comment]
This was it.  I didn't find anything in the docs, or in searching to find this.  Thanks for your help!
