### ISSUE TITLE
Inherited roles should use maximum row limit

### ISSUE THREAD

**Issue by sfcgeorge** [hasura/graphql-engine#6671]
To me inherited roles means _more_ privilege, but using the minimum of the row limits seems like the opposite. I would like it to use the maximum of the row limits.

That way if you have a limited public role with strict limits, then a logged in role with broader permissions, you could have an inherited role combining both. For example the public role might have a row limit of 20, but a logged in role might have a limit of 1000 for a stats dashboard. Currently combining those with an inherited role is useless because your stats would be limited to 20.

I imagine it was made to take the minimum to be cautious with performance. But that would only really matter if an inherited role was used in a logged out context so someone mischievous could try to DOS the site. But mostly I think inherited roles will be used for logged in users so it's not a concern. Perhaps you could add a config flag / env var to enable either min or max if there's demand for it.

**Comment by codingkarthik** [comment]
Hello @sfcgeorge ,

Thanks for reporting this issue. You make sense with your arguments about why it should be the maximum row limit instead of the minimum row limit, but I guess there will be users who will still prefer the minimum. So, I was thinking we can solve this by letting the users decide for themselves by accepting a `customization` parameter while adding an inherited role. Something like, 

```json
{
   "type": "add_inherited_role",
   "args": {
      "role_name": "sample_inherited_role",
      "role_set": [ "role1", "role2"  ],
      "customization": {
          "limit": "min" or "max"
       }
   }
}
```

We can default `limit` depending upon what the users want. But, at the same time I'm thinking if it makes sense to customize it per inherited role or should it be a global configuration which applies to all the inherited roles. 
@tirumaraiselvan @0x777 What do you folks think about this?

**Comment by sfcgeorge** [comment]
The customisation sounds nice though I'm struggling to think of an example when you'd want the more limited minimum. Hopefully someone will give a use case so you don't have to implement based on a guess :) 

You'll have to think about what to do if one base role has a limit but the other doesn't. I suppose with min it just uses the limit, but with max it would be unlimited? I think that's what I'd like.

Another possible config could be `sum`. Since the rows are the set union of permitted rows, the limit would then be the union of limits which seems consistent. Not sure how useful it would be in practice though, maybe wait and see if anyone asks for it.

**Comment by tirumaraiselvan** [comment]
Inherited roles now use `max`: https://github.com/hasura/graphql-engine/commit/7be8003a4b656710baf62a989d7cf71e8a41d802
