### ISSUE TITLE
No longer able retrieve my tenant id via the hasura cloud api

### ISSUE THREAD

**Issue by austinrivas** [hasura/graphql-engine#6676]
Hello, I can no longer retrieve my tenant id via the hasura cloud api. 

This is impacting our CI env and our ability to deploy our application.

Previously we were using the following query to get a tenant id via the project slug.

```gql
query retrieveTenant ($slug: String!) {
  tenant (where: { slug: {_eq: $slug } }) {
      id
      slug
      project {
        id
        endpoint
      }
    }
}
```

We get the following error when running this query:

```sh
Error: [{"extensions":{"path":"$.selectionSet.tenant","code":"validation-failed"},"message":"field \"tenant\" not found in type: 'query_root'"}]
```

What is the recommended best practice for retrieving the `tenant` id now?

Also, what is the best place to stay up to date on breaking changes to the cloud api?

**Comment by robx** [comment]
This sounds like an authorization issue. (The `tenant` field doesn't exist because the client isn't authorized to see it, not because it went away.) Could you share more details on how you're accessing the cloud API? What endpoint, what headers, etc.

For what it's worth, the following worked for me: First generate a personal access token in my hasura cloud account, then

```
$ pat=<paste token value>
$ curl -H "Content-Type: application/json" -H "Authorization: pat $pat" https://data.pro.hasura.io/v1/graphql -d '{"query": "query { tenant { slug } }"}'
```

(I also tried the full query above successfully.)

**Comment by austinrivas** [comment]
@robx it seems like this was a temporary issue with the api, it resolved itself after a couple days

**Comment by robx** [comment]
Ah thanks for the update!
