### ISSUE TITLE
Inconsistent Postgres triggers from metadata Event Triggers - blocks applying migrations

### ISSUE THREAD

**Issue by EdNutting** [hasura/graphql-engine#6762]
Hi,

This is a thorny corner case @rossng and I ran into...

## Starting state

* We had a table called Reactions. 
* This table had a column called `duplicateId`. 
* We also had INSERT/UPDATE/DELETE Event Triggers for this table.

## The changes

1. We deleted the Event Triggers (this is a Metadata change -- more on this in a moment)
2. We deleted the `duplicateId` column (this is an SQL Migration)
3. As part of later changes, we ran a _manual_ SQL migration that updated rows in the Reactions table

This all worked fine as a step-by-step in development. Then we moved to testing...

## The failure

We tried to jump one of our staging environments from the "starting state" to the end state, by applying migrations. This failed with a very unexpected error message: `...record "old" has no field "duplicateId".`

## What's gone wrong here

Applying migrations executed column deletion (step 2) and the UPDATE (step 3) -- but the Update failed, because it triggered the Postgres "update" trigger -- the one created by the Hasura Event trigger. The postgres trigger has an explicit reference to the `duplicateId` column. Ouch!

The problem here is that the Metadata change has not recorded the migration it applied (i.e. deleting the postgres trigger) and so is out of sequence (since metadata updates have to be applied after migrations for them to work).

The metadata changes to delete the Event Triggers are not just metadata changes - they really need to be SQL migrations. 

## A solution

Metadata changes that result in changes to the Postgres schema(s) should save associated migrations - such as creation, update or delete of triggers associated with Event Triggers.

**Comment by Naveenaidu** [comment]
Heya @EdNutting, thanks for the detailed bug report :) I had a few questions that I would like to clarify.

IIUC, in your **development environment** you did the following things:
1. Delete the event triggers
2. Delete the `duplicateId` column
3. Run some _manual_ SQL migration

In this case, everything worked fine.

The problem occurred in **staging environment**.  Quoting from the issue description
> We tried to jump one of our staging environments from the "starting state" to the end state, by applying migrations.

Can you please clarify what the "starting state" is?

Also, what does your migrations include?
* Is it from the Delete event triggers steps (OR)
* Does it include only step 2 and step 3 which is to delete the column and apply some migrations?

I ask the above question, because I was confused about the following line ^^'
> Applying migrations executed column deletion (step 2) and the UPDATE (step 3) -- but the Update failed

This seems to suggest to me, that the migrations you run in a staging environment only include two steps:
1. Delete `duplicateId` column (AND)
2. SQL migrations that updated rows in the Reactions table

> The problem here is that the Metadata change has not recorded the migration it applied (i.e. deleting the Postgres trigger)

FWIW, whenever an event trigger is deleted, Hasura does clean up and delete the Postgres trigger that was associated with it.

> Metadata changes that result in changes to the Postgres schema(s) should save associated migrations - such as creation, update or delete of triggers associated with Event Triggers.

Forgive my ignorance and please do correct me if I'm in the wrong here, do you mean to say that:
Whenever a Postgres schema change occurs, Hasura should automatically update the event triggers so that it reflects the new schema. For eg: Assuming that you did not delete the event triggers on the `Reactions` table and you deleted the `duplicateId` column, which will update the Postgres schema. Hasura needs to detect this schema change and update the existing event triggers on the table to conform to the updated Postgres schema?

If that is the case, I want to bring to your attention that it is not the intended behaviour of event triggers. i.e Hasura does not update the event trigger if the postgres schema changes. You would have to delete the event trigger first and then after the migrations are applied - recreate the event triggers :)

Please let me know if I have misunderstood it.

**Comment by rossng** [comment]
> Forgive my ignorance and please do correct me if I'm in the wrong here, do you mean to say that:
> Whenever a Postgres schema change occurs, Hasura should automatically update the event triggers so that it reflects the new schema. For eg: Assuming that you did not delete the event triggers on the Reactions table and you deleted the duplicateId column, which will update the Postgres schema. Hasura needs to detect this schema change and update the existing event triggers on the table to conform to the updated Postgres schema?

> If that is the case, I want to bring to your attention that it is not the intended behaviour of event triggers. i.e Hasura does not update the event trigger if the postgres schema changes. You would have to delete the event trigger first and then after the migrations are applied - recreate the event triggers :)

No, I don't think this is necessary. But schema changes _triggered by metadata changes_ should be applied in the correct order relative to other schema changes.

**Comment by Naveenaidu** [comment]
@rossng thank you for the explanation. A quick question, Are you using Hasura CLI to apply the migrations in your production/staging environment ? If so which config version are you using ?

**Comment by rossng** [comment]
When this issue was opened, we were using https://github.com/GavinRay97/hasura-ci-cd-action and config v2. That has changed now.
