### ISSUE TITLE
[v2.0.0-alpha.7] Cannot use `distinct_on` in conjunction with `order_by` on a joined column

### ISSUE THREAD

**Issue by http-teapot** [hasura/graphql-engine#6778]
The following query used to work pre-v2 and no longer works in v2.0.0-alpha.7

## Malfunctioning query

```graphql
query MyQuery {
  class(
    distinct_on: instructor_id,
    order_by: {
      instructor_id: desc,
      instructor: {total_followers: desc}
    },
    limit: 20
  ) {
    id
  }
}

```

## Error

```
{
  "errors": [
    {
      "extensions": {
        "path": "$.selectionSet.class.args",
        "code": "validation-failed"
      },
      "message": "\"distinct_on\" columns must match initial \"order_by\" columns"
    }
  ]
}
```

Any way I can export the queries? I clicked on Analyze and the UI showed the same error.

**Comment by nicuveo** [comment]
Hi! Thanks for the bug report.

There's an easy workaround for this problem, which is to list the `order_by` has a list of objects with only one field, like we do in the [documentation](https://hasura.io/docs/latest/graphql/core/databases/postgres/queries/sorting.html#sorting-by-multiple-fields). Namely:

```graphql
query MyQuery {
  class(
    distinct_on: instructor_id,
    order_by: [
      {instructor_id: desc},
      {instructor: {total_followers: desc}}
    ],
    limit: 20
  ) {
    id
  }
}
```

I'll keep investigating to see why this worked pre-v2 and what to do about it!

**Comment by nicuveo** [comment]
So! The problem lies in the fact that [input objects are unordered](http://spec.graphql.org/June2018/#sec-Input-Object-Values); meaning, as far as the GraphQL spec is concerned, there's no difference between `{a: desc, b: desc}` and `{b: desc, a: desc}`. That's the reason why we use a list for `order_by`: a list is ordered.

The reason why this used to work pre-v2 is that the previous implementation actually preserved the order of fields in an input object throughout the parsing phase, meaning we would **accidentally** do what the user expected. During our v2 cleanup, we changed how we parse queries, and now the code loses the order of fields within an input object (one of the reasons why: we represent the fields of an object with a hashmap, while we used to use an assoc list pre-v2), which we deemed fine since the spec clearly states that the fields are unordered.

We did a quick proof of concept to see whether it was worth it to adapt our new system to actually preserve the order of fields; it turned out to be quite complicated, and introduced a lot of changes to support something that is not part of the spec. In the end, since there is already a proper syntax for `order_by` using a list of objects, we have decided **not to fix this**.

We will, however, in the near future, add an error message for queries that have multiple fields in an `order_by` input object, which will explain why this is dangerous, and suggests a possible correct syntax for the query; something along the lines of:

```
GraphQL input objects are unordered, the order in which those fields will appear
in the ORDER_BY statement is not guaranteed to be the same as the one in which
they appear here. To list several fields you can use the list syntax:
  found:     {a: desc, b: desc}
  suggested: [{a: desc}, {b: desc}]
```

**Comment by paf31** [comment]
I ran into this with where clauses today. I think it's especially confusing because Graphiql will output an object, not an array of objects. So if I understand right, the default in Graphiql is to construct the wrong thing, which I do think is a bug.
