### ISSUE TITLE
Add support for CockroachDB

### ISSUE THREAD

**Issue by orefalo** [hasura/graphql-engine#678]
Or any distributed/replicated SQL db alike...

**Comment by karibertils** [comment]
would be interesting

**Comment by vroad** [comment]
CockroachDB doesn't support triggers at this moment.
Could Hasura implement event triggers without built-in DB support?

Even if that's possible, events won't be fired if you modify the DB directly.

https://github.com/cockroachdb/cockroach/issues/28296

**Comment by vroad** [comment]
Latest version of CockroachDB now offers support for experiential change feed.
https://www.cockroachlabs.com/docs/v19.1/changefeed-for.html

Could this be used instead of SQL triggers?
I'm not sure if current Hasura implementation assume that trigger is always available regardless of the database you use, though.

**Comment by hiralsp** [comment]
Is the only thing that's broken is webhooks for db change events?  Does everything else work with CockroachDB ?

**Comment by marionschleifer** [comment]
Hi everyone 👋 this is to let you know that we are aware of the community's request for support for CockroachDB. We will take this up in a few weeks 🙂

**Comment by hiralsp** [comment]
Any update here?

**Comment by gnanakeethan** [comment]
any updates here?

**Comment by tirumaraiselvan** [comment]
Hey everyone, so we did an initial investigation and Hasura doesn't start on CockroachDB out-of-the-box because of Cockroach's different implementation of internal schema and lack of few json operators.

Although now we have more insights into what will go into supporting CockroachDB and we will update this issue when we have a technical spec ready.

**Comment by guru2228** [comment]
any updates on this

**Comment by hiralsp** [comment]
please update, thank you!

**Comment by nvcnvn** [comment]
@tirumaraiselvan sorry for the noise.
Do you have a draft technical spec somewhere already? Me and my team are willing to work on this (ofc with guidance, none of us know Haskell).

**Comment by madasebrof** [comment]
Plus one for support for CockroachDB! 😄

**Comment by nmabhinandan** [comment]
Any updates?

**Comment by fritzblue** [comment]
> Or any distributed/replicated SQL db alike...

@orefalo Hasura does support [YugabyteDB](https://www.yugabyte.com/), which is a distributed SQL database with a Postgres-compliant API.

Here is [a tutorial](https://docs.yugabyte.com/latest/develop/graphql/hasura/) on using Hasura and YugabyteDB together.

Yugabyte has a [hosted cloud offering](https://www.yugabyte.com/cloud/) that starts with 5GB of storage and 3 nodes on the free tier.

**Comment by ChristianHohlfeld** [comment]
> Hi everyone 👋 this is to let you know that we are aware of the community's request for support for CockroachDB. We will take this up in a few weeks 🙂

any updates on this? Thank's!

**Comment by Bessonov** [comment]
I use CockroachDB at work and YugaByte for a personal project. Both are great until now, but also different. With YB you get better compatibility to Postgres and with CRDB you get a very easy management, scaling and stability (more mature than YB, bug not mature as PG).

In general, I prefer tools which I can use in both projects and it would be nice if hasura supports CRDB too. So, the question is, what prohibits usage of CRDB? It's the syntax or missing features like triggers?

As a workaround I can imagine to use [custom resolvers](https://hasura.io/learn/graphql/hasura/custom-business-logic/2-remote-schemas/) to fetch/update CRDB for example with knex or some ORM. Is this the way to go until CRDB is supported?

> CockroachDB doesn't support triggers at this moment.
> Could Hasura implement event triggers without built-in DB support?
> 
> Even if that's possible, events won't be fired if you modify the DB directly.

I'm not hasura user yet, but I would like to ask which events are important here? Can it work for migrations?

**Comment by tonyabracadabra** [comment]
Would Hasura support any PostgreSQL compatible databases like TiDB or PolarDB?

**Comment by alexandrim0** [comment]
Vote for CockroachDB!
Thank you!

**Comment by rrjanbiah** [comment]
FWIW, as someone mentioned here, https://github.com/yugabyte/yugabyte-db already supports Hasura. It is a competitor to the CockroachDB.

1. https://docs.yugabyte.com/latest/comparisons/
2. https://docs.yugabyte.com/latest/comparisons/cockroachdb/
3. https://docs.yugabyte.com/latest/develop/graphql/hasura/
4. #411

**Comment by dwstevens** [comment]
Vote for CockroachDB!

**Comment by adamfeldman** [comment]
Just for fun, I tried connecting `hasura/graphql-engine:v2.0.0-alpha.6` to CockroachDB V20.2.6 using Hasura 2's support for multiple databases. I got a "connection error" with "constraint-violation":

`
{"type":"pg-client","timestamp":"2021-03-25T19:49:53.955+0000","level":"warn","detail":{"message":"postgres connection failed, retrying(0)."}}
{"type":"pg-client","timestamp":"2021-03-25T19:49:53.955+0000","level":"warn","detail":{"message":"postgres connection failed, retrying(1)."}}
{"type":"http-log","timestamp":"2021-03-25T19:49:53.955+0000","level":"error","detail":{"operation":{"user_vars":{"x-hasura-role":"admin"},"error":{"internal":[{"definition":"cr","reason":"connection error","type":"source"}],"path":"$.args","error":"connection error","code":"constraint-violation"},"request_id":"7acaf279-5fed-4069-a521-c265c242cee5","response_size":151,"query":{"resource_version":null,"args":{"name":"cr","configuration":{"connection_info":{"database_url":"postgresql://hasura@localhost:26257/postgres","pool_settings":{}}}},"version":1,"type":"pg_add_source"}},"request_id":"7acaf279-5fed-4069-a521-c265c242cee5","http_info":{"status":400,"http_version":"HTTP/1.1","url":"/v1/metadata","ip":"172.19.0.1","method":"POST","content_encoding":null}}}
`

**Comment by h-parker-higgins** [comment]
Another vote for CockroachDB!

**Comment by egorsmkv** [comment]
Also a vote for CockroachDB.

**Comment by gerwim** [comment]
And another vote!

**Comment by fkmatsuda** [comment]
Vote for CockroachDB!

**Comment by samiujan** [comment]
any update on this?

Voting for CockroachDB!

**Comment by bamne123** [comment]
any update on this?

Voting for CockroachDB!

**Comment by orefalo** [comment]
Closing this issue - I opened it more than 3 years ago yet support has not been implemented.
I believe the enablement is more political than technical. Besides, in the last 3 years, the landscape for distributed sql db that can speak Postgres or MySQL has grown significantly: TiDB, ClickHouse and even the core Postgres platform have made significant steps forward. Using other libraries, you can achieve the desired outcome.

Hope this helps,
Sincerely,
Olivier

**Comment by Bessonov** [comment]
> I believe the enablement is more political than technical.

Strongly disagree with this statement. Beside that due to linked issue on CRDB side it's technically impossible, it doesn't make much sense. I use now both products (but not together) and both products are great. But without deep support of postgres features like triggers you don't get much power from hasura side and you go right into a dead end. How do you want validate your incoming data? How do you want react on data changes? All that isn't possible with hasura + crdb. Of course you can limit you to some select queries with permissions and handle all stuff with custom backend code... but why? It is a good trade-off to introduce additional component like hasura?

I had great success with hasura + YugaByteDB. But slow migrations make development a little bit uncomfortable. BTW, migrations in crdb aren't faster.

**Comment by vy-ton** [comment]
Hi, PM from Cockroach Labs here.

> But without deep support of postgres features like triggers you don't get much power from hasura side and you go right into a dead end.

We're collecting use cases for triggers, so I would love to learn more about the specific trigger functionality Hasura requires and how you're using them.

**Comment by Bessonov** [comment]
Hi @vy-ton! I think general trigger usage is well explored. AFAIK hasura on it's own doesn't require triggers at all. But for me the whole point of hasura is to avoid custom backend logic beside hasura and database. This works very well, especially with declarative permission model, API and triggers I can avoid a lot of (boilerplate) code. In fact, currently I don't have any custom backend code at all and ATM less than 1000 LOC of sql/plpgsql code, even it's very verbose (but well I see some features coming, like payment, which are impossible without backend. Not related to your question directly, but to hasura usage: https://github.com/hasura/graphql-engine/issues/7012, https://github.com/hasura/graphql-engine/issues/7159).

My use cases for triggers are:

1. Auditing

I've very similar construct to [Auditing actions on tables in Postgres](https://hasura.io/docs/latest/graphql/core/guides/auditing-tables.html), see also linked audit.sql. But there are some differences, which makes usage of hasura very powerful to me. I create not only auditing events with additional information, but also collect users who are interested in this information. For example, if a team name is changed, then all team members are interested in this event. I have a more structured view `updates` to this information and subscribe to the changes with hasura and websocket. It's very similar to [this blogpost](https://hasura.io/blog/building-an-offline-first-web-app-with-rxdb-hasura/#pull-query), but instead of watch for multiple entities and do expensive permission checks I watch only on this view, which _feels_ very efficient for short polling used by hasura.

2. Validation

There are multiple relevant use cases, which can't be implemented as check constraints. For example, if a `car` entity can be connected to not more than four `wheel` entities. And if there less than 4 wheels, then the car can't be set to `available`. Probably, not the best example, but I think that makes use case clear. This makes the database more robust against unintended manual/migrations changes.

3. Synchronize `updatedat` column

I think this is clear. I course there are other ways to implement that, for example with `on duplicate` or I think hasura offers some functionality for this. But I go with triggers to have it built-in.

4. Fill related data

For example, if a user creates a team, then a trigger adds `manager` permission to the user for that team. (And related to 2.: it's impossible to remove all `managers` from a team). There are another use cases related to user insertion and data filling, but they are similar.

**Comment by SkinyMonkey** [comment]
https://3factor.app/

**Comment by andreasgan** [comment]
Cockroach just launched a serverless offering we are considering to use. I want to bump this as it would be interesting to use that service along with hasura.

**Comment by otan** [comment]
CockroachDB dev here -- I have a limited subset of Hasura working on a local branch (https://github.com/cockroachdb/cockroach/issues/72407) but requires changes on both Hasura and CockroachDB to make it possible.

We'd like to partner on Hasura on the next steps to get this "to production" and hope to get this up and running soon.

**Comment by sethgw** [comment]
+1 We're looking for this support

**Comment by c-nv-s** [comment]
considering that we have had a response from both a project manager and developer from cockroach labs give input on this ticket saying they are interested in making this a reality ( and there is progress ), is it not possible to either reopen the ticket or create a new one to track this to fruition?

**Comment by KempWatson** [comment]
Why is this closed? The Hasura website even points to this page as active!

https://hasura.io/docs/latest/graphql/core/databases/postgres/index/

**Comment by adamfeldman** [comment]
As an outsider, it appears that Yugabyte and Hasura partnered in some way around June 2021 ([Yugabyte blog](https://blog.yugabyte.com/yugabyte-and-hasura-make-it-easier-to-build-complex-global-applications/), [Hasura blog](https://hasura.io/blog/postgresql-flavors-extensions-work-with-hasura/)). CockroachDB and Yugabyte are fairly direct competitors. 

As a user of both projects, it's unfortunate that Hasura won't engage with [the Cockroach team here in the open-source workflow on GitHub](https://github.com/hasura/graphql-engine/issues/678#issuecomment-971138408).

**Comment by c-nv-s** [comment]
well it would be nice if someone from the hasura team could explicity declare that they are no longer open to pursuing this effort. Or if anyone from the cockroachdb team could mention if they no longer have an interest in the effort.

**Comment by jannehietamaki** [comment]
I really wanted to use Cockroach in my project, but ended up using Yugabyte because of some kind of Hasura compatibility. Life is not perfect with Yugabyte either, but I'm pretty sure Cockroach Postgres compatibility is so far from being at required level this is not going to happen in the near future.

Also with Yugabyte there are some nasty issues where both Hasura and Yugabyte have tickets but they can't co-operate to get the problem fixed. For example https://github.com/hasura/graphql-engine/issues/3549

**Comment by otan** [comment]
Hi everyone! CockroachDB dev again - sorry for the slow follow up here.

Last I've heard, Hasura is currently working towards making integrations with other databases easier. As soon as we get updates on that, we (on the CockroachDB side and in partnership with Hasura) can look to get the ball moving on this again.

(as always, we're also looking at bridging the PG-CRDB gap which will also help)

**Comment by DaxGoon** [comment]
I am following this as this is something I want as well. 
Add CockroachDB support.

**Comment by thewillhuang** [comment]
yes please

**Comment by dameleney** [comment]
In case you didn’t hear at [Roachfest](https://roachfest.cockroachlabs.com/) today!!!

Hasura is pleased to announce work is in progress to release CockroachDB as a supported database for the community. We are planning to support queries, mutations, relations, and subscriptions. Now you can have instant GraphQL with one of the most cutting edge distributed SQL databases in the marketplace.

🚀 [Sign me up for the beta!!](https://hasura.io/graphql/database/cockroachdb/)

**Comment by dameleney** [comment]
We are pleased to announce the beta release for CocroachDB datasource on the Hasura GraphQL Engine for Hasura CE, Cloud, and EE in v2.15. 🚀 🚀 🚀 Beta release for v2.15 is expected to take place Monday 10/31.

In this beta release Hasura supports Queries and Mutations with plans to add support for subscription before the GA release, which will coincide with the release of CockroachDB v22.2 (tentatively scheduled for early December).

CockroachDB is a distributed SQL database built on a transactional and strongly-consistent key-value store. It scales horizontally; survives disk, machine, rack, and even datacenter failures with minimal latency disruption and no manual intervention; supports strongly-consistent ACID transactions; and provides a familiar SQL API for structuring, manipulating, and querying data.

Together with Hasura, CockroachDB now supports: Instant GraphQL & REST APIs, Declarative Role Based Authorization, Advanced Security and Performance with rate limiting, allow lists, and caching.

**Comment by dameleney** [comment]
🎉💥 Excited to officially announce the beta release of CockroachDB on Hasura v2.15.0 currently available on cloud and oss versions of Hasura. Support for CockroachDB will be considered GA when the minimum required CockroachDB version, v22.2, which is currently in beta is released as GA and pushed to CockroachDB's managed solutions.

[Find out more in this blog post](https://hasura.io/blog/announcing-native-cockroachdb-integration/) or follow the instructions in the [CockroachDB docs](https://hasura.io/docs/latest/databases/postgres/cockroachdb/getting-started/docker/) to get started building with Hasura and CockroachDB today.

Coming soon!!! We are hoping to release support for subscriptions for CockroachDB in the coming weeks.
