### ISSUE TITLE
hasura cli: during migration overwrites existing database URL with old one

### ISSUE THREAD

**Issue by prashant-shahi** [hasura/graphql-engine#6788]
**CLI version**: `2.0.0-alpha.7`
**Platform**: Hasura Cloud
**Server version**: `v2.0.0-cloud.6`
**Old server version**: `2.0.0-alpha.7`
**Docs link**: https://hasura.io/docs/latest/graphql/core/migrations/migrations-setup.html#step-7-apply-the-migrations-and-metadata-on-another-instance-of-the-graphql-engine

It happens when I execute the query below.

```bash
hasura metadata apply ...
```

**Solution**
I was able to go around it by using the SQL schema dump directly from `migrations/default/<version-id>_init/up.sql` to the Hasura Cloud UI and then imported the metadata.

**Comment by scriptonist** [comment]
@prashant-shahi Just to understand correctly, when you do a `metadata apply` on your cloud instance. It overwrites metadata on cloud with an outdated database url right? Also, does this happen even after updating your local CLI project metadata with the correct database url?

**Comment by prashant-shahi** [comment]
@scriptonist Yes, you are right. It overwrites the new database URL mentioned in Hasura Cloud with the old database URL.

**Comment by scriptonist** [comment]
@prashant-shahi that behaviour is expected, by doing a `hasura metadata apply` we are effectively "replacing" the metadata on the server with the project metadata. The database connection string is also part of the metadata, so it'll be overwritten by whatever value we have in the CLI project.

So, once you have updated your metadata on the server (ie updated the database connection string), you should ideally do a `hasura metadata export`, which will write the updated metadata onto CLI your project. Now, the next time you do a `hasura metadata apply` it'll "apply" the new metadata.

Also, I would suggest using environment variables for configuring database connection strings rather than hard code values in metadata. This would also help in moving the project between environments ie dev -> staging -> prod

https://hasura.io/docs/latest/graphql/core/migrations/upgrade-v3.html#changes-needed-in-existing-workflows

**Comment by prashant-shahi** [comment]
yes, seems like environment variables was the way to go.

anyways, thanks for responding, @scriptonist
