### ISSUE TITLE
Horizontal scaling with event triggers

### ISSUE THREAD

**Issue by badrequest400** [hasura/graphql-engine#6844]
We've noticed an event in our production deployment that seems to have been delivered twice. Exact same eventId and payload for both. This has caused our system to enter a bit of a dirty state as we need to interact with 3rd parties based off the back of them.

We are suspicious that this has arisen as a result of us horizontally scaling out Hasura to 2 nodes on Heroku.

Are there any guarantees around event delivery when scaling Hasura horizontally? Are there any config options we could have a look at to try and get around an issue like this? Is there something we would need to do to keep the nodes in sync? Would this potentially be solved in v2.0 or on Hasura Cloud? Any help around this would be very much appreciated.

<img width="1126" alt="Screenshot 2021-04-28 at 14 55 08" src="https://user-images.githubusercontent.com/2377846/116420356-cfebc400-a835-11eb-815c-39e5dfce4cfa.png">

Both of these contained the exact same payloads including data, trace context, event metadata and headers.

**Comment by tirumaraiselvan** [comment]
Hi there

Yes, during scale up or scale down or restart events, it is indeed possible that event triggers deliver an event more than once. We have mentioned that event triggers are at-least once here: https://hasura.io/docs/latest/graphql/core/event-triggers/index.html#introduction

v2.0 has a big improvement to tackle these and the surface are for double delivery is really low but it is still possible (because a hasura instance trying to delivery an event might restart because of an external cue and hasura has no way to know if it has finished or not).

**Comment by badrequest400** [comment]
Hi @tirumaraiselvan,

Thanks for the quick response 👍 . If this is expected, then we will try to do somehting on our end to make the handler idempotent.
