### ISSUE TITLE
Hasura multiple mutations are not executed sequentially

### ISSUE THREAD

**Issue by victor-solvethex** [hasura/graphql-engine#6967]
I'm trying to execute a request with multiple mutations (one of them is an action that performs a post request against an API)
I want Hasura to sent the post request to my server only and strictly only if the first mutation goes right.

Example of my mutation: 

```graphql
mutation test_mutation {
  insert_site_images(objects: {url: "<url>", file_name: "<name>", mime: "image/png", active: true, area: "<area>"}) {
    affected_rows
  }
  fileUpload(name: "<file-name>", type: "image/png", base64str: "dGfkjdsfS") {
    success
  }
}
```

What I want to do is the following:

+ Insert a row on the db with info about an image which I want to upload to AWS S3
+ Then, if everything goes right, execute the `fileUpload` action. 
+ If the action goes wrong (returns a 400 code) then rollback the previous mutations (in this case the insert)

The thing is that Hasura is triggering the action before receiving a response from the insert mutation.
The docs explicitly say: `If multiple mutations are part of the same request, they are executed sequentially in a single transaction. If any of the mutations fail, all the executed mutations will be rolled back.`

Thanks!

**Comment by nicuveo** [comment]
Hi @victor-solvethex! Thanks for the bug report.

Can you confirm that this is happening on version 1.3? We haven't been able to replicate this on 2.0.

**Comment by victor-solvethex** [comment]
@nicuveo This is happening in 1.3.3, should I update to 2.0 alpha? We are using the dockerized version of Hasura

**Comment by nicuveo** [comment]
So! Transactions are complicated.

### What's happening in 1.3?

In 1.3, the entire mutation is run in a postgres transaction, which means every _root field_ is processed, THEN the transaction is committed. So, the following GraphQL mutation:

```graphql
mutation test_mutation {
  insert_pg_table_1(objects: ...) {
    affected_rows
  }
  insert_pg_table_2(objects: ...) {
    affected_rows
  }
  call_sync_action(...) {
    success
  }
}
```

results in the following execution steps:
- begin transaction
- insert table 1
- insert table 2
- call the action (the transaction hasn't been committed yet!)
- commit transaction

This results in the problem you describe: when the action is called, the transaction hasn't been committed yet. If one of the two inserts fail, they're both gonna be rolled back, but the action call itself can't be. So what does 2.0 do differently?

### What's happening in 2.0?

Amongst the many changes in 2.0, there can now be more than one database in your schema; meaning that in the example query above, "pg_table_1" and "pg_table_2" might be on two different postgres databases! As a result, we have slightly relaxed the transaction semantics: a GraphQL mutation is executed as a transaction IF AND ONLY IF:
 - all the fields are database mutations (no actions, no remote mutations)
 - all those mutations go to the same Postgres database

otherwise, the mutation is executed step by step, and stops on the first failure.

If we send the same query as above, it will NOT qualify for transaction "promotion": one of the fields is an action call. So the same query will result in the following steps:
- insert table 1; continue on success, abort on error
- insert table 2; continue on success, abort on error
- call the action (guaranteed to happen only if both inserts have succeeded!)

However, the downside of this approach is that the two inserts are not in a transaction: if the second fail, the first will not be reverted. I guess that's fine for your use case if you have only one mutation before the action call?

Is there however a way we could have transaction semantics ONLY for those inserts, and then guarantee that the action is called when the transaction is committed? Well...

### The future?

...no, not yet. But what I hope we can do one day is implement [explicit transaction semantics](https://github.com/nicuveo/graphql-engine/blob/breaking-changes-rfc/rfcs/graphql-breaking-changes.md#explicit-transaction-semantics) (note that this is a RFC draft and NOT an official feature announcement ^^'). With explicit transactions, it'd be possible to do something like:

If it were possible to do something such as:
```graphql
mutation test_mutation {
  transaction {
    insert_pg_table_1(objects: ...) {
      affected_rows
    }
    insert_pg_table_2(objects: ...) {
      affected_rows
    }
  }
  call_sync_action(...) {
    success
  }
}
```

then we'd have the best of both worlds.
