### ISSUE TITLE
server/postgres: use computed fields in permission check/filter

### ISSUE THREAD

**Issue by rakeshkky** [hasura/graphql-engine#7102]
This issue follows https://github.com/hasura/graphql-engine/issues/7100. Support computed fields in filter/check boolean expressions of permission metadata APIs.

**Comment by dminkovsky** [comment]
Really looking forward to this.

This should probably limit to SQL functions? Or at least warn if it's not SQL? 

I recently had a computed field used in generated SQL (in another context, obviously, since this isn't possible yet), and because the function wasn't SQL, the query planner totally failed and performance dramatically exploded: After I changed the language to SQL the planner cost went from 500,000 to 20.

https://stackoverflow.com/questions/51821053/optimize-postgresql-query-with-slow-and-bad-estimate-on-function-scan-and-nested/51821306#comment106053060_51821053 
and
https://stackoverflow.com/questions/51821053/optimize-postgresql-query-with-slow-and-bad-estimate-on-function-scan-and-nested/51821306#comment106053019_51821306

**Comment by rakeshkky** [comment]
@dminkovsky Thank you.

There's a performance compromise in using Postgres functions in `WHERE` expression. We didn't evaluate the execution performance for difference `LANGUAGE` types. We'll do that and document the performance limitation and few workarounds at docs.hasura.io.

**Comment by 0x777** [comment]
server support has been added in v2.0.4. This issue tracks the console support: https://github.com/hasura/graphql-engine/issues/7336.
