### ISSUE TITLE
server: unify CI and local integration test setup

### ISSUE THREAD

**Issue by sassela** [hasura/graphql-engine#7140]
_Issue split from https://github.com/hasura/graphql-engine/issues/6951_

Different parts of the test suite rely on different assumptions: that there's a version of graphql-engine running, that it was started with some specific environment variables, that the proper environment variables are set... And there isn't one consistent way of running the tests; the CI uses a verbose `run-tests.sh`, which runs all or parts of the test suite with different configurations, while locally, for devs, `dev.sh test --integration` is the preferred way. This leads to a lot of complexity and errors:
- some tests are always skipped locally
- new tests can work on CI but break local workflows
- the CI is probably testing more than it needs by running the suite in each configuration
- the metadata database running separately from the tests means that it is persisted from one group of tests to the next, and that previous test failures can impact other unrelated tests down the line

_goal_: running the tests should be done the same way on CI and locally

_ideas for improvements_:
- Vamshi makes several proposals in [his RFC here](https://github.com/hasura/graphql-engine-mono/pull/3790)
- Dockerise the test environment for each backend, such that they can be spun up consistently across local and CI environments. [graphql-bench](https://github.com/hasura/graphql-bench/blob/master/containers/docker-compose.yaml) illustrates how this is done in conjunction with Docker Compose

**Comment by sassela** [comment]
Relates to https://github.com/hasura/graphql-engine-mono/pull/2982: test failures occurring locally, but not in CI, due to inconsistent config between environments.

**Comment by abooij** [comment]
I like the goal of this issue. I'm not wholly convinced by the Docker-based approach that it suggests. I think there's genuine engineering work that can be done here before surrendering to adding another container to our setup.

For instance:
- _Why_ is there a difference between `run-tests.sh` and `dev.sh`?
- Can we reduce the difference by enabling or disabling tests on one side or the other?
- Can certain tests be re-engineered so that they can be run in a leaner environment? Can some of them perhaps even be phrased as Haskell property tests, or Haskell unit tests?
- Are certain tests perhaps superfluous due to internal refactors?

**Comment by sassela** [comment]
@abooij agreed. I've reworded "suggested improvements" to "ideas for improvements"

**Comment by gilligan** [comment]
I think that in order to start on this we will need to first come to a conclusion in https://github.com/hasura/graphql-engine-mono/pull/3790

**Comment by sassela** [comment]
closing this since the migration to the haskell test suite https://github.com/hasura/graphql-engine/issues/7760
