### ISSUE TITLE
mssql: columns with null values are omitted in the response

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#7181]
```graphql
query {
  User(where: {id: {_eq: 1}}) {
    id
    email
  }
}
```
would respond with 
```json
{
  "id": 1
}
```
and not 
```json
{
  "id": 1,
  "email": null
}
```
if `email` is `NULL` for the row with `id = 1`.

**Comment by sassela** [comment]
Closing as this issue was fixed in https://github.com/hasura/graphql-engine/commit/66f09eeaab2ad5a8da66668c79d8125855dcfcfb, merged yesterday. Test case at https://github.com/hasura/graphql-engine/commit/66f09eeaab2ad5a8da66668c79d8125855dcfcfb#diff-0ba849a7ea26374d98df474a242568fae425fdba67a7ffaed91248a25fac4e76R1 (I'll add a comment reference in the test to this ticket on Monday)
