### ISSUE TITLE
Allow for multiple entries with the same query name in allow-lists

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#7268]
As a query evolves, the selection set, or arguments might change, but the query name may remain the same.
We should relax the constraints on the allow-list collection to allow for "duplicate" entries.

**Comment by tirumaraiselvan** [comment]
Basically, if you have a query which has been added to a collection like this:


```
query MyQuery {
  users {
    id
    name
  }
}
```
and suppose you add a new column to users table and want to include it:

query MyQuery {
  users {
    id
    name
    age
  }
}

We need both the above queries to be part of the collection so that old apps can continue to use the first query and new apps can use the second query. But currently, we can't do this because there is a unique constraint on the operation name.
