### ISSUE TITLE
"or" in where clause is not correctly translated into the SQL query

### ISSUE THREAD

**Issue by dewulf** [hasura/graphql-engine#7386]
Dear Team,
thanks a lot for your wonderful and important work. I have found an issue with the following query:
```
query MyQuery {
  activities(where: {_or: {date: {_eq: "2021-08-12"}, backlogged: {_eq: true}}}) {
    id
    backlogged
    date
    description
  }
}
```

I expect to get all activities per date plus the ones that have backlogged = true. But it doesn't work that way. The generated SQL is as follows from the logs:
`SELECT  *  FROM \"public\".\"activities\"  WHERE (((\"public\".\"activities\".\"backlogged\") = (($2)::boolean)) AND ((\"public\".\"activities\".\"date\") = (($3)::date)))`
Instead of "or" it is used "and". Is this by design or is it a bug?

**Comment by dewulf** [comment]
Any comment on this?

**Comment by pijablonski** [comment]
`_or` takes LIST of expressions to join by SQL `OR`.
By passing object instead of an array, you use it as it would be a single-element array:
`where: {_or: [ {date: {_eq: "2021-08-12"}, backlogged: {_eq: true}}] }`
To acheive what you want, you should pass two objects, each with single property instead.

**Comment by 0x777** [comment]
@dewulf https://hasura.io/docs/latest/graphql/core/databases/postgres/queries/query-filters.html#using-multiple-filters-in-the-same-query-and-or

**Comment by dewulf** [comment]
Thanks a lot
