### ISSUE TITLE
bug: error on add graphql remote schema after version 2.0.4

### ISSUE THREAD

**Issue by dougg0k** [hasura/graphql-engine#7443]
Hi, when I try to add a graphql remote schema after version 2.0.4, meaning starting v2.0.5 this error appears. 

All I did was set the url and timeout to 30 and once I pressed the button, it returned that error. Before I had the schema already setup and working, but once I tried versions 2.0.5+, it gave the same metadata error when I tried to open the console.

Not sure if it's related, but the url I tried is `POST` only.

```
{
    "path": "$.args[0].args",
    "error": "Error in $.data: parsing HashMap ~Text failed, expected Object, but encountered Null",
    "code": "remote-schema-error"
}
```

**Comment by 0x777** [comment]
@dougg0k Just to confirm, you can add the remote schema on v2.0.4 but not from `v2.0.5`? Can you share the introspection result of your remote schema? You can use [gq](https://github.com/hasura/graphqurl#export-schema) for this.

**Comment by chrismaddalena** [comment]
@0x777 I am seeing the same error using Docker and `hasura/graphql-engine:v2.0.9.cli-migrations-v3`. I also tried the latest beta since it mentioned some changes related to remote schemas.

In my case, I have something close to what is described here: https://hasura.io/blog/how-to-setup-authentication-with-django-graphene-and-hasura-graphql/

I have a pre-existing PostgreSQL database with Django and Hasura set up with Python Graphene. I am trying to add a remote schema to support JWT authentication for the GraphQL API.

This comes back in the logs:

```
django_1          | INFO:     172.20.0.6:58160 - "POST /graphql HTTP/1.1" 200 OK
graphql           | {"type":"http-log","timestamp":"2021-10-01T17:09:33.541+0000","level":"error","detail":{"operation":{"user_vars":{"x-hasura-role":"admin"},"error":{"path":"$.args[0].args","error":"Error in $.data: parsing HashMap ~Text failed, expected Object, but encountered Null","code":"remote-schema-error"},"request_id":"f7a433c9-7203-4f17-8efb-36716549085c","response_size":149,"query":{"resource_version":156,"args":[{"args":{"definition":{"timeout_seconds":60,"url":"http://django:8000/graphql","headers":[],"forward_client_headers":true},"name":"Graphene","comment":""},"type":"add_remote_schema"}],"source":"default","type":"bulk"},"request_mode":"error"},"request_id":"f7a433c9-7203-4f17-8efb-36716549085c","http_info":{"status":400,"http_version":"HTTP/1.1","url":"/v1/metadata","ip":"172.20.0.1","method":"POST","content_encoding":null}}}
```

To investigate this as a potential issue, how can I help? I am unfamiliar with `gq`.

**Comment by kevinmichaelchen** [comment]
I'm also seeing a similar error on 2.15.1 (both CLI and server) when attempting to add a remote schema.
```
Error in $.data: parsing KeyMap failed, expected Object, but encountered Null
```

I have Hasura running in a container trying to reach `http://host.docker.internal:8081/query`, which is a Go app serving a [gqlgen](https://github.com/99designs/gqlgen)-powered GraphQL API on port 8081 on the host.
