### ISSUE TITLE
REST: queries should be validated after metadata changes

### ISSUE THREAD

**Issue by lorenzo** [hasura/graphql-engine#7497]
The REST API feature is a time-saver, it really helps put a working API together from a working GraphQL query.

I have noticed on occasion that when changing the underlying schema or metadata, no validation happens for the queries backing the REST api, which leads to errors.

For instance, we have a remote GraphQL schema that exposes some mutations, such as `orderCancel`. We exposed this query over REST:

```
mutation CancelOrder($orderRef: String!) {
  orderCancel(args: {ref: $orderRef}) {
    status
  }
}
```

We now deleted the remote schema, but there is not indicated in the metadata that this query still exists and that is now invalid!

I think REST queries should be validated against new metadata changes.

**Comment by nicuveo** [comment]
Hey @sordina, I talked with @paritosh-08 about this. I think there are a few points that we need to clarify / discuss before this can be done. Most importantly: what does it mean for a REST query to be "validated"? I see two possible answers:

#### 1. we only care about parsing

In this scenario, we define a REST query as valid iff _it can be parsed successfully_. It doesn't matter if it "means something different", as long as sending it again after the metadata change would result in some data being returned. In this scenario, if a REST query is selecting field "foo" from a table "bar", if the metadata were to be atomically changed so that the table previously known as "bar" is now "bar1", and a new table is now "bar", as long as it still has a field "foo" we would consider this query as "valid", because it could still be parsed, even if now it means something entirely different.

In this case, we don't need to do complicated metadata validation: it is enough to attempt to parse the stored queries again (although we are going to need to implement something to bypass variable validation).

#### 2. we want to do proper dependency analysis

Internally, we store a dependency graph of metadata objects. This is used in renaming operations, and for cascading changes: if table A depends on table B, then if table B is deleted and "cascade" is true, then A is deleted as well. We could use / extend this dependency graph to keep track of what a stored query depends on. Upside of this: answering the question of "was this REST query impacted" becomes trivial: we look at whether it appears in the dependents of any modified object. This is a bit more strict, but it involves more work: we are going to need to keep track, at parsing time, of which metadata objects are involved, which I think is ~1w of work (there's some subtlety involved in making sure we do this properly at schema parsers generation time).

Regardless, there's also the question of _what do we do with an invalidated query?_ Do we delete them, or do we have a way of maybe flagging one as "invalid", so that users can diagnose them / fix them?

I'm happy to provide more context on any of this / pair with @paritosh-08 on that work. :)

**Comment by kolharsam** [comment]
> Regardless, there's also the question of what do we do with an invalidated query? Do we delete them, or do we have a way of maybe flagging one as "invalid", so that users can diagnose them / fix them?

I think the idea we had in mind was to flag them as `inconsistent_metadata` and then the onus lies on the user to fix the queries / endpoints. 

cc @sordina @paritosh-08

**Comment by sordina** [comment]
@tirumaraiselvan What do you think we should do here? We're almost there in terms of the validity of the queries, but the variables problem is causing some implementation issues. Should we push through with the current approach, or take approach 2 suggested by @nicuveo ?

**Comment by paritosh-08** [comment]
Closed via https://github.com/hasura/graphql-engine/commit/00558666b12e5be34e73e4eb1155e8fa303f9f94
