### ISSUE TITLE
'user_vars' is missing in http-log even when there are errors

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#7532]
### Version Information

Server Version:
`<= 2.0.8`

### Environment

Cloud, OSS and EE

### What is the expected behaviour?

`http-log` should have `user_vars` when the user can be determined. 

### What is the current behaviour?

`http-log` does not have `user_vars` when an invalid json body is sent to `/v1/graphql`. 

### How to reproduce the issue?

The following query (valid) produces this log:

```bash
curl 'http://127.0.0.1:8080/v1/graphql' -H 'content-type: application/json' -H 'x-hasura-role: user' -H 'x-hasura-user-id: 1' --data-raw '{"query":"query { __typename }","variables":null}'
```

```json
{
  "type": "http-log",
  "timestamp": "2021-09-09T15:42:14.035+0530",
  "level": "info",
  "detail": {
    "operation": {
      "query_execution_time": 0.00120527,
      "user_vars": {
        "x-hasura-role": "user",
        "x-hasura-user-id": "1"
      },
      "request_id": "3cbd033c-1049-4ae7-ac17-ea5adf77b249",
      "response_size": 36,
      "query": {
        "variables": null,
        "query": "query { __typename }"
      },
      "request_mode": "single",
      "request_read_time": 2.253e-05
    },
    "request_id": "3cbd033c-1049-4ae7-ac17-ea5adf77b249",
    "http_info": {
      "status": 200,
      "http_version": "HTTP/1.1",
      "url": "/v1/graphql",
      "ip": "127.0.0.1",
      "method": "POST",
      "content_encoding": null
    }
  }
}
```

Note the presence of `user_vars` at `$.detail.operation.user_vars`. However, if we send an invalid json body as follows:

```bash
curl 'http://127.0.0.1:8080/v1/graphql' -H 'content-type: application/json' -H 'x-hasura-role: user' -H 'x-hasura-user-id: 1' --data-raw 'not-a-valid-json-query'
```
the log line is as follows:

```json
{
  "type": "http-log",
  "timestamp": "2021-09-09T15:45:11.362+0530",
  "level": "error",
  "detail": {
    "operation": {
      "error": {
        "path": "$",
        "error": "Error in $: string at 'not-a-valid-json-query'",
        "code": "invalid-json"
      },
      "request_id": "f3186318-4896-4b30-ad95-da0b01903601",
      "response_size": 91,
      "request_mode": "error",
      "raw_query": "not-a-valid-json-query"
    },
    "request_id": "f3186318-4896-4b30-ad95-da0b01903601",
    "http_info": {
      "status": 200,
      "http_version": "HTTP/1.1",
      "url": "/v1/graphql",
      "ip": "127.0.0.1",
      "method": "POST",
      "content_encoding": null
    }
  }
}
```

The `user_vars` section isn't present even when the information is part of the query. 

### Any possible solutions?

Is this even possible? We can't delay parsing the request body till we resolve the user information because we send the request body to the auth webhook. Should we instead log raw headers along with the raw query when the body cannot be parsed? It isn't exactly user information but the headers should help get the user information if need be.

**Comment by robx** [comment]
I had a look at this. The core reason why it's not easy to do is that in some cases (auth webhook), we parse the graphql request before resolving user info.

That's a bit of a weird dependency, coming out of https://github.com/hasura/graphql-engine-mono/pull/149 / https://github.com/hasura/graphql-engine/issues/2666. Could someone (@ecthiender, @evertedsphere) weigh in on why we chose to pass the parsed request instead of the raw request? (I remember running into this before, where it made code more confusing than necessary.)

Some ideas for how to solve this issue:
- pass the raw request to auth webhook
- special case error logging to include user info if we're not using a webhook

**Comment by evertedsphere** [comment]
@robx my rationale was that from the pov of someone consuming this from a webhook, people would probably want to match against a list of normalised/pretty-printed graphql query strings, instead of a single bytestring containing the entire request body (where different equivalent queries may additionally have e.g. whitespace irregularities). 

i did not receive a spec, so i picked this way of implementing the feature request and went ahead with it, and neither i nor any reviewers noticed this bug. i agree that this is an inconsistency in our apis, and, further, i suspect the fact that we parse _first_ because of that PR also has other implications (memory/resource usage) that i did not consider at the time. 

i was quite new to the codebase at the time and still getting my bearings; today i would certainly have thought through it more thoroughly — right now, it does look like a "weird dependency" at best, and concerning at worst. passing the raw request to the auth webhook does seem like the only "watertight" and sensible solution to me now.

since it was a PR of mine that introduced it, and i'm still reasonably familiar with the code paths, i'm happy to work on or help with a fix for it once we decide on a path forward.

**Comment by robx** [comment]
Cool. So I don't think this was an awful choice or anything, and I can see that normalizing the request body could be beneficial in some ways. But yeah if there's no deeper reason to need to parse the request early, sounds like a good idea to move the parsing to later.

**Comment by evertedsphere** [comment]
based on conversations with @ecthiender @robx:

first, we aren't _calling_ the webhook right now for queries that fail to parse! that is easily fixed, and the fix seems to ensure the expected behaviour.

second, auth webhooks do both authentication and authorization simultaneously, which i had not consciously realised until now. is this a good thing? 
it leads to the possibility of very counter-intuitive behaviour on the part of the webhook, perhaps due to error on the part of the person writing the webhook: e.g. the value of `x-hasura-role` depends on what query was sent. and since the webhook controls ... the entirety of hasura's security features, this is sort of equivalent to providing arbitrary (even if non-malicious) code execution within our auth{n,z} setup. i think it is important for us to restrict the expressiveness of auth webhooks so _weird_ things like this are forbidden by construction. 
we should definitely think about separating webhook authentication and authorisation, and perhaps impose certain invariants that webhooks are required to satisfy.

**Comment by ecthiender** [comment]
Fixed via https://github.com/hasura/graphql-engine-mono/pull/2604
