### ISSUE TITLE
Regression in 2.0.9: cannot upsert when column is GENERATED BY DEFAULT AS IDENTITY.

### ISSUE THREAD

**Issue by BenoitRanque** [hasura/graphql-engine#7557]
### Version Information

Server Version: 2.0.9
This issue is new in 2.0.9, and is not present in 2.0.8

### Environment

Issue confirmed on Cloud and OSS

### What is the expected behaviour?

The `<table-name>_insert_input` type should include columns that are `GENERATED BY DEFAULT`
This is important for upsert operations.

### What is the current behaviour?

The `<table-name>_insert_input` type does not include columns that are `GENERATED BY DEFAULT`

### How to reproduce the issue?

1. apply this migration and track the table:
```sql
CREATE TABLE public.person (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  name TEXT
);
```
2. Go to the api tab, and check out the `person_insert_input` type
![image](https://user-images.githubusercontent.com/25712958/133458805-ef1dc4a8-f4dc-4abb-b790-5b4db52ef366.png)
3. The id column is not present.

### Any possible solutions?

Reverting to 2.0.8 solves the issue

### Can you identify the location in the source code where the problem exists?

No

### If the bug is confirmed, would you be willing to submit a PR?

No, this is most likely haskell which I know precious little about

**Comment by plcplc** [comment]
A preliminary analysis suggests it's likely 7ca48decfb that is responsible for the change in behavior:

* It introduces distinction based on identity-column-ness
* it elides identity columns from insert schema
* it is introduced in 2.0.9

as per 7ca48decfb we currently determine identity-column-ness by the `is_identity` column only. It seems we ought to also consider the value of `identity_generation`, c.f. https://www.postgresql.org/docs/current/infoschema-columns.html.

**Comment by 24601** [comment]
> A preliminary analysis suggests it's likely [7ca48de](https://github.com/hasura/graphql-engine/commit/7ca48decfb3718301a2fcdf4515db70fc6f0d05d) that is responsible for the change in behavior:
> 
> * It introduces distinction based on identity-column-ness
> * it elides identity columns from insert schema
> * it is introduced in 2.0.9
> 
> as per [7ca48de](https://github.com/hasura/graphql-engine/commit/7ca48decfb3718301a2fcdf4515db70fc6f0d05d) we currently determine identity-column-ness by the `is_identity` column only. It seems we ought to also consider the value of `identity_generation`, c.f. https://www.postgresql.org/docs/current/infoschema-columns.html.

This is the second time in about a month that a Hasura bug fix has introduced an (unintentional) breaking change (but still breaking), and worse, auto-upgrades in production WITHOUT NOTICE and WITHOUT OPT-OUT mean we wake up to broken production systems. 

This is insane. Bugs happen, yes, that's reality, but silently slipping them into our production systems while we are sleeping and we wake up to a broken app because our vendor decided to bork our system (unintentionally, sure, but certainly preventable because you should NOT be silently upgrading our production systems no matter how much you think your code is bug free!). 

I keep pointing to the actual root cause as being "don't touch production systems without notice or opt-in to an upgrade, no matter how small" and Hasura keeps breaking our systems, what is this? Sadism? I feel like I'm taking crazy pills. 

https://github.com/hasura/graphql-engine/issues/7568

**Comment by plcplc** [comment]
For reference, the error a user gets if she does put in an `id` field is:

GraphQL:
```
mutation MyMutation {
  insert_person(objects: {id: 10, name: "hey"}) {
    affected_rows
  }
}
```

and error:

```
{
  "errors": [
    {
      "message": "field \"id\" not found in type: 'person_insert_input'",
      "extensions": {
        "code": "validation-failed",
        "path": "$.selectionSet.insert_person.args.objects[0].id"
      }
    }
  ]
}
```
