### ISSUE TITLE
Sample Docker Compose Install Manifest with MSSQL is actually using Postgresql

### ISSUE THREAD

**Issue by tafs7** [hasura/graphql-engine#7584]
In the repo (both in stable and master branches), the docker-compose file in the install manifest sample using **MS SQL** as a database is actually starting up a Postgresql container, not a "MS SQL Server on Linux" container.

The file in question is this:
https://github.com/hasura/graphql-engine/blob/1843ee7b0b914acfb5c29a219343f3b2fb2fbe9d/install-manifests/docker-compose-ms-sql-server/docker-compose.yaml

I assume this has gone unnoticed for this long because most of your userbase is targeting Postgresql, not MS SQL, so they've not even looked at this sample compose yaml as a resource.

I'll see if I can find some time to correct and open a PR to address this, but wanted to track it her for visibility.

**Comment by rikinsk** [comment]
@tafs7 This is actually intentional. Hasura needs a Postgres db to store its internal metadata. the docker-compose file adds this Postgres db as you see. The manifest is currently designed to be used with an existing mssql database which can be connected to Hasura from the Hasura console once Hasura is running. You can the [getting started with mssql](https://hasura.io/docs/latest/graphql/core/databases/ms-sql-server/getting-started/docker.html#database-ms-sql-server-docker) docs for more details.
