### ISSUE TITLE
Check costrain works only with lowercase

### ISSUE THREAD

**Issue by nico1996it** [hasura/graphql-engine#7735]
![telegram-cloud-photo-size-4-6039718136057542266-y](https://user-images.githubusercontent.com/24296003/139076680-34e76f52-9f4e-4787-bd9d-8aa89a9e962a.jpg)

As you can see, it always converts everything in all lowercase format, therefore if you check a column that is not completely lowercase you will get this error

**Comment by rikinsk** [comment]
This is because of the way Postgres treats identifiers. By default all identifiers are lowercased by Postgres if not wrapped with double-quotes. 

Fom the Postres docs: "Quoting an identifier also makes it case-sensitive, whereas unquoted names are always folded to lower case. For example, the identifiers FOO, foo, and "foo" are considered the same by PostgreSQL, but "Foo" and "FOO" are different from these three and each other."

For your case, updating the constraint to `"NAME" != null` should fix this.
