### ISSUE TITLE
The create scheduled event request does not return `event_id`

### ISSUE THREAD

**Issue by sakhmedbayev** [hasura/graphql-engine#7887]
### Version Information

Server Version:
2.0.10

### Environment

Node.js v14

### What is the expected behaviour?

https://hasura.io/docs/latest/graphql/core/api-reference/metadata-api/scheduled-triggers.html#create-scheduled-event

the create scheduled event request to return `event_id`

### What is the current behaviour?

getting back only `message` param, e.g.:

```
{ message: 'success' }
```

### How to reproduce the issue?

1.  create a scheduled event https://hasura.io/docs/latest/graphql/core/api-reference/metadata-api/scheduled-triggers.html#create-scheduled-event
2. observer the response

### If the bug is confirmed, would you be willing to submit a PR?

Unfortunately, do not have enough knowledge to do that

**Comment by BenoitRanque** [comment]
This was fixed in #7506 and released in 2.1.0-beta.1 per the [changeloangelog](https://github.com/hasura/graphql-engine/blob/master/CHANGELOG.md#v210-beta1)

**Comment by sakhmedbayev** [comment]
@BenoitRanque, I am not using the self-hosted version of Hasura. When will #7506 make it to Hasura Cloud? Here is what I see in the Hasura Cloud web console

<img width="300" alt="Screen Shot 2021-12-06 at 11 36 45 AM" src="https://user-images.githubusercontent.com/8005396/144885338-ce20c07b-a6ed-4226-97d3-9d0df400dc82.png">

**Comment by BenoitRanque** [comment]
Hasura cloud is updated automatically, and typically uses the latest stable version.
I cannot give a precise timeline at the moment, because there may be multiple beta releases before 2.1.0 becomes stable.

Once 2.1.0 becomes stable, it typically takes a week~ for an update to be deployed to hasura cloud.

In the meantime, you could use the undocumented `get_scheduled_events` api by sending a request to the metadata endpoint with the following body:
```json
{
  "type":"get_scheduled_events",
  "args":{
    "type":"one_off",
    "status":["scheduled"],
    "limit":10,
    "offset":0
  }
}
```
This is of course a work around, but it is an existing api you could start using today.
