### ISSUE TITLE
Support for Soft deletes

### ISSUE THREAD

**Issue by miradnan** [hasura/graphql-engine#8084]
### Describe the solution you'd like
Support for soft deletes

### Describe alternatives you've considered
Alternate option is to use a backend endpoint that handles soft deletes.

### If the feature is approved, would you be willing to submit a PR?
No. I haven't worked with Haskell language yet.

**Comment by raphaeltm** [comment]
You mention a backend endpoint, but could you not just add a `deleted_at` column to your tables, and prevent all access in permissions if `deleted_at` is set? That would essentially be a soft delete, no? Personally, I wouldn't want something baked into Hasura for soft deletes, because that feels like it's drifting a bit too close to application logic, which I don't think Hasura should be in doing. It feels too much like building a framework, rather than a data access layer.

**Comment by miradnan** [comment]
I agree. I didn't wanted to have it in where clause in each query. Adding condition within the permissions definitely works. Thanks!
