### ISSUE TITLE
Incorrect reload_metadata default value for reload_sources

### ISSUE THREAD

**Issue by jflambert** [hasura/graphql-engine#8244]
### Version Information

Server Version: 2.2.0

### Environment

OSS

### What is the expected behaviour?

Documentation should be correct. It says `reload_sources` has a default value of `true` but it's actually `false`

https://hasura.io/docs/latest/graphql/core/api-reference/metadata-api/manage-metadata.html#reload-metadata

![image](https://user-images.githubusercontent.com/11539524/155636735-13d2414a-be60-44df-872e-445f485f67f9.png)

### Keywords

invalid documentation, reload_metadata, reload_sources, default value

### What is the current behaviour?

Despite what the documentation says, `reload_sources` must be set to `true` in order for database sources metadata to be properly reloaded.

### How to reproduce the issue?

1. Add a DB as a source
2. Make some changes on the DB through psql / pgadmin / etc
3. Click the Reload button without selecting the "Reload all databases" option
4. Nothing happens.
5. Same problem through the API.

![image](https://user-images.githubusercontent.com/11539524/155636882-70b86062-0852-4bbd-8336-489d66364749.png)

**Comment by jflambert** [comment]
Some suggestions:
- make it true by default as per documentation
- either way: the console could specify the default value in the tooltip

**Comment by tirumaraiselvan** [comment]
We will fix the documentation ASAP. Thanks for raising this!

**Comment by tirumaraiselvan** [comment]
Hi @jflambert 

This is actually the expected behaviour on the console. The documentation is also right.

We intentionally do not reload remote schemas or sources because it is a costly operation. You will have to check the "reload all remote schemas" and "reload all databases" if you want to reload them. The console sends the following request if there are no inconsistent remote schemas or databases:

```
{"type":"bulk","source":"hge_oss_db","args":[{"type":"reload_metadata","args":{"reload_sources":[],"reload_remote_schemas":[]}},{"type":"get_inconsistent_metadata","args":{}}]}
```

(Note that the console sends an empty list `[]`, you can check this API from the browser's dev tools)

If there are inconsistencies, then it will ONLY include those with `Reload`.

**Comment by jflambert** [comment]
@tirumaraiselvan I went back to testing and you're right, the documentation is valid.

I still think my suggestion `either way: the console could specify the default value in the tooltip` should be implemented, because I assumed the documented default value of the API held true in the console.
