### ISSUE TITLE
Error applying metadata in CI, key "sources" not found

### ISSUE THREAD

**Issue by greg-prospyr** [hasura/graphql-engine#8280]
### Version Information

Server Version:
CLI Version (for CLI related issue): v2.3.0

### Environment

Cloud (Github Actions) on ubuntu-latest

### What is the expected behaviour?

I would like to be able to be able to apply metadata to a graphql-engine instance running CI

### Keywords

hasura apply metadata, key "sources" not found, "cannot get config information from server, this might be because config API is not enabled: error unmarshalling fetching server config"

### What is the current behaviour?

When I run `hasura metadata apply --skip-update-check --endpoint http://localhost:5001 --admin-secret secret` as a step in my Github actions CI process, I receive this error: `{"fields.time":"640.255729ms","isError":true,"level":"debug","msg":"telemetry: beamed","time":"2022-03-04T20:36:01Z"}
time="2022-03-04T20:36:01Z" level=fatal msg="error applying metadata \n{\n  \"path\": \"$.args.metadata\",\n  \"error\": \"key \\\"sources\\\" not found\",\n  \"code\": \"parse-failed\"\n}"`

Whats bizarre is that the migrations apply successfully, so I know the engine is up and running & configured

### Screenshots or Screencast
<img width="1070" alt="Screen Shot 2022-03-04 at 2 45 40 PM" src="https://user-images.githubusercontent.com/94129270/156839029-92224400-278e-49ef-8a95-b660414c55d1.png">
<img width="1072" alt="Screen Shot 2022-03-04 at 2 50 04 PM" src="https://user-images.githubusercontent.com/94129270/156839649-ec0993e0-f0bd-45a4-8b77-f689807cbbaf.png">

### Please provide any traces or logs that could help here.

This is my github action (minus envs):
```name: End to End
on: [pull_request]

jobs:
  end-to-end:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          # will assign a random free host port
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      hasura:
        image: hasura/graphql-engine:v2.3.0
        env:
          HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
          HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
          PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
          HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
          HASURA_GRAPHQL_DEV_MODE: "true"
          HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
          HASURA_GRAPHQL_AUTH_HOOK: "http://localhost:3003/auth/webhook"
          ACTION_BASE_URL: "http://localhost:3003"
          ACTION_REMOTE_SCHEMA_URL: "http://localhost:3004"
          EVENT_TRIGGER_URL: "http://localhost:3003/events"
          HASURA_GRAPHQL_ADMIN_SECRET: secret
        ports:
          - 5001:8080

    environment: staging
    env:
      NODE_ENV: test
    steps:
      - uses: actions/checkout@v2
      - name: Install hasura cli
        run: curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | VERSION=v2.3.0 bash
      - name: Make envfile (action-service)
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_NODE_ENV: test
          directory: services/action-service
          file_name: .env
          fail_on_empty: false
      - name: Make envfile (gql-action-service)
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_NODE_ENV: test
          envkey_PORT: 3004
          directory: services/gql-action-service
          file_name: .env
          fail_on_empty: false
      - name: Make envfile (webapp)
        uses: SpicyPizza/create-envfile@v1.3
        with:
          directory: ./webapp/apps/webapp
          file_name: .env
          fail_on_empty: false
      - name: Install Tilt
        run: curl -fsSL https://raw.githubusercontent.com/tilt-dev/tilt/master/scripts/install.sh | bash

      - name: Run Tilt
        run: |
          tilt ci -f Tiltfile.ci.test

      - name: migrate to the latest version of the database
        run: |
          cd hasura
          hasura migrate apply --skip-update-check --all-databases --endpoint http://localhost:5001 --admin-secret secret

      - name: apply metadata
        run: |
          cd hasura
          hasura metadata apply --skip-update-check --endpoint http://localhost:5001 --admin-secret secret --log-level DEBUG

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - uses: c-hive/gha-yarn-cache@v1

      - name: Install dependencies
        working-directory: ./webapp
        run: yarn install

      - name: Build
        working-directory: ./webapp
        run: yarn build

      - name: test
        working-directory: ./webapp
        run: nx e2e webapp-e2e
```

Thank you in advance for any help, I am really at my wit's end here!

**Comment by scriptonist** [comment]
@greg-prospyr 

The error that you mentioned might be because the metadata CLI generates does not have a "required" key `sources` in it. 

We can get the JSON metadata that CLI sends to the server by `hasura metadata apply --dry-run -o json` can you share the output of this command? Also, please share what Config version you are on (refer `config.yaml`)

**Comment by alexbatis** [comment]
@greg-prospyr i ran into this issue recently, and for me the issue was file name case sensitivity.  on my local machine the filenames appeared to be fine but when I checked the repository in github the filenames were incorrect.

for example, `hasura/metadata/databases/default/tables/public_User.yaml` looked fine on my machine but showed up as `hasura/metadata/databases/default/tables/public_user.yaml` in github.

if you can find the files that have inconsistent naming conventions from the filename to the database table name use this git command to rename the file

`git mv yOuRfIlEnAmE yourfilename` (source: https://stackoverflow.com/a/20907647/5173922)

hope this solves your issue as this is a tricky one and the error message `\"key \\\"sources\\\" not found\"` is not very helpful

**Comment by motleydev** [comment]
I also encountered this issue where uppercase naming on a Mac caused issues with CI/CD deploys. 

I would propose that an error be added to the CLI that when no matching source is found, we surface that, not that now key sources was found.

Something like "database Default not present in databases 'default'" or something else that more accurately describes the underlying issues.

For now, it's lowercase all the things for me!

**Comment by imperfect-fourth** [comment]
@greg-prospyr thanks for the extra info. As @alexbatis pointed out [here](https://github.com/hasura/graphql-engine/issues/8280#issuecomment-1078741390), it is a file naming issue. And the reason that the metadata gets built correctly on a MacOS is because it is a case-insensitive filesystem. 

Anyway, the error doesn't provide much information and the debug info is misleading(`"file for sources was not found"`). The error reporting can be improved in this case and we are working on fixing that.

**Comment by greg-prospyr** [comment]
Thank you everyone above for your suggestions, it did end up being a file naming issue - definitely a tough bug to track down!

**Comment by rikinsk** [comment]
Hey folks, the error messaging around this scenario has been improved with https://github.com/hasura/graphql-engine/commit/c668aa1158254eca9d47ae0e4eb788f35ecc3242. 

Closing this for now. Please feel free to reopen if there are more actionables one would like to be discussed
