### ISSUE TITLE
Invalid console documentation when inferred function permissions are disabled

### ISSUE THREAD

**Issue by jflambert** [hasura/graphql-engine#8288]
### Version Information

Server Version: 2.2.1

### Environment

OSS

### What is the expected behaviour?

When using `HASURA_GRAPHQL_INFER_FUNCTION_PERMISSIONS: false`, I want to explicitly set function permissions to specific roles. On-screen documentation should reflect the environment variable.

### What is the current behaviour?

Permissions are no longer inferred/inherited, but a message appears as though they are.

### How to reproduce the issue?

1. start hasura with `HASURA_GRAPHQL_INFER_FUNCTION_PERMISSIONS: false`
2. track a function
3. go to permissions
4. Notice an incorrect message `Permissions will be inherited from the SELECT permissions of the referenced table (XXX) by default.`

### Screenshots or Screencast

![image](https://user-images.githubusercontent.com/11539524/157265337-a2d8739b-800e-47dc-9fe2-1bb129db498b.png)

**Comment by tirumaraiselvan** [comment]
This is the expected behaviour. Select permissions are inherited in either case (HASURA_GRAPHQL_INFER_FUNCTION_PERMISSIONS: true/false). But when `HASURA_GRAPHQL_INFER_FUNCTION_PERMISSIONS: false` then you need to **additionally** give an explicit permission to enable that function for the given role.

If you want to give different permissions altogether, then you should follow this issue: https://github.com/hasura/graphql-engine/issues/8328
