### ISSUE TITLE
Reuse generated types in Actions

### ISSUE THREAD

**Issue by mscrocdile** [hasura/graphql-engine#8476]
**ad Actions**
For instance i have generated Customer type from database using tracking (i have mutations and queries).
Now i want to create new action returning array of customers GiveMeSpecialCustomers: [Customer]
I think now i cannot reuse existing types now in Action. Am i right?

**ad Remote Schema**
In case i want to do the similar using remote schema - graphql endpoint using same database -  i will get an error:
Inconsistent object: Field cannot be overwritten by remote field 'customers',
I suppose it is because that type already exists in Hasura scheme, is that right?

Would it be possible for at least one of above cases create business logic functions using already generated types ?

**Comment by mscrocdile** [comment]
I noticed now it is already mentioned here 2 years ago.
[https://github.com/hasura/graphql-engine/issues/5001](url)
Is there any optimistic forecast about it?

**Comment by AesSedai** [comment]
I don't think it's possible at all in Actions currently, but you can do it with remote schemas. I have an example repository here that should more or less point you in the right direction: https://github.com/AesSedai/apollo-hasura-remote-schema

The TL;DR version is:
- Fetch the existing graphql spec from Hasura in your remote schema
- Merge the Hasura gql definitions with your remote server
- Add in whatever queries / mutations you want to your remote schema, re-using Hasura types as desired
- Hasura should allow the above, since the types should be consistent

**Comment by rahulagarwal13** [comment]
Closing this as feature request captured in https://github.com/hasura/graphql-engine/issues/5001
