### ISSUE TITLE
Creating a Event Trigger on MS-SQL on table with reserved name fails

### ISSUE THREAD

**Issue by jmarbutt** [hasura/graphql-engine#8557]
### Version Information

Server Version: v2.7.0-cloud.1

### Environment

Hasura Cloud 

### What is the expected behaviour?

Creating an Event Trigger on MS-SQL on tables with reserved words should create an event trigger. 

### Keywords
Event Trigger, MS-SQL

### What is the current behaviour?

When creating an event trigger on table `User` it returns an error:
```
[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near the keyword 'User'.
```

In MS-SQL all tables should be specified in `[schema].[table]` format for the safest and most consistent results. 

### How to reproduce the issue?

1. Post the following to the `v1/metadata`
```json
{
  "type": "mssql_create_event_trigger",
  "args": {
    "name": "UserTrigger",
    "source": "default",
    "table": {
      "name": "User"
    },
    "webhook": "{FUNCTIONS_URL}/api/UserTrigger",
    "insert": {
      "columns": ["FirstName"]
    },
    "update": {
      "columns": ["LastName"]
    }
  }
}
```

2. Receive Error

**Comment by Naveenaidu** [comment]
@jmarbutt thanks for reporting this issue. The fix for this has been merged into the main via this [commit](https://github.com/hasura/graphql-engine/commit/2526dd011414431ba2e76a71423af5530bb38608). This should be available in the next release :)

I'll go ahead and close this issue, please feel free to re-open if you feel otherwise ^^
