### ISSUE TITLE
Console: refactor Data tabs Browse Rows components to move away from Redux

### ISSUE THREAD

**Issue by ejkkan** [hasura/graphql-engine#8836]
### Describe the solution you'd like

Currently, all requests related to rendering the Browse rows tab are handled by redux.
Start migrating current class components into functional components to make use of the react-query hooks

Tasks:
* Split the `ViewRows` component into different presentational components:
![image](https://user-images.githubusercontent.com/59067245/186436577-df526f02-4ea3-4586-81eb-4e7c9c70dc7d.png)

**Comment by lucarestagno** [comment]
@vijayprasanna13 is this going to be handled by `useHttpClient`? 

What are the use cases for:
* `includeCredentials`
* `includeAdminHeaders`

Source: `src/utils/requestAction.ts`
```
const requestOptions = { ...options };

    if (!options.credentials && includeCredentials) {
      requestOptions.credentials = globalCookiePolicy;
    }

    if (includeAdminHeaders) {
      requestOptions.headers = {
        ...(options.headers || {}),
        ...dataHeaders(getState),
      };
    }
```

**Comment by vijayprasanna13** [comment]
The uses cases for `includeCredentials` & `includeAdminHeaders` are not well documented in the codebase but my best guess is that they are optional headers being set during pro console mode. The `useHtttpClient` should technically work without no issues when passing down the auth headers since the headers are stored in the same redux path on both oss and pro console. 
One example from the code base -
```ts
    const options: RequestInit = {
      method: 'POST',
      credentials: globalCookiePolicy, // this is hardcoded to `same-origin` in Endpoints.ts
      headers: dataHeaders, // this is passed down as props from its parent, which reads it from state.tables.dataHeaders
      body: JSON.stringify(
        getRunSqlQuery(query, dataSource.name, false, true, dataSource.driver)
      ),
    };

    dispatch(requestAction(url, options)).then()
 ```
I've tried the `useHttpClient` on the pro console with Oauth and it seemed to worked fine.

**Comment by NoriSte** [comment]
Nice initiative ❤️ if I can be helpful (instead of reading my usual 30 comments for every PR late) let m know! So we can establish patterns to save refactoring time and improve components' readability etc.
