### ISSUE TITLE
server/bigquery: optional project_id with the default value from the service account

### ISSUE THREAD

**Issue by hgiasac** [hasura/graphql-engine#8878]
### Is your proposal related to a problem?

Although the service account is configurable with an env variable, the project_id is still hard coded. It's cumbersome for multiple environments (dev, staging, production).

### Describe the solution you'd like

The project id is already included inside the service account JSON file. We can parse its content and get the project_id as default, and make project_id optional in the data source configuration.

### Describe alternatives you've considered

Enable env template for project_id. Related https://github.com/hasura/graphql-engine/issues/7017

### If the feature is approved, would you be willing to submit a PR?

Yes, if I have time to do that

**Comment by i-am-tom** [comment]
Hi! Apologies for the slow response - I came across this issue while reviewing open BigQuery requests, but I think we've solved this since the issue was opened.

This can be achieved both via the console here:

<img width="405" alt="BigQuery project_id via environment variable" src="https://github.com/hasura/graphql-engine/assets/6302310/540c8a29-7ec3-46f6-9d49-7edb6f78d24f">

... and directly in the metadata API, by setting the `project_id` as `{"from_env": "MY_PROJECT_ID_ENVIRONMENT_VARIABLE"}`. The reason we don't parse the service account file is because service accounts might be tied to multiple datasets, and we don't want to assume that the one listed in the service account is necessarily the one you want to configure. Hopefully, though, being able to set a project_id env var solves your problem?

Thanks for opening an issue, and let me know if this doesn't work for you!
