### ISSUE TITLE
hook auth stopped working after 0.26

### ISSUE THREAD

**Issue by patcito** [hasura/graphql-engine#890]
Here is what my webhook returns:

` { 'X-Hasura-Role': 'anon' }`

And the error I get:

```
{
  "errors": [
    {
      "path": "$",
      "error": "Invalid response from authorization hook: Error in $: expected [a], encountered Object",
      "code": "unexpected"
    }
  ]
}
```

This happens on all my queries, works fine on v0.25.

**Comment by 0x777** [comment]
@patcito We are releasing `alpha27` with the fix in the next couple of hours. However if you are using the webhook to always return `{"x-hasura-role":"anon"}`, you can use the new `--unauthorized-role` feature instead of webhook. In your case, you'll have something like `--access-key 'access-key' --unauthorized-role 'anon'`, or you can simply add an environment variable `HASURA_GRAPHQL_UNAUTHORIZED_ROLE` with the role name and remove the webhook env variable.

**Comment by patcito** [comment]
@0x777 I don't always return {"x-hasura-role":"anon"}, only when the jwt token has expired. However, can I bypass the webhook when the client already knows current role is anon? (ie, when user is not logged in on client).
