### ISSUE TITLE
using a function that returns date for computed field

### ISSUE THREAD

**Issue by abdullah2993** [hasura/graphql-engine#9033]
Unable to track/use a function that return date.
```sql
create or replace function get_tenant_date(id uuid) returns date stable as $$ .... $$
```
getting error
```
cannot be tracked for the following reasons: 
• the function does not return a "COMPOSITE" type 
• the function does not return a table
```

**UPDATE:** 
I tried [the sample code](https://hasura.io/docs/latest/schema/postgres/computed-fields/#1-scalar-computed-fields) in hasura cloud as well and it seems to not working there as well. the sample code in question is this
```sql
CREATE FUNCTION author_full_name(author_row authors)
RETURNS TEXT AS $$
  SELECT author_row.first_name || ' ' || author_row.last_name
$$ LANGUAGE sql STABLE;
```

**Comment by abdullah2993** [comment]
Finally figured this one out, It looks like you don't have to track the function to use it in computed fields 😞

**Comment by meetzaveri** [comment]
Hey @abdullah2993 

This error is an expected one. Let me explain a bit here 

### Context
I guess in this context, you might be referring to this track checkbox UI

![captures_chrome-capture-2022-8-30 (1)](https://user-images.githubusercontent.com/21293048/193140794-80f2cc28-a938-40c9-9d09-bcd550711995.png)


Regarding the docs you [mentioned](https://hasura.io/docs/latest/schema/postgres/computed-fields/#1-scalar-computed-fields), in those docs, it doesn't include anywhere that you need to "track" the function. Because when you create that function and use it for computed field, then it works as expected even if **we didn't track them**

### Solution
As you can see, we have included a text hyperlink very next to checkbox text which mentions "[See supported functions requirements](https://hasura.io/docs/latest/graphql/core/schema/custom-functions.html#pg-supported-sql-functions)"  

If you go through those requirements, then you can see this section that - while creating custom SQL functions, if you want to track them then to simply put,
- When you track a function, its **return type MUST** be SETOF `<table-name>` OR `<table-name>` where `<table-name>` is already tracked

The reason we tick the checkbox to track functions(saying this in context of RAW SQL editor) is to have them exposed over GraphQL API so that we can use it as queries/mutations or to use them as custom trigger function.

Please refer to this docs for more details - https://hasura.io/docs/latest/schema/postgres/custom-functions/#pg-supported-sql-functions

Also, do correct me if I am wrong here. I hope this makes sense

**Comment by abdullah2993** [comment]
@meetzaveri thanks for reaching out, yes the problem was exactly that combined with the face the only function that are shown in UI has to accept an input argument of type table which was something I was missing, not sure if that is documented somewhere.
Feel free to close the ticket or convert to docs tag 
Thanks
