### ISSUE TITLE
hdb_catalog schema Inconsistent between Instances

### ISSUE THREAD

**Issue by DomVinyard** [hasura/graphql-engine#9116]
### Version Information

Server Version:
v2.13.0-cloud.1

### Environment
Cloud

### What is the current behaviour?

I have two Hasura instances which differ in how they have constructed the `hdb_catalog` in the database.

If I run this sql in both:

```
SELECT * FROM information_schema.tables 
WHERE table_schema = 'hdb_catalog'
```

I see different results. The first is what we have (rightly or wrongly) considered to be the 'correct' behaviour (the behaviour we have coded against)
<img width="539" alt="image" src="https://user-images.githubusercontent.com/1271197/196026640-2bbb594c-bae0-4a2e-9913-76f3d7cb6300.png">

The second instance does not surface these tables, instead (for the same query) giving us:

<img width="489" alt="image" src="https://user-images.githubusercontent.com/1271197/196026662-da7e9220-d7b6-44b9-8fe0-bdc015c354d7.png">

I'm not sure which is the intended behaviour. The reason this is an issue is because we have a script which can return the number of unprocessed events at any one time:

```
post(HASURA_QUERY_ENDPOINT, {
      headers: {"X-Hasura-Admin-Secret": HASURA_ADMIN_SECRET},
      body: JSON.stringify({
         type: "run_sql",
         args: { sql: "select count(*) from hdb_catalog.hdb_scheduled_events where status = 'scheduled'" },
      }),
});
```

This obviously throws an error in the second example as the table does not exist. I would like to understand:
1. Which of these two results is intended/expected?
2. How/where are events stored in the second example?
3. How can I go about making these consistent?

Thanks in advance

(Related: https://stackoverflow.com/q/70010557/3001761)

**Comment by adas98012** [comment]
@DomVinyard 
Actually, what you are seeing are two different database schemas: **metadata** and **main database**. You should see distinct values in "table_catalog" column in the above sql query.

Hasura Metadata is a representation of the configuration of the Hasura Server. From actions to databases and their tables, to permissions, event triggers and API limits, everything regarding the config of the Hasura Server is represented in Metadata.

Please let me know if you need more information.

**Comment by DomVinyard** [comment]
Hi @adas98012, thank you so much for your help.

> what you are seeing are two different database schemas: metadata and main database

I think I'm even more confused than before! Why the same sql command would return two distinct schemas - the `hbd_catalog` schema was generated by Hasura, but in the first example it is the main database? what does that mean? 

> You should see distinct values in "table_catalog" column in the above sql query.

The table_catalogue column seems to contain the name of the environment, `myapp_staging` in the first example and `myapp_production` in the second

<img width="577" alt="image" src="https://user-images.githubusercontent.com/1271197/196399602-8f7d522d-dad3-4461-99fd-d4d80081e5c8.png">

vs

<img width="650" alt="image" src="https://user-images.githubusercontent.com/1271197/196399723-ed80826a-77d7-4612-a9f4-65034a10395a.png">

> Please let me know if you need more information

I'd love to know how you would generate the behaviour in the first example so it works the same as the second example. Should I just create these tables manually? I guess I'm still no closer to understanding my initial three questions

1. Which of these two results is intended/expected?
2. How/where are events stored in the second example?
3. How can I go about making these consistent?

**Comment by DomVinyard** [comment]
A bit more context:

I can [see from the docs](https://hasura.io/docs/latest/scheduled-triggers/clean-up/):

> scheduled events also have two tables managed by Hasura:
> hdb_catalog.hdb_scheduled_events: Table that stores all the scheduled events.
> hdb_catalog.hdb_scheduled_event_invocation_logs: Table that stores all the HTTP requests and their responses of the scheduled events invocations.

In all of my environments -- local and cloud -- this is true. Except for one instance (example #2 above) - in this instance the table does not exist.

However, when I create an event it exists in the GUI, so it is definitely being stored somewhere

**Comment by BenoitRanque** [comment]
Hi @DomVinyard

### How to get count of events

The short answer to your question:
> is it undocumented for a reason, aka should I not be interfacing with it directly? If not is there a recommended way to query for scheduled events?

Is that yes, these tables are considered implementation details of hasura functionality and not intended to be used directly.
Their schema may change when upgrading to newer versions of hasura.

The intended way to interact with these tables is to use the [corresponding APIs](https://hasura.io/docs/latest/api-reference/metadata-api/scheduled-triggers/). Unfortunately, an API allowing you to do exactly what you want (get a count of pending events) is not currently documented. Most likely it exists and is either undocumented because it is considered unstable, or we are simply missing documentation. We'll inquire into this and provide an update here.

### Why are there multiple versions of the hdb_catalog schema

The answer to this question is a bit complicated so I'll have to provide some context on older versions of hasura.
In hasura 1.3, the `hdb_catalog` schema is used to store metadata (configuration information), and a bunch of other things including event data.

Hasura 2.0 introduced the ability to connect multiple databases, which posed the question: if we can connect to multiple databases, where do we store the metadata required for startup?

The answer is that we have a dedicated metadata database. Access to this database is required for startup.
On hasura cloud, this database is hosted by us and cannot be accessed directly by the users.

Users who are self-hosting and do not explicitly specify a metadata database using `HASURA_GRAPHQL_METADATA_DATABASE_URL`, and instead specify a single database using the legacy `HASURA_GRAPHQL_DATABASE_URL` will be able to continue using that database for metadata.

This explains why you may be seeing a different schema in a self-hosted dev environment, and on hasura cloud.
If you are seeing these tables on a 2.x.x cloud environment, it may be because the database was at one point used with a 1.3 project, or with a self-hosted instance.

#### Event triggers

Hasura's event triggers work by using postgres triggers to build a queue of events, and then asynchronously processing those events.

For performance reasons, building this queue still happens on the user's database, which is why projects that use event triggers will still have a different version of the `hdb_catalog` schema.

### Your two different schemas

Your first screenshot shows a metadata database hdb_catalog schema.
This may either be a dedicated metadata database, or a project using a single database for both the metadata and the user's data.

Your second screenshot shows a schema of a project that has a dedicated metadata database (could be a cloud project) and has the tables used by the event processing loop.

I hope this helps clarify things.

**Comment by DomVinyard** [comment]
@BenoitRanque amazing, thank you - that really clears things up 🙏 

> If you are seeing these tables on a 2.x.x cloud environment, it may be because the database was at one point used with a 1.3 project

Yup, that's exactly it. We created our staging environment a little while ago with the old schema. Now we're ready to build a production environment the upgrade to 2.x means we are no longer able to query for event counts, I understand that this was undocumented so no there's absolutely blame, however to us it's still a regression and we need to find an urgent workaround.

> an API allowing you to do exactly what you want (get a count of pending events) is not currently documented  [...] We'll inquire into this and provide an update here.

That would be amazing. Without this we'll need to rethink our events strategy so really appreciate your advice 🙏

**Comment by adas98012** [comment]
@DomVinyard 
Thank you for your prompt update. We have created a separate [feature request](https://github.com/hasura/graphql-engine/issues/9135) for an API and intimated the engineering team. You should be able to track its progress.

**Comment by DomVinyard** [comment]
Hi @adas98012 that's really helpful thank you, how can I query for the one off events, something like `type: "one-off"`?

**Comment by adas98012** [comment]
@DomVinyard 

You can try the same POST query as above, with a small variation in the Body : 

{
    "type": "get_scheduled_events",
    "args": {
        "type": "one_off",
        "limit": 10,
        "offset": 0,
        "get_rows_count": true
    }
}

**Comment by DomVinyard** [comment]
OK, that's fine, we can fetch all events and filter on our side, there's nothing that should prevent us from doing that for the meantime, right? - thanks @adas98012

**Comment by DomVinyard** [comment]
> I don't think our API supports filtering by comment

Any chance you could clarify whether this is definitely the case, also whether it is a part of your roadmap
