### ISSUE TITLE
"After Insert" permissions

### ISSUE THREAD

**Issue by osdiab** [hasura/graphql-engine#9299]
### Is your proposal related to a problem?

Yes, since [we can't use SQL functions for row select permissions](https://github.com/hasura/graphql-engine/issues/2575), we instead opted to use a view, but then because insert permissions appear to be evaluated pre-insert instead of post-insert, they always fail.

> My company also is experiencing this issue. My colleague @sincraianul and I are building an enterprise SaaS, and as part of that we needed a complex permissions system, which mostly works! We got inspiration from [the HighTouch talk on complex authentication with Hasura](https://hasura.io/events/webinar/how-hightouch-uses-hasura-to-manage-complex-access-controls/), and ended up using a system of views and functions to pull it off.
> 
> But like @mvilrokx found, while selects work fine, inserts and updates have a significant issue—I'm not sure if what I will describe is the same phenomenon he experienced, but this is what we found.
> 
> We wanted to use our `check_permissions` SQL function directly in the permission, but we couldn't, so instead we ended up making a view for evaluating permissions that calls it instead. For each table, the permissions view for that table cross joins the set of users in our system, outputting whether or not that user could view or edit that row. This works great for selects, as we can just make a manual relation from the table row to the equivalent permissions row, and then check that the selecting user has a matching permissions row for the selected row.
> 
> But it seems that the permissions are evaluated before, not after the insert/update. As a result, because the row we're trying to insert doesn't exist in the table yet, the view doesn't have that row either, and therefore the permissions check always fails because no matching row in the permissions table will be present.

_Originally posted by @osdiab in https://github.com/hasura/graphql-engine/issues/2575#issuecomment-1342534051_

### Describe the solution you'd like

Like there's a pre- and post- update permissions, would love pre- and post-insert permissions. this way our views would have data present when we do the permissions check against them.

### Describe alternatives you've considered

> Our ugly workaround for now is that we will make all of our tables have a `last_edited_by_user_id` column that is set via presets, and then handle the insert permissions check via an `AFTER INSERT` constraint trigger that does the same logic that we would have done had the permissions lookup worked (we need the user ID to evaluate the permissions, but the authorization headers we've set up wouldn't ordinarily be accessible from a constraint trigger as far as we know). The downside is that A) every table needs this column set up, B) the permissions aren't shown in the actual permissions UI which is counterintuitive, and C) we need to make effectively the same trigger for every single table in our app. This works, but it's not elegant, to say the least.

**Comment by osdiab** [comment]
Looking forward to a resolution for this. Our insert trigger workaround sort of works, but since we don't have access to the Hasura session JWT claims in the insert trigger as far as I can tell, we've had to make some sketchy hacks to allow us to properly do our migration from our old permissions system to the new one described above. It's created a lot of boilerplate to work, which has been tolerable, but ideally the feature would work as we expected out of the box. Thanks for looking into this Hasura team!

**Comment by SamirTalwar** [comment]
Hey @osdiab, thanks for reporting this, and sorry for the delay in getting back to you.

In order to fully understand why you've worked around this issue in the way you have, I'd like to present a couple of ways in which you _could_ potentially solve the problem. You've probably tried them already, but understanding why they don't work for you will help us either get to a better solution or, if necessary, prioritize a new feature.

So we don't get confused by abstract explanations, I am going to pretend we are talking about a table `article`, with the columns `article_id`, `author_id`, and `title`. The `author_id` is a foreign key to the `person` table.

### Idea 1: use a computed field during validation

As I said, you've probably already tried this. I list it here for completeness and so we can discuss why it doesn't work.

1.  Create a PostgreSQL function wrapping your `check_permissions` function, which accepts an input of type `article` and returns a `BOOL`:
    ```sql
    CREATE FUNCTION validate_author(article article)
      RETURNS BOOL
      STABLE
      AS $$ SELECT check_permissions(article.author_id) $$
      LANGUAGE SQL;
    ```
2.  Register this function as a "computed field" for the `article` table.
3.  Set the row insert permissions of the `article` table to check that the result of this function is `true`.

### Idea 2: use an insert rule on an empty table

You may be aware that views in PostgreSQL don't really exist. They are simply an empty table of the given schema, and a "select rule" that overrides any `SELECT` query to instead run the SQL defined.

We can do similar things with "update rules", overriding the behavior of `INSERT` on an empty table that has the correct shape.

So, for example:

1.  Create a wrapper table which encompasses the `article` table, but with extra columns to capture Hasura-specific authentication data:
    ```sql
    CREATE TABLE new_article(
      article_id INT NOT NULL,
      author_id INT NOT NULL REFERENCES user(user_id),
      title TEXT,
      hasura_user_id INT NOT NULL,
      hasura_role TEXT NOT NULL
    );
    ```
2.  Define a function that calls `validate_permissions` and returns the original input, or raises an exception on failure:
    ```sql
    CREATE FUNCTION validate_author(author_id INT, hasura_user_id, hasura_role TEXT)
      RETURNS INT
      STABLE
      AS $$
        BEGIN
          IF validate_permissions(author_id, hasura_user_id, hasura_role) THEN
            RETURN author_id;
          ELSE
            RAISE 'Invalid author: %', author_id USING ERRCODE = 'check_violation';
          END IF;
        END
      $$
      LANGUAGE plpgsql;
    ```
3.  Override the `INSERT` behavior with a rule that calls your new validation function.
    ```sql
    CREATE RULE new_article_insert AS
      ON INSERT TO new_article
      DO INSTEAD INSERT INTO article VALUES (
        new.article_id,
        validate_author(new.author_id, new.hasura_user_id, new.hasura_role),
        new.title
      ) RETURNING *;
    ```
5.  Track the `new_article` table in Hasura.
6.  Set the permissions such that users can only insert into this table, and that the `hasura_user_id` and `hasura_role` columns are automatically populated by the appropriate headers. (This will need to be customized to your specific authentication process, of course.)

The new API endpoint will therefore call your `validate_permissions` function with all the appropriate data.

### Let's discuss

As I said earlier, these may not work for you. If they do, fantastic! Let us know what solved it. If not, let's discuss what we can do to improve the situation. Any information you can offer about the limitations of the above solutions would be very helpful.

**Comment by osdiab** [comment]
Hi @SamirTalwar , thanks for the post and the other possible workarounds! My quick takes:

1. Computed fields workaround: Not sure why we didn't think of that, that actually looks like it could be the most elegant solution as we may not need the views at all. We'll try making a POC of that to see if it works better than what we were doing originally.
2. Insert rule - interesting, but wouldn't be great for our scenario since during the migration we need to roll over from our old permissions system (which doesn't use this function, and we call with a different Hasura role in the auth claims) to the new one (which does); to have them running simultaneously so that we can gradually migrate over, we'd need to have inserts to the dummy tables (for our new permissions) and to the actual tables (for our old one) conditionally based on the hasura role, which would require a large amount of additional conditional logic that we'd just delete in the future. So yeah not our preference.

Overall ideally the insert permissions would work properly with views as the original issue poses, but I'm guessing there's some deeper technical reason (maybe around Postgres transaction levels?) that would make the views not receive the updates properly. But yeah, computed field might be the way, and just to avoid views with permissions in general, so we'll give it a shot. Thanks!

**Comment by SamirTalwar** [comment]
Thank you for the update! Looking forward to hearing if the computed fields work for you. 😀

**Comment by iosifnicolae2** [comment]
@SamirTalwar we have a similar problem, we would like to conditionally allow column update based on a condition.
For example, we want to allow column `active` to be changed for certain organizations but not for others.

Do you have any idea how can we implement this?

Thank you!

**Comment by SamirTalwar** [comment]
@iosifnicolae2, I'm glad you resolved your issue.

I am curious if you could accomplish the same thing by mapping the organization ID to a role, and then limiting based on role. Did you try that, and if it didn't work, why not?

**Comment by iosifnicolae2** [comment]
Hmm, if we map each organization to a role, then we will need to create all
the permissions programaticaly..

And also, this will not work in this case because for the same table a user
can or can't edit the same column.. (even if we use two roles combined
using inherited roles, we can't do this because the row policy must be
identical for Hasura to be able to combine..)


mar., 21 feb. 2023, 23:55 Samir Talwar ***@***.***> a scris:

**Comment by osdiab** [comment]
@SamirTalwar , just came back to this later to try out

> Idea 1: use a computed field during validation

and i find that that doesn't work; despite making a computed field like so:

<img width="402" alt="Screenshot 2023-05-02 at 19 40 07" src="https://user-images.githubusercontent.com/1890926/235645178-7f02f3e7-3ef9-4b0c-a8a5-ef670282c08d.png">

it doesn't show up in the permissions UI as something I can declare permissions against:

<img width="366" alt="Screenshot 2023-05-02 at 19 40 51" src="https://user-images.githubusercontent.com/1890926/235645300-cee61f3a-7a6f-4af1-96d1-6276a481f945.png">

So yeah, right now the insert trigger remains the best way we've found to handle this, which is a bummer.

**Comment by SamirTalwar** [comment]
This is weird. Can you share the structure of your computed field (i.e. the DDL that created it)? You're welcome to redact the actual SQL, as well as any names.

**Comment by osdiab** [comment]
let me see if i can repro it, i unfortunately have already gotten rid of that code.

**Comment by osdiab** [comment]
Of course when i tried to reproduce it it's working 🥲 i'll let you know if I run into that again.

**Comment by osdiab** [comment]
I didn't actually try using the permissions, just checking that the computed field was available. But I don't have reason to believe it wouldn't work. That said so long as you guys are cool with the fact that accessing a view for insert permissions just doesn't work at all, and not documenting that anywhere, I guess you can close it? lol

**Comment by SamirTalwar** [comment]
I'll bring it up with the docs team. Thanks for pointing it out, and sorry it took so long for me to reply!
