### ISSUE TITLE
sql server create EVENTS can not get the table

### ISSUE THREAD

**Issue by 8990679** [hasura/graphql-engine#9521]
### Version Information

Server Version:
v2.21.0-cloud.1

### Environment
amd64 sql server 2019

### What is the current behaviour?
 mssql create EVENTS
### What is the expected behaviour?
mssql create EVENTS

### How to reproduce the issue?
1.  run docker image mcr.microsoft.com/mssql/server:2019-latest
2.  Driver={ODBC Driver 17 for SQL Server};Server=tcp:127.0.0.1,1433;Database=master;Uid=sa;Pwd=$password;charset=utf8
3.  Create a test data table
4.  Create an EVENTS, choose a database, choose a schema.
5.  Unexpectedly no table.
### Screenshots or Screencast
![mssql](https://user-images.githubusercontent.com/64882073/227405885-9d411ef6-d5f8-4b75-b4ad-04a814e8d84e.jpg)
![no table](https://user-images.githubusercontent.com/64882073/227405912-ffa4af27-88cb-4cee-a988-a5372a1a2865.jpg)

### Please provide any traces or logs that could help here.
An error occurred in the console "Error: SyntaxError: Unexpected token 'd', "dbo" is not valid JSON"

### Any possible solutions/workarounds you're aware of?

Maybe there is an error in the parsing of json.

### Keywords

json，js

**Comment by 8990679** [comment]
![image](https://user-images.githubusercontent.com/64882073/233260051-7a715e80-2874-4027-8f95-c5c494729382.png)
maybe here is not suitable for parsing ms sql

**Comment by lucasnad27** [comment]
Is this bug being actively investigated? I stumbled across this issue when trying to setup a web hook event on MS SQL Server. Given how critical triggering events for hasura-based architecture, it would be nice to know if there were any plans to fix this or how to work around it. I've provided a few similar details to the original post. Thank you!

-----------------------

### Version Information

Server Version:
v2.24.1-cloud.1

### Environment

hasura cloud connected to microsoft azure - sql server database

### What is the current behaviour?

When trying to create a new event trigger, after selecting the schema, the table dropdown fails to load.

### What is the expected behaviour?

I should see a list of tables that I'm tracking in hasura.

### How to reproduce the issue?

- Run Hasura Cloud instance
- follow steps from original post

## Screenshots or Screencast

below is the console.log when I try clicking on the tables dropdown.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/2490636/236608859-606138b1-dfc2-43e0-b2d1-a020f13c841b.png">

**Comment by 8990679** [comment]
I can only think of two simpler solutions so far.
1: Intercept the data packet and modify the returned json data. (successful)
2: By modifying the code for parsing json, the image '[0]' I provided is changed to '[4]'. (It works in theory, I didn't succeed)

**Comment by lucasnad27** [comment]
thanks @8990679 -- unfortunately those two options aren't tenable for me. Hopefully the good folks at hasura can give us some guidance. I know we're in the minority (SQL Server vs PG), but I'm surprised more people haven't ran up against this issue. Unless it's something with our specific versions of SQL Server 🤷

**Comment by tirumaraiselvan** [comment]
Hey folks, thanks for the report. We are looking into this.

**Comment by tirumaraiselvan** [comment]
Hey folks, this bug was introduced in v2.20 and has been fixed in 2.25 (currently in beta). Pls try the new version when it's available in GA (in the next couple of days).

**Comment by lucasnad27** [comment]
> Hey folks, this bug was introduced in v2.20 and has been fixed in 2.25 (currently in beta). Pls try the new version when it's available in GA (in the next couple of days).

@tirumaraiselvan you are a life saver! Thank you for the good news and prompt reply. Look forward to unblocking some fun things I'll be doing with events 😬

**Comment by tirumaraiselvan** [comment]
Hey folks, you can try this out on `hasura/graphq-engine:v2.25.0-beta.1` image. I will close this ticket now. Pls feel free to comment/reopen if the issue persists.
