### ISSUE TITLE
How to integrate strapi ？

### ISSUE THREAD

**Issue by zuohuadong** [hasura/graphql-engine#9554]
I love hasura, but I want to have a backstage like strapi. 

https://strapi.io/

I think that's a great thing.

**Comment by Frikadellios** [comment]
Hi there... 

https://swagger.io/tools/swaggerhub/

I think the best decision.

**Comment by m-rgba** [comment]
There are a few ways you could go about doing this.
To compose:
- To start since Strapi is particular about it's schema, it may be easier to let it manage the CMS-specific stuff in your database (you can have other data that you want Hasura to manage in other schemas or non-Strapi-managed tables).
- Compose and manage your data as you usually would via your Strapi service.

There are 3 ways you could integrate with Strapi:
- Off your Postgres database (assuming you're using Postgres + Strapi) [I'd recommend this].
  - In this scenario you'd be using Strapi to edit your data in the database, but Hasura to serve the data.
  - The nice part about this is you don't actually need your Strapi instance running at runtime - since it's just editing data in your database which is then served by Hasura directly.
  - Note: You'll want to integrate Strapi with S3 or a CDN to serve any static content from your database if you don't have Strapi running.
- You could integrate with Strapi's [GraphQL API](https://docs.strapi.io/dev-docs/api/graphql) using a [Remote Schema](https://hasura.io/docs/latest/remote-schemas/overview/).
- You could integrate with Strapi's [REST API](https://docs.strapi.io/dev-docs/api/rest) using [Actions + REST Connectors](https://hasura.io/docs/latest/actions/rest-connectors/).

**Comment by zuohuadong** [comment]
@m-rgba   

> There are a few ways you could go about doing this. To compose:
> 
> * To start since Strapi is particular about it's schema, it may be easier to let it manage the CMS-specific stuff in your database (you can have other data that you want Hasura to manage in other schemas or non-Strapi-managed tables).
> * Compose and manage your data as you usually would via your Strapi service.
> 
> There are 3 ways you could integrate with Strapi:
> 
> * Off your Postgres database (assuming you're using Postgres + Strapi) [I'd recommend this].
>   
>   * In this scenario you'd be using Strapi to edit your data in the database, but Hasura to serve the data.
>   * The nice part about this is you don't actually need your Strapi instance running at runtime - since it's just editing data in your database which is then served by Hasura directly.
>   * Note: You'll want to integrate Strapi with S3 or a CDN to serve any static content from your database if you don't have Strapi running.


How should I handle user permissions issues?

Thanks.
