### ISSUE TITLE
[2.28.0] order by with multiple fields is broken?

### ISSUE THREAD

**Issue by efstathiosntonas** [hasura/graphql-engine#9728]
### Version Information

Server Version:
CLI Version (for CLI related issue): `2.0.28`

### What is the current behaviour?
 
this query returns totally different results on `2.28.0` than `2.27.0`, `id`  is type of `uuid`:

```gql
query GetConversationChannels(
  $limit: Int = 30
  $offset: Int = 0
  $channel_type: chat_channel_type_enum!
) {
  chat_channel(
    limit: $limit
    offset: $offset
    order_by: { latest_message_at: desc_nulls_last, id: desc }
    where: { channel_type: { _eq: $channel_type }, latest_message: {} }
  ) {
    id
    channel_type
    created_at
    latest_message_at
    snoozed
    members {
      ...chatChannelMember
    }
  }
}
```

The order of the results is not correct

### What is the expected behaviour?

I would expect the results to be the same as before upgrading to `2.28.0`

### How to reproduce the issue?

1. Upgrade from `2.27.0` to `2.28.0` 
2. Apply metadata

### Any possible solutions/workarounds you're aware of?

Downgrade to `2.27.0`, had to learn the hard way since prod server was updated to 2.28.0 :(

### Keywords
order_by, two fields, two or more fields

**Comment by jflambert** [comment]
You need to use square brackets to enforce order by of multiple_futanari columns.

**Comment by SamirTalwar** [comment]
@efstathiosntonas, you are probably correct in finding the offending PR. However, as @jflambert said, the syntax you were using was always choosing a random order (though stable for a given version). This is because according to the GraphQL specification, objects (dictionaries) are unordered.

[You need to use an array with one key per object:](https://hasura.io/docs/latest/queries/postgres/sorting/#sorting-by-multiple-fields)

```graphql
order_by: [{ latest_message_at: desc_nulls_last }, { id: desc }]
```
