### ISSUE TITLE
Input Validation Header: not possible to use env var

### ISSUE THREAD

**Issue by fschuermeyer** [hasura/graphql-engine#9782]
### Version Information

Server Version: 2.29.1

### What is the current behaviour?

Currently, then you want to set a Header Key Value in the new Input Validation (Hasura Console), and you use from_env, the Permissions Tab never saved as from_env. It's always saving as from_value

### What is the expected behaviour?

The expected behavior is that it's saved as from_env

### How to reproduce the issue?

1. Go to a Permissions View
2. Enable Input Validation
3. Try to set a Header from ENV Var

### Screenshots or Screencast

![image](https://github.com/hasura/graphql-engine/assets/25571323/bcac6e95-4839-44c1-98b9-f2eddaad434a)
![image](https://github.com/hasura/graphql-engine/assets/25571323/6713c80f-cb15-420b-b73d-520fb3ef0ab3)

### Keywords
input validation, from_env, from_value

**Comment by Naveenaidu** [comment]
hey @fschuermeyer, thank you very much for reporting this issue. This turned out to be a console issue and we are actively working on a fix.  

That being said, environment variables are accessible inside Input Validation configuration. You'll have to enclose your environment variable inside template `{{}}`. This should let you access your environment variable. An example screenshot is attached below:

![Screenshot from 2023-07-18 18-29-12](https://github.com/hasura/graphql-engine/assets/30195193/1c9b2281-3c1f-482a-8b28-b8f360fad73b)

Please let us know if you have face any further issues ^^

**Comment by tirumaraiselvan** [comment]
@fschuermeyer For the time being, you can simply provide the env variable as a template in the "Value" field. e.g. ``{{MY_ENV_VAR}}``

**Comment by danieljharvey** [comment]
This should be resolved now, as of version 2.29 onwards. If you have other issues, please get in touch. Thanks!

**Comment by fschuermeyer** [comment]
Do you mean 2.39? the issue was in 2.29.1
