### ISSUE TITLE
customise generated type names in graphql schema

### ISSUE THREAD

**Issue by Maxpain177** [hasura/graphql-engine#981]
Hi. It will be cool to let a developer select which style of schema's root resolver and type names to use. Or let him override it in a console (separately for an object and arrays).
In my case, I already have a frontend on ApolloStack (about 60000 lines of code) + backend on [JoinMonster](https://github.com/acarl005/join-monster), and it's too hard to replace joinMonster to Hasura, because I need to transform schema, like this:

```typescript
export default async function getSchema() {
	const link = makeHttpAndWsLink(HASURA_GRAPHQL_ENGINE_URL, HASURA_ACCESS_KEY && { 'x-hasura-access-key': HASURA_ACCESS_KEY })

	const schema = makeRemoteExecutableSchema({
		schema: await introspectSchema(link),
		link
	})

	return transformSchema(schema, [
		new RenameTypes(type => pluralize.singular(capitalize(camelCase(type)))),
		new RenameRootFields((operation, name) => {
			let newName = name

			if (name.includes('_by_pk')) {
				newName = pluralize.singular(newName.replace('_by_pk', ''))
			}

			return camelCase(newName)
		})
	])
}
```

I want to:

- Type names must be in camelcase style
- Type names must begin with a capital letter
- Type names must be in the singular (even if the table name is in the plural) because it describes one object
- Root resolvers names must be in camelcase style
- Root resolvers names which returning arrays must be in the plural
- Root resolvers names which returning an object must be in the singular (_by_pk, for example)

**Example**:
Before:
```graphql
user_parties: [user_parties!]!
user_parties_by_pk: user_parties
```
After:
```graphql
userParties: [UserParty!]!
userParty: UserParty
```

**Comment by shahidhk** [comment]
@Maxpain177 What you are proposing is complete customisability for the schema generated by Hasura from your Postgres tables, right? Like camel case vs snake case, singular vs plural etc.

I have added an `ideas` label so that we can discuss further.

**Comment by Maxpain177** [comment]
> @Maxpain177 What you are proposing is complete customisability for the schema generated by Hasura from your Postgres tables, right? Like camel case vs snake case, singular vs plural etc.
> 
> I have added an `ideas` label so that we can discuss further.

Yes exactly

**Comment by 0x777** [comment]
The server can add a `field_names` option to the `track_table` API to customise fields at the top level. 

For example, for an `article` table

```json
{
    "select": "Articles",
    "select_by_pk": "Article",
    "select_aggregate": "ArticleAggregate",
    "insert" : "AddArticles",
    "update" : "UpdateArticles",
    "delete" : "DeleteArticles"
}
```

I'm not sure about how to allow customisation of the column names. For relationships, it is already under the user control. However for every array relationship, we also generate a `_aggregate` field which we should allow to be customised. That can be part of the `create_array_relationship` API. 

The console can then do the hard part of automatically adding the correct field names to the `track_table` request based on the user's choice, snake case or camel case etc. 

Thoughts @rikinsk @praveenweb @coco98 ?

**Comment by Maxpain177** [comment]
@0x777, @shahidhk, @rikinsk, @praveenweb, @coco98 
I think we also should allow being customized fields in tables.

**Comment by 0x777** [comment]
@Maxpain177 That might complicate things a bit but I see your point.

**Comment by akiran** [comment]
yes, I would like to customise the schema as well.

Since data coming from graphql flow into code, it is better to have semantic names for better maintainability. For example, if graphql return list of users, I would like to have data property name to be  users instead user.

**Comment by Maxpain177** [comment]
> yes, I would like to customise the schema as well.
> 
> Since data coming from graphql flow into code, it is better to have semantic names for better maintainability. For example, if graphql return list of users, I would like to have data property name to be users instead user.

While we wait for implementing this feauture by Hasura Team, we can use graphql aliases.

**Comment by JeetChaudhari** [comment]
@coco98 I was thinking about same, Thank you for showing me how to do it. Currently, I would do my project as you explained but I hope in the near future Hasura team changes the mutation names to "user_by_pk" => "user" or "accountByAccountId" => "account".

**Comment by coco98** [comment]
@JeetChaudhari Sure :)

Also, uou can rename relationships very easily. The default names are just generated for convenience and ensure that there are no overlapping relationship names for the same table. 
You can delete the relationship and then name it to whatever you want :)

**Comment by JeetChaudhari** [comment]
@coco98 Thank You for the info, I wasn't knowing that relationships can be renamed.

**Comment by ivawzh** [comment]
FYI though you may know it already, Postgraphile allows the naming and other customizations via plugins https://www.graphile.org/postgraphile/make-add-inflectors-plugin/

This could be also helpful for Hasura I guess.

**Comment by JeetChaudhari** [comment]
@ivawzh I know, I switched to postgraphile due to following facts after trying Hasura. 

1. The main reason is postgraphile can be used in multiple ways including CLI, library, and schema only which means I can easily integrate it with NestJs framework with Apollo server to implement my business logic there and my team can manage everything in a single server application.
2. Postgraphile supports plugins so we can create plugins according to our need.
3. The naming conventions used by Hasura in my personal opinion is a pain and confusing for my team. More to it, there is no way we can change those apart from the relation names. Postgraphile has a plugin which does this efficiently.
4. Postgraphile has been developed in JS which means my team can work on its core features as they are familiar with the stack used.
5. Postgraphile does not have build in support for subscriptions but, I am working on currently developing one plugin for that (almost ready, within one or two days it would be on GitHub), which would not provide live queries (maybe in future) but would provide features provided by Prisma subscriptions with less filter options(maybe in future there would be more). 

Once Hasura solves most of these issues and becomes stable I would give it another try.

**Comment by revskill10** [comment]
@JeetChaudhari The main reasons to use Hasura to me:
- Haskell instead of Javascript, means better performance and stability.
- Built-in RBAC means i don't have to manually code my authorization logic.
- Naming convention ? `insert_users` is fine, what's wrong ? 
- Hasura has built-in subscription for all query mean all of my query now is live.
- Hasura has built-in event triggers means i can easily scale my application per my need as app grows.
- Hasura has built-in remote schema stitching means i don't have to manually merge remote schemas on my side, and the performance is 10x better.

I tried Postgraphile before and it's no way better than Hasura.

**Comment by coco98** [comment]
@revskill10 @JeetChaudhari Thanks for your comments and notes. 
We'll take especially the naming stuff into account. I think aliasing made easy via the console will work well :)

**Comment by dsandip** [comment]
@karibertils FYI

**Comment by coco98** [comment]
Also, we should allow aliasing of the postgres schema names so that people can change the prefixing behaviour. For example, being able to disable schema name prefixing altogether.

**Comment by 0x777** [comment]
This is WIP at https://github.com/hasura/graphql-engine/pull/2509

**Comment by beepsoft** [comment]
@coco98, @0x777 is this still planned to be supported?

> Also, we should allow aliasing of the postgres schema names so that people can change the prefixing behaviour. For example, being able to disable schema name prefixing altogether.

The `custom_root_fields` and `custom_column_names` customizations work great added by #2509, but it would be great to have the same kind of customization for the type names/prefixes as well.  

Is there an issue or PR where this is being implemented?

Thanks!

**Comment by tirumaraiselvan** [comment]
> it would be great to have the same kind of customization for the type names/prefixes as well

Being tracked here: https://github.com/hasura/graphql-engine/issues/3811
