### ISSUE TITLE
Hasura Actions imported from OpenAPI does not provide Type of Response

### ISSUE THREAD

**Issue by hubts** [hasura/graphql-engine#9826]
### Version Information

Server Version: v2.31.0
CLI Version (for CLI related issue): May not be releated

### Environment

- `Hasura` deployed by docker container as v2.31.0
- `NestJS` to generate Swagger by `@nestjs/swagger`
- The swagger generated JSON with `openapi` 3.0.0

### What is the current behaviour?

Hello, I struggled to generate my hasura actions easily by importing openapi from my server. I found some posts, however, there are no examples to generate hasura actions in all case.

My issue is simple. When I import openapi json to hasura actions feature, the hasura does not provide response type for my API spec. Am I missing something?

In my API spec (json):
![image](https://github.com/hasura/graphql-engine/assets/25478540/d8fa169f-1355-4268-964f-3832a7205a09)
This is a part of `loginManager` method in my API. The `requestBody` and `responses` are defined. Then, here is the detail of them.

![image](https://github.com/hasura/graphql-engine/assets/25478540/0c104113-4f9b-47e1-8acc-e4798f565d99)

Then, openapi (swagger) is well constructed, however, when I import it, no response type is providing.

![image](https://github.com/hasura/graphql-engine/assets/25478540/1ea63666-4f3e-4064-8ea5-775628de3569)

I want to know where should be set to get a response type from openapi.

### What is the expected behaviour?

When I import openapi json to hasura action, the response type of implemented API should be generated as type and used as response of hasura action automatically generated from openapi like this:

![image](https://github.com/hasura/graphql-engine/assets/25478540/dfa99adf-1c8a-4e51-9e24-8563a1485d54)

### How to reproduce the issue?

1. Here is my openapi json:
```Bash
{"openapi":"3.0.0","paths":{"/auth/login-manager":{"post":{"operationId":"loginManager","summary":"","parameters":[],"requestBody":{"required":true,"content":{"application/json":{"schema":{"$ref":"#/components/schemas/LoginManagerBodyDto"}}}},"responses":{"default":{"description":"","content":{"application/json":{"schema":{"$ref":"#/components/schemas/LoginManagerResponseDto"}}}}},"tags":["Auth"]}}},"info":{"title":"Backend API Swagger","description":"Documents to experience the Backend API","version":"1.0.0","contact":{}},"tags":[],"servers":[],"components":{"securitySchemes":{"bearer":{"scheme":"bearer","bearerFormat":"JWT","type":"http"}},"schemas":{"LoginManagerBodyDto":{"type":"object","properties":{"email":{"type":"string","example":"gvzlog8798@email.com"},"password":{"type":"string","example":"isskhdplpv"},"code":{"type":"string","example":"2692"}},"required":["email","password","code"]},"LoginManagerResponseDto":{"type":"object","properties":{"accessToken":{"type":"string","example":"wyfppmwxvnedizlsorrygmbhmiymbrel"},"refreshToken":{"type":"string","example":"etkmpjzbkghvpbrbqeuilrlhirkjpyxl"}},"required":["accessToken","refreshToken"]}}}}
```
2. Import it for hasura action creation like this:
![image](https://github.com/hasura/graphql-engine/assets/25478540/254cfce2-534c-4dea-bbfa-134804f1ec35)

3. When creating the action, It may not provide the response type.

### Screenshots or Screencast

The screenshots are used in the above descriptions.

### Please provide any traces or logs that could help here.

No, there is no any log.

### Any possible solutions/workarounds you're aware of?

In my thinking, openapi json may not be wrong, or hasura action importing want to read other fields to catch the response type. I want to know about it. Or the hasura action import does not provide catching the response type?

### Keywords

Hasura, Actions, Import OpenAPI, Response, Type, Generation, Creation, JSON

**Comment by tirumaraiselvan** [comment]
Thanks for reporting. We are looking into it.

**Comment by dancamma** [comment]
Hi @hubts, thanks for reporting! It looks like the response is not detected correctly. We'll fix it, but a temporary workaround can be to change the `default` key in the `responses` object to `200`.

```
"responses": {
          "200": {
            "description": "",
```

**Comment by hubts** [comment]
Thank you for your quick actions! 😃 

I understand that the response status should be fixed to 200 in this time, is that right? Moreover, which version will the fix you mentioned be applied?

**Comment by soorajshankar** [comment]
Hey @hubts, 

I was checking the spec, it looks like the spec is defining positive case response as the `default` response, but as per the [OAS spec definition ](https://spec.openapis.org/oas/v3.1.0#fixed-fields-13), the `default` field should only be used to cover the undeclared responses. 

![image](https://github.com/hasura/graphql-engine/assets/8408875/d6843f05-c529-463c-a25c-99e61562b038)
 
And on the Hasura side, what we do is to look for the `200` series HTTP code responses on the OpenAPI spec file for the select endpoint and generate the GraphQL type for the same. (we ignore any other HTTP codes like 400, 500 as it is treated as negative response by [HTTP error code standards](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status)   )

In this context, I feel the fix should be on the OpenAPI spec json file to include the proper HTTP code and use `default` only to define the undeclared responses before passing it to Hasura.

I hope you are unblocked from the above comment- and I suggest if the generated OAS spec is not giving the correct data, use a text editor or script to map all the `default` responses to the correct HTTP code. 

Closing the issue for now, but feel free to re-open if you feel otherwise or find any reasons to consider `default` as a positive response. 

Thanks!

**Comment by hubts** [comment]
By the answer of @soorajshankar , it is right that I should have set a response status code. 

The problem solved by setting the status code as 201 (In my case, POST method it is). Then, the object property name was changed from `default` to `201`. Using `ApiResponse` decorator provided in NestJS solved the problem.

After setting the status code, importing OpenAPI spec in Hasura actions can find my response type correctly.

Thank you for correcting my mistake.
