### ISSUE TITLE
Escape sequence not honored for Array of character varying field in Postgres

### ISSUE THREAD

**Issue by CuriousLearner** [hasura/graphql-engine#9972]
### Version Information

Server Version: v2.34.0

### Environment

OSS

### What is the current behaviour?

If you add escape sequence to update array of char fields, it trims down the `\` char before inserting in the database, causing issues while using escape sequences.

Example mutation:

```
mutation {
  updateMyObjectByPk(pkColumns: {id: "a483586e-0f54-4688-a8e6-a66b05f9efdc"}, _set: {MyArrayField: ["Hello there \nHow are you"]}) {
    id
    MyArrayField
  }
}
```

Response:

```
{
  "data": {
    "updateMyObjectByPk": {
      "id": "a483586e-0f54-4688-a8e6-a66b05f9efdc",
      "MyArrayField": [
        "Hello there nHow are you"
      ]
    }
  }
}
```

### What is the expected behaviour?

Expected behaviour is that escape sequence should be inserted as it is in the DB and not trimmed.

So, the response should be:

```
{
  "data": {
    "updateMyObjectByPk": {
      "id": "a483586e-0f54-4688-a8e6-a66b05f9efdc",
      "MyArrayField": [
        "Hello there \nHow are you"
      ]
    }
  }
}
```

### Keywords

escape sequence, escaping, arrayfield, postgres

**Comment by CuriousLearner** [comment]
Hello,

Any updates on this, please?

**Comment by plcplc** [comment]
Hi @CuriousLearner 

We acknowledge there is an issue with escape characters not being handled correctly in the input of arrays on postgres.

We've had a thorough look at fixing it, but it turns out to be quite non-trivial.

So as of now we don't have a commitment on fixing this.

As per our expectations, this issue should not be present in the new Hasura v3, since the design already takes array value input into consideration.

**Comment by plcplc** [comment]
Hi @CuriousLearner 

We acknowledge there is an issue with escape characters not being handled correctly in the input of arrays on postgres.

We've had a thorough look at fixing it, but it turns out to be quite non-trivial.

So as of now we don't have a commitment on fixing this.

As per our expectations, this issue should not be present in the new Hasura v3, since the design already takes array value input into consideration.
